// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: access.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvitation = `-- name: AcceptInvitation :execrows
UPDATE invitations SET accepted_at=now(),totp_ciphertext=NULL WHERE id=$1 AND accepted_at IS NULL AND revoked_at IS NULL AND expires_at>now()
`

func (q *Queries) AcceptInvitation(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, acceptInvitation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const administratorCount = `-- name: AdministratorCount :one
SELECT count(*) FROM memberships m JOIN users u ON u.id=m.user_id WHERE m.org_id=$1 AND m.role_id='administrator' AND m.active AND u.active
`

func (q *Queries) AdministratorCount(ctx context.Context, orgID string) (int64, error) {
	row := q.db.QueryRow(ctx, administratorCount, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBuiltinRoles = `-- name: CreateBuiltinRoles :exec
INSERT INTO roles(org_id,id,name,permissions,builtin)
SELECT $1,r.id,r.name,r.permissions||ARRAY['modules.read','templates.read']||CASE WHEN r.id IN ('administrator','connection-manager','auditor') THEN ARRAY['admin.access'] ELSE ARRAY[]::text[] END||CASE WHEN r.id='administrator' THEN ARRAY['modules.manage','templates.publish','dashboards.manage'] ELSE ARRAY[]::text[] END,true FROM (VALUES
 ('administrator','Administrator',ARRAY['connections.read','connections.manage','resources.read','audit.read','members.read','members.manage','roles.manage','operations.read','operations.request','operations.delete','operations.create','operations.approve','identity.manage','schedules.read','schedules.manage','notifications.read','notifications.manage','maintenance.read','maintenance.manage','maintenance.override','audit.export.manage']),
 ('viewer','Viewer',ARRAY['connections.read','resources.read']),
 ('connection-manager','Connection manager',ARRAY['connections.read','connections.manage','resources.read','maintenance.read']),
 ('auditor','Auditor',ARRAY['audit.read','notifications.read','maintenance.read']),
 ('operator','Operator',ARRAY['connections.read','resources.read','operations.read','operations.request','schedules.read','schedules.manage','notifications.read','maintenance.read']),
 ('approver','Approver',ARRAY['resources.read','operations.read','operations.approve','schedules.read','notifications.read','maintenance.read','maintenance.override'])
) AS r(id,name,permissions)
`

func (q *Queries) CreateBuiltinRoles(ctx context.Context, orgID string) error {
	_, err := q.db.Exec(ctx, createBuiltinRoles, orgID)
	return err
}

const createInvitation = `-- name: CreateInvitation :exec
INSERT INTO invitations(id,org_id,email,role_id,role_revision,inviter_id,token_hash) VALUES($1,$2,$3,$4,$5,$6,$7)
`

type CreateInvitationParams struct {
	ID           string
	OrgID        string
	Email        string
	RoleID       string
	RoleRevision int64
	InviterID    string
	TokenHash    []byte
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) error {
	_, err := q.db.Exec(ctx, createInvitation,
		arg.ID,
		arg.OrgID,
		arg.Email,
		arg.RoleID,
		arg.RoleRevision,
		arg.InviterID,
		arg.TokenHash,
	)
	return err
}

const createRole = `-- name: CreateRole :exec
INSERT INTO roles(org_id,id,name,permissions) VALUES($1,$2,$3,$4)
`

type CreateRoleParams struct {
	OrgID       string
	ID          string
	Name        string
	Permissions []string
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) error {
	_, err := q.db.Exec(ctx, createRole,
		arg.OrgID,
		arg.ID,
		arg.Name,
		arg.Permissions,
	)
	return err
}

const enrollInvitation = `-- name: EnrollInvitation :exec
UPDATE invitations SET totp_ciphertext=$2 WHERE id=$1
`

type EnrollInvitationParams struct {
	ID             string
	TotpCiphertext []byte
}

func (q *Queries) EnrollInvitation(ctx context.Context, arg EnrollInvitationParams) error {
	_, err := q.db.Exec(ctx, enrollInvitation, arg.ID, arg.TotpCiphertext)
	return err
}

const eventRevision = `-- name: EventRevision :one
SELECT o.revision FROM organizations o JOIN effective_memberships m ON m.org_id=o.id WHERE o.id=$1 AND m.user_id=$2
`

type EventRevisionParams struct {
	ID     string
	UserID string
}

func (q *Queries) EventRevision(ctx context.Context, arg EventRevisionParams) (int64, error) {
	row := q.db.QueryRow(ctx, eventRevision, arg.ID, arg.UserID)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const getRole = `-- name: GetRole :one
SELECT org_id, id, name, permissions, builtin, revision FROM roles WHERE org_id=$1 AND id=$2
`

type GetRoleParams struct {
	OrgID string
	ID    string
}

func (q *Queries) GetRole(ctx context.Context, arg GetRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, getRole, arg.OrgID, arg.ID)
	var i Role
	err := row.Scan(
		&i.OrgID,
		&i.ID,
		&i.Name,
		&i.Permissions,
		&i.Builtin,
		&i.Revision,
	)
	return i, err
}

const hasMembership = `-- name: HasMembership :one
SELECT EXISTS(SELECT 1 FROM memberships WHERE org_id=$1 AND user_id=$2)
`

type HasMembershipParams struct {
	OrgID  string
	UserID string
}

func (q *Queries) HasMembership(ctx context.Context, arg HasMembershipParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasMembership, arg.OrgID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const invitationByToken = `-- name: InvitationByToken :one
SELECT id, org_id, email, role_id, role_revision, inviter_id, token_hash, created_at, expires_at, revoked_at, accepted_at, totp_ciphertext FROM invitations WHERE token_hash=$1 AND revoked_at IS NULL AND accepted_at IS NULL AND expires_at>now()
`

func (q *Queries) InvitationByToken(ctx context.Context, tokenHash []byte) (Invitation, error) {
	row := q.db.QueryRow(ctx, invitationByToken, tokenHash)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.RoleID,
		&i.RoleRevision,
		&i.InviterID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.AcceptedAt,
		&i.TotpCiphertext,
	)
	return i, err
}

const joinMembership = `-- name: JoinMembership :exec
INSERT INTO memberships(org_id,user_id,permissions,role_id) VALUES($1,$2,'{}',$3)
`

type JoinMembershipParams struct {
	OrgID  string
	UserID string
	RoleID pgtype.Text
}

func (q *Queries) JoinMembership(ctx context.Context, arg JoinMembershipParams) error {
	_, err := q.db.Exec(ctx, joinMembership, arg.OrgID, arg.UserID, arg.RoleID)
	return err
}

const listInvitations = `-- name: ListInvitations :many
SELECT i.id,i.email,i.role_id,r.name AS role_name,i.expires_at FROM invitations i JOIN roles r ON r.org_id=i.org_id AND r.id=i.role_id WHERE i.org_id=$1 AND i.revoked_at IS NULL AND i.accepted_at IS NULL AND i.expires_at>now() ORDER BY i.created_at DESC LIMIT 1001
`

type ListInvitationsRow struct {
	ID        string
	Email     string
	RoleID    string
	RoleName  string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) ListInvitations(ctx context.Context, orgID string) ([]ListInvitationsRow, error) {
	rows, err := q.db.Query(ctx, listInvitations, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvitationsRow{}
	for rows.Next() {
		var i ListInvitationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.RoleID,
			&i.RoleName,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT m.user_id,u.email,m.active,m.revision,u.active AS user_active,coalesce(m.role_id,'')::text AS role_id,coalesce(r.name,'Custom legacy grant')::text AS role_name,coalesce(em.permissions,r.permissions,m.permissions)::text[] AS permissions
FROM memberships m JOIN users u ON u.id=m.user_id LEFT JOIN roles r ON r.org_id=m.org_id AND r.id=m.role_id LEFT JOIN effective_memberships em ON em.org_id=m.org_id AND em.user_id=m.user_id WHERE m.org_id=$1 ORDER BY u.email LIMIT 1001
`

type ListMembersRow struct {
	UserID      string
	Email       string
	Active      bool
	Revision    int64
	UserActive  bool
	RoleID      string
	RoleName    string
	Permissions []string
}

func (q *Queries) ListMembers(ctx context.Context, orgID string) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersRow{}
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.Active,
			&i.Revision,
			&i.UserActive,
			&i.RoleID,
			&i.RoleName,
			&i.Permissions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT org_id, id, name, permissions, builtin, revision FROM roles WHERE org_id=$1 ORDER BY builtin DESC,name
`

func (q *Queries) ListRoles(ctx context.Context, orgID string) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.OrgID,
			&i.ID,
			&i.Name,
			&i.Permissions,
			&i.Builtin,
			&i.Revision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAccess = `-- name: LockAccess :one
SELECT id FROM organizations WHERE id=$1 AND active FOR UPDATE
`

func (q *Queries) LockAccess(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, lockAccess, id)
	err := row.Scan(&id)
	return id, err
}

const revokeInvitation = `-- name: RevokeInvitation :execrows
UPDATE invitations SET revoked_at=now(),totp_ciphertext=NULL WHERE org_id=$1 AND id=$2 AND accepted_at IS NULL AND revoked_at IS NULL
`

type RevokeInvitationParams struct {
	OrgID string
	ID    string
}

func (q *Queries) RevokeInvitation(ctx context.Context, arg RevokeInvitationParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeInvitation, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setMember = `-- name: SetMember :execrows
UPDATE memberships SET role_id=$3,active=$4 WHERE org_id=$1 AND user_id=$2 AND revision=$5
`

type SetMemberParams struct {
	OrgID    string
	UserID   string
	RoleID   pgtype.Text
	Active   bool
	Revision int64
}

func (q *Queries) SetMember(ctx context.Context, arg SetMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, setMember,
		arg.OrgID,
		arg.UserID,
		arg.RoleID,
		arg.Active,
		arg.Revision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRole = `-- name: UpdateRole :execrows
UPDATE roles SET name=$3,permissions=$4,revision=revision+1 WHERE org_id=$1 AND id=$2 AND NOT builtin AND revision=$5
`

type UpdateRoleParams struct {
	OrgID       string
	ID          string
	Name        string
	Permissions []string
	Revision    int64
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRole,
		arg.OrgID,
		arg.ID,
		arg.Name,
		arg.Permissions,
		arg.Revision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const userExists = `-- name: UserExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE email=$1)
`

func (q *Queries) UserExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, userExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const verifySessionMFA = `-- name: VerifySessionMFA :exec
UPDATE sessions SET mfa_at=now() WHERE id=$1
`

func (q *Queries) VerifySessionMFA(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, verifySessionMFA, id)
	return err
}
