// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_export.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceAuditExport = `-- name: AdvanceAuditExport :exec
UPDATE audit_exports SET cursor_id=$2,next_batch_at=now(),detail='Last batch stored and verified.',updated_at=now() WHERE org_id=$1
`

type AdvanceAuditExportParams struct {
	OrgID    string
	CursorID int64
}

func (q *Queries) AdvanceAuditExport(ctx context.Context, arg AdvanceAuditExportParams) error {
	_, err := q.db.Exec(ctx, advanceAuditExport, arg.OrgID, arg.CursorID)
	return err
}

const auditExportActive = `-- name: AuditExportActive :one
SELECT EXISTS(SELECT 1 FROM audit_export_batches WHERE org_id=$1 AND status IN ('pending','running'))
`

func (q *Queries) AuditExportActive(ctx context.Context, orgID string) (bool, error) {
	row := q.db.QueryRow(ctx, auditExportActive, orgID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const auditExportBacklog = `-- name: AuditExportBacklog :one
SELECT count(*)::bigint AS events,min(occurred_at)::timestamptz AS oldest FROM audit_events WHERE org_id=$1 AND id>$2
`

type AuditExportBacklogParams struct {
	OrgID string
	ID    int64
}

type AuditExportBacklogRow struct {
	Events int64
	Oldest pgtype.Timestamptz
}

func (q *Queries) AuditExportBacklog(ctx context.Context, arg AuditExportBacklogParams) (AuditExportBacklogRow, error) {
	row := q.db.QueryRow(ctx, auditExportBacklog, arg.OrgID, arg.ID)
	var i AuditExportBacklogRow
	err := row.Scan(&i.Events, &i.Oldest)
	return i, err
}

const auditExportRows = `-- name: AuditExportRows :many
SELECT id, org_id, actor, action, target, details, occurred_at FROM audit_events WHERE org_id=$1 AND id>$2 ORDER BY id LIMIT 100
`

type AuditExportRowsParams struct {
	OrgID string
	ID    int64
}

func (q *Queries) AuditExportRows(ctx context.Context, arg AuditExportRowsParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, auditExportRows, arg.OrgID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Actor,
			&i.Action,
			&i.Target,
			&i.Details,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bumpAuditExportVisibility = `-- name: BumpAuditExportVisibility :exec
UPDATE organizations SET revision=revision+1 WHERE id=$1
`

func (q *Queries) BumpAuditExportVisibility(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, bumpAuditExportVisibility, id)
	return err
}

const cancelAuditExportBatches = `-- name: CancelAuditExportBatches :exec
UPDATE audit_export_batches SET status='canceled',payload=''::bytea,detail='Export configuration changed or was paused.',updated_at=now() WHERE org_id=$1 AND status IN ('pending','running')
`

func (q *Queries) CancelAuditExportBatches(ctx context.Context, orgID string) error {
	_, err := q.db.Exec(ctx, cancelAuditExportBatches, orgID)
	return err
}

const claimAuditExportBatch = `-- name: ClaimAuditExportBatch :one
UPDATE audit_export_batches SET status='running',attempts=attempts+1,lease_until=now()+interval '60 seconds',updated_at=now()
WHERE id=(SELECT id FROM audit_export_batches WHERE (status='pending' AND next_attempt<=now()) OR (status='running' AND lease_until<now()) ORDER BY next_attempt,id FOR UPDATE SKIP LOCKED LIMIT 1) RETURNING id, org_id, revision, kind, first_id, last_id, event_count, payload, checksum, object_key, status, attempts, next_attempt, lease_until, detail, created_at, updated_at
`

func (q *Queries) ClaimAuditExportBatch(ctx context.Context) (AuditExportBatch, error) {
	row := q.db.QueryRow(ctx, claimAuditExportBatch)
	var i AuditExportBatch
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Revision,
		&i.Kind,
		&i.FirstID,
		&i.LastID,
		&i.EventCount,
		&i.Payload,
		&i.Checksum,
		&i.ObjectKey,
		&i.Status,
		&i.Attempts,
		&i.NextAttempt,
		&i.LeaseUntil,
		&i.Detail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAuditExportBatch = `-- name: CreateAuditExportBatch :exec
INSERT INTO audit_export_batches(id,org_id,revision,kind,first_id,last_id,event_count,payload,checksum,object_key) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
`

type CreateAuditExportBatchParams struct {
	ID         string
	OrgID      string
	Revision   int64
	Kind       string
	FirstID    int64
	LastID     int64
	EventCount int32
	Payload    []byte
	Checksum   string
	ObjectKey  string
}

func (q *Queries) CreateAuditExportBatch(ctx context.Context, arg CreateAuditExportBatchParams) error {
	_, err := q.db.Exec(ctx, createAuditExportBatch,
		arg.ID,
		arg.OrgID,
		arg.Revision,
		arg.Kind,
		arg.FirstID,
		arg.LastID,
		arg.EventCount,
		arg.Payload,
		arg.Checksum,
		arg.ObjectKey,
	)
	return err
}

const delayAuditExport = `-- name: DelayAuditExport :exec
UPDATE audit_exports SET next_batch_at=now()+interval '30 seconds' WHERE org_id=$1
`

func (q *Queries) DelayAuditExport(ctx context.Context, orgID string) error {
	_, err := q.db.Exec(ctx, delayAuditExport, orgID)
	return err
}

const failAuditExport = `-- name: FailAuditExport :exec
UPDATE audit_exports SET detail='Export failed. Local audit is retained; retry is scheduled.',updated_at=now() WHERE org_id=$1
`

func (q *Queries) FailAuditExport(ctx context.Context, orgID string) error {
	_, err := q.db.Exec(ctx, failAuditExport, orgID)
	return err
}

const finishAuditExportBatch = `-- name: FinishAuditExportBatch :exec
UPDATE audit_export_batches SET status=$3,payload=CASE WHEN $3 IN ('succeeded','canceled') THEN ''::bytea ELSE payload END,detail=$4,next_attempt=$5,lease_until=NULL,updated_at=now() WHERE org_id=$1 AND id=$2
`

type FinishAuditExportBatchParams struct {
	OrgID       string
	ID          string
	Status      string
	Detail      string
	NextAttempt pgtype.Timestamptz
}

func (q *Queries) FinishAuditExportBatch(ctx context.Context, arg FinishAuditExportBatchParams) error {
	_, err := q.db.Exec(ctx, finishAuditExportBatch,
		arg.OrgID,
		arg.ID,
		arg.Status,
		arg.Detail,
		arg.NextAttempt,
	)
	return err
}

const getAuditExport = `-- name: GetAuditExport :one
SELECT org_id, endpoint, region, bucket, ciphertext, revision, enabled, verified, cursor_id, next_batch_at, detail, updated_at FROM audit_exports WHERE org_id=$1
`

func (q *Queries) GetAuditExport(ctx context.Context, orgID string) (AuditExport, error) {
	row := q.db.QueryRow(ctx, getAuditExport, orgID)
	var i AuditExport
	err := row.Scan(
		&i.OrgID,
		&i.Endpoint,
		&i.Region,
		&i.Bucket,
		&i.Ciphertext,
		&i.Revision,
		&i.Enabled,
		&i.Verified,
		&i.CursorID,
		&i.NextBatchAt,
		&i.Detail,
		&i.UpdatedAt,
	)
	return i, err
}

const listAuditExportBatches = `-- name: ListAuditExportBatches :many
SELECT id,kind,first_id,last_id,event_count,checksum,object_key,status,attempts,detail,updated_at FROM audit_export_batches WHERE org_id=$1 AND id<$2 ORDER BY id DESC LIMIT 101
`

type ListAuditExportBatchesParams struct {
	OrgID string
	ID    string
}

type ListAuditExportBatchesRow struct {
	ID         string
	Kind       string
	FirstID    int64
	LastID     int64
	EventCount int32
	Checksum   string
	ObjectKey  string
	Status     string
	Attempts   int32
	Detail     string
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) ListAuditExportBatches(ctx context.Context, arg ListAuditExportBatchesParams) ([]ListAuditExportBatchesRow, error) {
	rows, err := q.db.Query(ctx, listAuditExportBatches, arg.OrgID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditExportBatchesRow{}
	for rows.Next() {
		var i ListAuditExportBatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.FirstID,
			&i.LastID,
			&i.EventCount,
			&i.Checksum,
			&i.ObjectKey,
			&i.Status,
			&i.Attempts,
			&i.Detail,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAuditExportBatch = `-- name: LockAuditExportBatch :one
SELECT id, org_id, revision, kind, first_id, last_id, event_count, payload, checksum, object_key, status, attempts, next_attempt, lease_until, detail, created_at, updated_at FROM audit_export_batches WHERE org_id=$1 AND id=$2 FOR UPDATE
`

type LockAuditExportBatchParams struct {
	OrgID string
	ID    string
}

func (q *Queries) LockAuditExportBatch(ctx context.Context, arg LockAuditExportBatchParams) (AuditExportBatch, error) {
	row := q.db.QueryRow(ctx, lockAuditExportBatch, arg.OrgID, arg.ID)
	var i AuditExportBatch
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Revision,
		&i.Kind,
		&i.FirstID,
		&i.LastID,
		&i.EventCount,
		&i.Payload,
		&i.Checksum,
		&i.ObjectKey,
		&i.Status,
		&i.Attempts,
		&i.NextAttempt,
		&i.LeaseUntil,
		&i.Detail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockAuditScope = `-- name: LockAuditScope :one
SELECT id FROM organizations WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockAuditScope(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, lockAuditScope, id)
	err := row.Scan(&id)
	return id, err
}

const nextAuditExport = `-- name: NextAuditExport :one
SELECT e.org_id FROM audit_exports e WHERE e.enabled AND e.verified AND e.next_batch_at<=now() AND NOT EXISTS(SELECT 1 FROM audit_export_batches b WHERE b.org_id=e.org_id AND b.status IN ('pending','running')) ORDER BY e.next_batch_at,e.org_id LIMIT 1
`

func (q *Queries) NextAuditExport(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, nextAuditExport)
	var org_id string
	err := row.Scan(&org_id)
	return org_id, err
}

const retryAuditExport = `-- name: RetryAuditExport :exec
UPDATE audit_export_batches SET next_attempt=now() WHERE org_id=$1 AND status='pending'
`

func (q *Queries) RetryAuditExport(ctx context.Context, orgID string) error {
	_, err := q.db.Exec(ctx, retryAuditExport, orgID)
	return err
}

const saveAuditExport = `-- name: SaveAuditExport :exec
INSERT INTO audit_exports(org_id,endpoint,region,bucket,ciphertext) VALUES($1,$2,$3,$4,$5)
ON CONFLICT(org_id) DO UPDATE SET endpoint=excluded.endpoint,region=excluded.region,bucket=excluded.bucket,ciphertext=excluded.ciphertext,revision=audit_exports.revision+1,enabled=false,verified=false,cursor_id=0,next_batch_at=now(),detail='',updated_at=now()
`

type SaveAuditExportParams struct {
	OrgID      string
	Endpoint   string
	Region     string
	Bucket     string
	Ciphertext []byte
}

func (q *Queries) SaveAuditExport(ctx context.Context, arg SaveAuditExportParams) error {
	_, err := q.db.Exec(ctx, saveAuditExport,
		arg.OrgID,
		arg.Endpoint,
		arg.Region,
		arg.Bucket,
		arg.Ciphertext,
	)
	return err
}

const setAuditExportEnabled = `-- name: SetAuditExportEnabled :exec
UPDATE audit_exports SET enabled=$2,next_batch_at=now(),updated_at=now() WHERE org_id=$1
`

type SetAuditExportEnabledParams struct {
	OrgID   string
	Enabled bool
}

func (q *Queries) SetAuditExportEnabled(ctx context.Context, arg SetAuditExportEnabledParams) error {
	_, err := q.db.Exec(ctx, setAuditExportEnabled, arg.OrgID, arg.Enabled)
	return err
}

const verifyAuditExport = `-- name: VerifyAuditExport :exec
UPDATE audit_exports SET verified=true,detail='Storage probe verified. Enable continuous export when ready.',updated_at=now() WHERE org_id=$1
`

func (q *Queries) VerifyAuditExport(ctx context.Context, orgID string) error {
	_, err := q.db.Exec(ctx, verifyAuditExport, orgID)
	return err
}
