// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: automation_versions.sql

package database

import (
	"context"
)

const getAutomationVersion = `-- name: GetAutomationVersion :one
SELECT id, org_id, name, version, source_id, runtime_image, runtime_version, runtime, connection_id, connection_revision, region, review_note, status, created_at, runtime_policy, dependency_hosts FROM automation_versions WHERE org_id=$1 AND id=$2
`

type GetAutomationVersionParams struct {
	OrgID string
	ID    string
}

func (q *Queries) GetAutomationVersion(ctx context.Context, arg GetAutomationVersionParams) (AutomationVersion, error) {
	row := q.db.QueryRow(ctx, getAutomationVersion, arg.OrgID, arg.ID)
	var i AutomationVersion
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Version,
		&i.SourceID,
		&i.RuntimeImage,
		&i.RuntimeVersion,
		&i.Runtime,
		&i.ConnectionID,
		&i.ConnectionRevision,
		&i.Region,
		&i.ReviewNote,
		&i.Status,
		&i.CreatedAt,
		&i.RuntimePolicy,
		&i.DependencyHosts,
	)
	return i, err
}

const listAutomationVersions = `-- name: ListAutomationVersions :many
SELECT id, org_id, name, version, source_id, runtime_image, runtime_version, runtime, connection_id, connection_revision, region, review_note, status, created_at, runtime_policy, dependency_hosts FROM automation_versions WHERE org_id=$1 ORDER BY name,version DESC LIMIT 201
`

func (q *Queries) ListAutomationVersions(ctx context.Context, orgID string) ([]AutomationVersion, error) {
	rows, err := q.db.Query(ctx, listAutomationVersions, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AutomationVersion{}
	for rows.Next() {
		var i AutomationVersion
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Version,
			&i.SourceID,
			&i.RuntimeImage,
			&i.RuntimeVersion,
			&i.Runtime,
			&i.ConnectionID,
			&i.ConnectionRevision,
			&i.Region,
			&i.ReviewNote,
			&i.Status,
			&i.CreatedAt,
			&i.RuntimePolicy,
			&i.DependencyHosts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishAutomationVersion = `-- name: PublishAutomationVersion :one
INSERT INTO automation_versions(id,org_id,name,version,source_id,runtime_image,runtime_version,connection_id,connection_revision,region,review_note,runtime,runtime_policy,dependency_hosts)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING id, org_id, name, version, source_id, runtime_image, runtime_version, runtime, connection_id, connection_revision, region, review_note, status, created_at, runtime_policy, dependency_hosts
`

type PublishAutomationVersionParams struct {
	ID                 string
	OrgID              string
	Name               string
	Version            int32
	SourceID           string
	RuntimeImage       string
	RuntimeVersion     string
	ConnectionID       string
	ConnectionRevision int64
	Region             string
	ReviewNote         string
	Runtime            string
	RuntimePolicy      string
	DependencyHosts    []string
}

func (q *Queries) PublishAutomationVersion(ctx context.Context, arg PublishAutomationVersionParams) (AutomationVersion, error) {
	row := q.db.QueryRow(ctx, publishAutomationVersion,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Version,
		arg.SourceID,
		arg.RuntimeImage,
		arg.RuntimeVersion,
		arg.ConnectionID,
		arg.ConnectionRevision,
		arg.Region,
		arg.ReviewNote,
		arg.Runtime,
		arg.RuntimePolicy,
		arg.DependencyHosts,
	)
	var i AutomationVersion
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Version,
		&i.SourceID,
		&i.RuntimeImage,
		&i.RuntimeVersion,
		&i.Runtime,
		&i.ConnectionID,
		&i.ConnectionRevision,
		&i.Region,
		&i.ReviewNote,
		&i.Status,
		&i.CreatedAt,
		&i.RuntimePolicy,
		&i.DependencyHosts,
	)
	return i, err
}

const setAutomationVersionStatus = `-- name: SetAutomationVersionStatus :one
UPDATE automation_versions SET status=$3 WHERE org_id=$1 AND id=$2 AND (status='published' OR (status='retired' AND $3='revoked')) RETURNING id, org_id, name, version, source_id, runtime_image, runtime_version, runtime, connection_id, connection_revision, region, review_note, status, created_at, runtime_policy, dependency_hosts
`

type SetAutomationVersionStatusParams struct {
	OrgID  string
	ID     string
	Status string
}

func (q *Queries) SetAutomationVersionStatus(ctx context.Context, arg SetAutomationVersionStatusParams) (AutomationVersion, error) {
	row := q.db.QueryRow(ctx, setAutomationVersionStatus, arg.OrgID, arg.ID, arg.Status)
	var i AutomationVersion
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Version,
		&i.SourceID,
		&i.RuntimeImage,
		&i.RuntimeVersion,
		&i.Runtime,
		&i.ConnectionID,
		&i.ConnectionRevision,
		&i.Region,
		&i.ReviewNote,
		&i.Status,
		&i.CreatedAt,
		&i.RuntimePolicy,
		&i.DependencyHosts,
	)
	return i, err
}
