// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: automation_validation.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activeAutomationValidation = `-- name: ActiveAutomationValidation :one
SELECT id, org_id, version_id, requester_id, requester_email, requester_oidc_id, status, detail, created_at, updated_at, lease_until, project_id FROM automation_validations WHERE org_id=$1 AND version_id=$2 AND project_id=$3 AND status IN ('queued','running')
`

type ActiveAutomationValidationParams struct {
	OrgID     string
	VersionID string
	ProjectID string
}

func (q *Queries) ActiveAutomationValidation(ctx context.Context, arg ActiveAutomationValidationParams) (AutomationValidation, error) {
	row := q.db.QueryRow(ctx, activeAutomationValidation, arg.OrgID, arg.VersionID, arg.ProjectID)
	var i AutomationValidation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.VersionID,
		&i.RequesterID,
		&i.RequesterEmail,
		&i.RequesterOidcID,
		&i.Status,
		&i.Detail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LeaseUntil,
		&i.ProjectID,
	)
	return i, err
}

const automationValidationRunning = `-- name: AutomationValidationRunning :one
SELECT EXISTS(SELECT 1 FROM automation_validations WHERE id=$1 AND status='running' AND lease_until>now())::boolean
`

func (q *Queries) AutomationValidationRunning(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, automationValidationRunning, id)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const automationValidationSource = `-- name: AutomationValidationSource :one
SELECT v.id, v.org_id, v.name, v.version, v.source_id, v.runtime_image, v.runtime_version, v.runtime, v.connection_id, v.connection_revision, v.region, v.review_note, v.status, v.created_at, v.runtime_policy, v.dependency_hosts,s.ciphertext,s.storage,s.entrypoint,s.sha256,s.input_schema FROM automation_versions v JOIN automation_sources s ON s.org_id=v.org_id AND s.id=v.source_id WHERE v.org_id=$1 AND v.id=$2 FOR SHARE OF v,s
`

type AutomationValidationSourceParams struct {
	OrgID string
	ID    string
}

type AutomationValidationSourceRow struct {
	ID                 string
	OrgID              string
	Name               string
	Version            int32
	SourceID           string
	RuntimeImage       string
	RuntimeVersion     string
	Runtime            string
	ConnectionID       string
	ConnectionRevision int64
	Region             string
	ReviewNote         string
	Status             string
	CreatedAt          pgtype.Timestamptz
	RuntimePolicy      string
	DependencyHosts    []string
	Ciphertext         []byte
	Storage            string
	Entrypoint         string
	Sha256             string
	InputSchema        []byte
}

func (q *Queries) AutomationValidationSource(ctx context.Context, arg AutomationValidationSourceParams) (AutomationValidationSourceRow, error) {
	row := q.db.QueryRow(ctx, automationValidationSource, arg.OrgID, arg.ID)
	var i AutomationValidationSourceRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Version,
		&i.SourceID,
		&i.RuntimeImage,
		&i.RuntimeVersion,
		&i.Runtime,
		&i.ConnectionID,
		&i.ConnectionRevision,
		&i.Region,
		&i.ReviewNote,
		&i.Status,
		&i.CreatedAt,
		&i.RuntimePolicy,
		&i.DependencyHosts,
		&i.Ciphertext,
		&i.Storage,
		&i.Entrypoint,
		&i.Sha256,
		&i.InputSchema,
	)
	return i, err
}

const cancelAutomationValidation = `-- name: CancelAutomationValidation :one
UPDATE automation_validations SET status='canceled',detail='Canceled by an authorized publisher.',updated_at=now()
WHERE org_id=$1 AND id=$2 AND status IN ('queued','running') RETURNING id, org_id, version_id, requester_id, requester_email, requester_oidc_id, status, detail, created_at, updated_at, lease_until, project_id
`

type CancelAutomationValidationParams struct {
	OrgID string
	ID    string
}

func (q *Queries) CancelAutomationValidation(ctx context.Context, arg CancelAutomationValidationParams) (AutomationValidation, error) {
	row := q.db.QueryRow(ctx, cancelAutomationValidation, arg.OrgID, arg.ID)
	var i AutomationValidation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.VersionID,
		&i.RequesterID,
		&i.RequesterEmail,
		&i.RequesterOidcID,
		&i.Status,
		&i.Detail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LeaseUntil,
		&i.ProjectID,
	)
	return i, err
}

const claimAutomationValidation = `-- name: ClaimAutomationValidation :one
UPDATE automation_validations SET status='running',lease_until=now()+interval '3 minutes',updated_at=now() WHERE id=(SELECT id FROM automation_validations WHERE status='queued' AND created_at>now()-interval '30 minutes' ORDER BY created_at,id FOR UPDATE SKIP LOCKED LIMIT 1) RETURNING id, org_id, version_id, requester_id, requester_email, requester_oidc_id, status, detail, created_at, updated_at, lease_until, project_id
`

func (q *Queries) ClaimAutomationValidation(ctx context.Context) (AutomationValidation, error) {
	row := q.db.QueryRow(ctx, claimAutomationValidation)
	var i AutomationValidation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.VersionID,
		&i.RequesterID,
		&i.RequesterEmail,
		&i.RequesterOidcID,
		&i.Status,
		&i.Detail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LeaseUntil,
		&i.ProjectID,
	)
	return i, err
}

const expireAutomationValidations = `-- name: ExpireAutomationValidations :many
UPDATE automation_validations SET status='failed',detail='Validation expired or was interrupted. Request a new check.',updated_at=now() WHERE (status='running' AND lease_until<=now()) OR (status='queued' AND created_at<=now()-interval '30 minutes') RETURNING id, org_id, version_id, requester_id, requester_email, requester_oidc_id, status, detail, created_at, updated_at, lease_until, project_id
`

func (q *Queries) ExpireAutomationValidations(ctx context.Context) ([]AutomationValidation, error) {
	rows, err := q.db.Query(ctx, expireAutomationValidations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AutomationValidation{}
	for rows.Next() {
		var i AutomationValidation
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.VersionID,
			&i.RequesterID,
			&i.RequesterEmail,
			&i.RequesterOidcID,
			&i.Status,
			&i.Detail,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LeaseUntil,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishAutomationValidation = `-- name: FinishAutomationValidation :exec
UPDATE automation_validations SET status=$2,detail=$3,updated_at=now() WHERE id=$1 AND status='running' AND lease_until>now()
`

type FinishAutomationValidationParams struct {
	ID     string
	Status string
	Detail string
}

func (q *Queries) FinishAutomationValidation(ctx context.Context, arg FinishAutomationValidationParams) error {
	_, err := q.db.Exec(ctx, finishAutomationValidation, arg.ID, arg.Status, arg.Detail)
	return err
}

const getAutomationValidation = `-- name: GetAutomationValidation :one
SELECT id, org_id, version_id, requester_id, requester_email, requester_oidc_id, status, detail, created_at, updated_at, lease_until, project_id FROM automation_validations WHERE org_id=$1 AND id=$2
`

type GetAutomationValidationParams struct {
	OrgID string
	ID    string
}

func (q *Queries) GetAutomationValidation(ctx context.Context, arg GetAutomationValidationParams) (AutomationValidation, error) {
	row := q.db.QueryRow(ctx, getAutomationValidation, arg.OrgID, arg.ID)
	var i AutomationValidation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.VersionID,
		&i.RequesterID,
		&i.RequesterEmail,
		&i.RequesterOidcID,
		&i.Status,
		&i.Detail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LeaseUntil,
		&i.ProjectID,
	)
	return i, err
}

const listAutomationValidations = `-- name: ListAutomationValidations :many
SELECT id, org_id, version_id, requester_id, requester_email, requester_oidc_id, status, detail, created_at, updated_at, lease_until, project_id FROM automation_validations WHERE org_id=$1 AND ($2::text='' OR status=$2) AND ($3::timestamptz IS NULL OR (created_at,id)<($3::timestamptz,$4::text)) ORDER BY created_at DESC,id DESC LIMIT 101
`

type ListAutomationValidationsParams struct {
	OrgID    string
	Status   string
	BeforeAt pgtype.Timestamptz
	BeforeID string
}

func (q *Queries) ListAutomationValidations(ctx context.Context, arg ListAutomationValidationsParams) ([]AutomationValidation, error) {
	rows, err := q.db.Query(ctx, listAutomationValidations,
		arg.OrgID,
		arg.Status,
		arg.BeforeAt,
		arg.BeforeID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AutomationValidation{}
	for rows.Next() {
		var i AutomationValidation
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.VersionID,
			&i.RequesterID,
			&i.RequesterEmail,
			&i.RequesterOidcID,
			&i.Status,
			&i.Detail,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LeaseUntil,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAutomationValidation = `-- name: LockAutomationValidation :one
SELECT id, org_id, version_id, requester_id, requester_email, requester_oidc_id, status, detail, created_at, updated_at, lease_until, project_id FROM automation_validations WHERE id=$1 AND status='running' AND lease_until>now() FOR UPDATE
`

func (q *Queries) LockAutomationValidation(ctx context.Context, id string) (AutomationValidation, error) {
	row := q.db.QueryRow(ctx, lockAutomationValidation, id)
	var i AutomationValidation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.VersionID,
		&i.RequesterID,
		&i.RequesterEmail,
		&i.RequesterOidcID,
		&i.Status,
		&i.Detail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LeaseUntil,
		&i.ProjectID,
	)
	return i, err
}

const queueAutomationValidation = `-- name: QueueAutomationValidation :one
INSERT INTO automation_validations(id,org_id,version_id,requester_id,requester_email,requester_oidc_id,project_id) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(org_id,version_id,project_id) WHERE status IN ('queued','running') DO NOTHING RETURNING id, org_id, version_id, requester_id, requester_email, requester_oidc_id, status, detail, created_at, updated_at, lease_until, project_id
`

type QueueAutomationValidationParams struct {
	ID              string
	OrgID           string
	VersionID       string
	RequesterID     string
	RequesterEmail  string
	RequesterOidcID pgtype.UUID
	ProjectID       string
}

func (q *Queries) QueueAutomationValidation(ctx context.Context, arg QueueAutomationValidationParams) (AutomationValidation, error) {
	row := q.db.QueryRow(ctx, queueAutomationValidation,
		arg.ID,
		arg.OrgID,
		arg.VersionID,
		arg.RequesterID,
		arg.RequesterEmail,
		arg.RequesterOidcID,
		arg.ProjectID,
	)
	var i AutomationValidation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.VersionID,
		&i.RequesterID,
		&i.RequesterEmail,
		&i.RequesterOidcID,
		&i.Status,
		&i.Detail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LeaseUntil,
		&i.ProjectID,
	)
	return i, err
}
