// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: core.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addAudit = `-- name: AddAudit :exec
WITH locked AS MATERIALIZED (SELECT organizations.id FROM organizations WHERE organizations.id=$5 FOR UPDATE)
INSERT INTO audit_events(org_id,actor,action,target,details) SELECT locked.id,$1,$2,$3,$4 FROM locked
`

type AddAuditParams struct {
	Actor   string
	Action  string
	Target  string
	Details []byte
	OrgID   string
}

func (q *Queries) AddAudit(ctx context.Context, arg AddAuditParams) error {
	_, err := q.db.Exec(ctx, addAudit,
		arg.Actor,
		arg.Action,
		arg.Target,
		arg.Details,
		arg.OrgID,
	)
	return err
}

const addMembership = `-- name: AddMembership :exec
INSERT INTO memberships(org_id,user_id,permissions) VALUES($1,$2,$3)
`

type AddMembershipParams struct {
	OrgID       string
	UserID      string
	Permissions []string
}

func (q *Queries) AddMembership(ctx context.Context, arg AddMembershipParams) error {
	_, err := q.db.Exec(ctx, addMembership, arg.OrgID, arg.UserID, arg.Permissions)
	return err
}

const clearSetup = `-- name: ClearSetup :exec
DELETE FROM setup_pending
`

func (q *Queries) ClearSetup(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearSetup)
	return err
}

const consumeTOTP = `-- name: ConsumeTOTP :execrows
UPDATE users SET last_totp_step=$2 WHERE id=$1 AND active=true AND last_totp_step<$2
`

type ConsumeTOTPParams struct {
	ID           string
	LastTotpStep int64
}

func (q *Queries) ConsumeTOTP(ctx context.Context, arg ConsumeTOTPParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeTOTP, arg.ID, arg.LastTotpStep)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createConnection = `-- name: CreateConnection :one
INSERT INTO connections(id,org_id,name,provider,region,key_id,ciphertext,credential_source) VALUES($1,$2,$3,$4,$5,$6,$7,coalesce(nullif($8::text,''),'builtin')) RETURNING id,org_id,name,provider,region,enabled,created_at,scan_status,scan_error,last_scan_at,credential_source
`

type CreateConnectionParams struct {
	ID               string
	OrgID            string
	Name             string
	Provider         string
	Region           string
	KeyID            string
	Ciphertext       []byte
	CredentialSource string
}

type CreateConnectionRow struct {
	ID               string
	OrgID            string
	Name             string
	Provider         string
	Region           string
	Enabled          bool
	CreatedAt        pgtype.Timestamptz
	ScanStatus       string
	ScanError        string
	LastScanAt       pgtype.Timestamptz
	CredentialSource string
}

func (q *Queries) CreateConnection(ctx context.Context, arg CreateConnectionParams) (CreateConnectionRow, error) {
	row := q.db.QueryRow(ctx, createConnection,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Provider,
		arg.Region,
		arg.KeyID,
		arg.Ciphertext,
		arg.CredentialSource,
	)
	var i CreateConnectionRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Provider,
		&i.Region,
		&i.Enabled,
		&i.CreatedAt,
		&i.ScanStatus,
		&i.ScanError,
		&i.LastScanAt,
		&i.CredentialSource,
	)
	return i, err
}

const createOrganization = `-- name: CreateOrganization :exec
INSERT INTO organizations(id,name) VALUES($1,$2)
`

type CreateOrganizationParams struct {
	ID   string
	Name string
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) error {
	_, err := q.db.Exec(ctx, createOrganization, arg.ID, arg.Name)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions(id,user_id,refresh_hash,expires_at) VALUES($1,$2,$3,now()+interval '30 days')
`

type CreateSessionParams struct {
	ID          string
	UserID      string
	RefreshHash []byte
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.ID, arg.UserID, arg.RefreshHash)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users(id,email,password_hash,totp_ciphertext,last_totp_step) VALUES($1,$2,$3,$4,$5)
`

type CreateUserParams struct {
	ID             string
	Email          string
	PasswordHash   []byte
	TotpCiphertext []byte
	LastTotpStep   int64
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.TotpCiphertext,
		arg.LastTotpStep,
	)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id=$1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getConnectionMetadata = `-- name: GetConnectionMetadata :one
SELECT id,org_id,name,provider,region,enabled,created_at,scan_status,scan_error,last_scan_at,credential_source FROM connections WHERE org_id=$1 AND id=$2 AND deleted_at IS NULL
`

type GetConnectionMetadataParams struct {
	OrgID string
	ID    string
}

type GetConnectionMetadataRow struct {
	ID               string
	OrgID            string
	Name             string
	Provider         string
	Region           string
	Enabled          bool
	CreatedAt        pgtype.Timestamptz
	ScanStatus       string
	ScanError        string
	LastScanAt       pgtype.Timestamptz
	CredentialSource string
}

func (q *Queries) GetConnectionMetadata(ctx context.Context, arg GetConnectionMetadataParams) (GetConnectionMetadataRow, error) {
	row := q.db.QueryRow(ctx, getConnectionMetadata, arg.OrgID, arg.ID)
	var i GetConnectionMetadataRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Provider,
		&i.Region,
		&i.Enabled,
		&i.CreatedAt,
		&i.ScanStatus,
		&i.ScanError,
		&i.LastScanAt,
		&i.CredentialSource,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT s.id,s.user_id,s.mfa_at,s.oidc_id,u.email,u.mfa_enabled FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.id=$1 AND s.expires_at>now() AND u.active
`

type GetSessionRow struct {
	ID         string
	UserID     string
	MfaAt      pgtype.Timestamptz
	OidcID     pgtype.UUID
	Email      string
	MfaEnabled bool
}

func (q *Queries) GetSession(ctx context.Context, id string) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i GetSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MfaAt,
		&i.OidcID,
		&i.Email,
		&i.MfaEnabled,
	)
	return i, err
}

const listAudit = `-- name: ListAudit :many
SELECT id, org_id, actor, action, target, details, occurred_at FROM audit_events WHERE org_id=$1 AND id<$2
AND ($3::text='' OR actor=$3)
AND ($4::text='' OR action=$4)
AND ($5::text='' OR target=$5)
AND ($6::timestamptz IS NULL OR occurred_at>=$6)
AND ($7::timestamptz IS NULL OR occurred_at<$7)
ORDER BY id DESC LIMIT 101
`

type ListAuditParams struct {
	OrgID          string
	ID             int64
	Actor          string
	Action         string
	Target         string
	OccurredFrom   pgtype.Timestamptz
	OccurredBefore pgtype.Timestamptz
}

func (q *Queries) ListAudit(ctx context.Context, arg ListAuditParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAudit,
		arg.OrgID,
		arg.ID,
		arg.Actor,
		arg.Action,
		arg.Target,
		arg.OccurredFrom,
		arg.OccurredBefore,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Actor,
			&i.Action,
			&i.Target,
			&i.Details,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConnections = `-- name: ListConnections :many
SELECT id,org_id,name,provider,region,enabled,created_at,scan_status,scan_error,last_scan_at,credential_source FROM connections WHERE org_id=$1 AND deleted_at IS NULL ORDER BY created_at,id LIMIT 1000
`

type ListConnectionsRow struct {
	ID               string
	OrgID            string
	Name             string
	Provider         string
	Region           string
	Enabled          bool
	CreatedAt        pgtype.Timestamptz
	ScanStatus       string
	ScanError        string
	LastScanAt       pgtype.Timestamptz
	CredentialSource string
}

func (q *Queries) ListConnections(ctx context.Context, orgID string) ([]ListConnectionsRow, error) {
	rows, err := q.db.Query(ctx, listConnections, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConnectionsRow{}
	for rows.Next() {
		var i ListConnectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Provider,
			&i.Region,
			&i.Enabled,
			&i.CreatedAt,
			&i.ScanStatus,
			&i.ScanError,
			&i.LastScanAt,
			&i.CredentialSource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResources = `-- name: ListResources :many
WITH filtered AS (
SELECT id,connection_id,native_id,name,provider,kind,region,status,observed_at,public_ip,private_ip,size,tag_metadata,
(CASE $5::text WHEN 'name' THEN name WHEN 'provider' THEN provider WHEN 'kind' THEN kind WHEN 'region' THEN region WHEN 'status' THEN status ELSE id END COLLATE "C")::text AS sort_value
FROM filtered_inventory($6::text,$7::text,$8::text,$9::text,$10::text,$11::text,$12::text,$13::boolean,$14::text,$15::jsonb,$16::boolean,$17::text,$18::text)
)
SELECT id, connection_id, native_id, name, provider, kind, region, status, observed_at, public_ip, private_ip, size, tag_metadata, sort_value FROM filtered
WHERE $1::text='' OR
(NOT $2::boolean AND (sort_value,id)>($3::text COLLATE "C",$1::text)) OR
($2::boolean AND (sort_value,id)<($3::text COLLATE "C",$1::text))
ORDER BY CASE WHEN NOT $2::boolean THEN sort_value END ASC,
CASE WHEN $2::boolean THEN sort_value END DESC,
CASE WHEN NOT $2::boolean THEN id END ASC,
CASE WHEN $2::boolean THEN id END DESC LIMIT $4::integer
`

type ListResourcesParams struct {
	AfterID       string
	Descending    bool
	AfterValue    string
	PageSize      int32
	SortBy        string
	OrgID         string
	Search        string
	Provider      string
	Kind          string
	ConnectionID  string
	TagKey        string
	TagValue      string
	TagExists     bool
	TagName       string
	TagConditions []byte
	TagMatchAny   bool
	FilterRegion  string
	FilterStatus  string
}

type ListResourcesRow struct {
	ID           string
	ConnectionID string
	NativeID     string
	Name         string
	Provider     string
	Kind         string
	Region       string
	Status       string
	ObservedAt   pgtype.Timestamptz
	PublicIp     string
	PrivateIp    string
	Size         string
	TagMetadata  []byte
	SortValue    string
}

// ponytail: filtered result sorting uses PostgreSQL; add measured sort indexes if the 100k-resource load target needs them.
func (q *Queries) ListResources(ctx context.Context, arg ListResourcesParams) ([]ListResourcesRow, error) {
	rows, err := q.db.Query(ctx, listResources,
		arg.AfterID,
		arg.Descending,
		arg.AfterValue,
		arg.PageSize,
		arg.SortBy,
		arg.OrgID,
		arg.Search,
		arg.Provider,
		arg.Kind,
		arg.ConnectionID,
		arg.TagKey,
		arg.TagValue,
		arg.TagExists,
		arg.TagName,
		arg.TagConditions,
		arg.TagMatchAny,
		arg.FilterRegion,
		arg.FilterStatus,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListResourcesRow{}
	for rows.Next() {
		var i ListResourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.NativeID,
			&i.Name,
			&i.Provider,
			&i.Kind,
			&i.Region,
			&i.Status,
			&i.ObservedAt,
			&i.PublicIp,
			&i.PrivateIp,
			&i.Size,
			&i.TagMetadata,
			&i.SortValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSetup = `-- name: LockSetup :exec
SELECT pg_advisory_xact_lock(74193820)
`

func (q *Queries) LockSetup(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockSetup)
	return err
}

const organizationsForUser = `-- name: OrganizationsForUser :many
SELECT o.id,o.name,m.permissions FROM organizations o JOIN effective_memberships m ON m.org_id=o.id WHERE m.user_id=$1 ORDER BY o.name,o.id
`

type OrganizationsForUserRow struct {
	ID          string
	Name        string
	Permissions []string
}

func (q *Queries) OrganizationsForUser(ctx context.Context, userID string) ([]OrganizationsForUserRow, error) {
	rows, err := q.db.Query(ctx, organizationsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationsForUserRow{}
	for rows.Next() {
		var i OrganizationsForUserRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Permissions); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingSetup = `-- name: PendingSetup :one
SELECT ciphertext FROM setup_pending WHERE expires_at>now()
`

func (q *Queries) PendingSetup(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRow(ctx, pendingSetup)
	var ciphertext []byte
	err := row.Scan(&ciphertext)
	return ciphertext, err
}

const permissions = `-- name: Permissions :one
SELECT permissions FROM effective_memberships WHERE org_id=$1 AND user_id=$2
`

type PermissionsParams struct {
	OrgID  string
	UserID string
}

func (q *Queries) Permissions(ctx context.Context, arg PermissionsParams) ([]string, error) {
	row := q.db.QueryRow(ctx, permissions, arg.OrgID, arg.UserID)
	var permissions []string
	err := row.Scan(&permissions)
	return permissions, err
}

const rateLimit = `-- name: RateLimit :one
INSERT INTO auth_limits(key,window_at,attempts) VALUES($1,now(),1) ON CONFLICT(key) DO UPDATE SET window_at=CASE WHEN auth_limits.window_at<now()-interval '1 minute' THEN now() ELSE auth_limits.window_at END,attempts=CASE WHEN auth_limits.window_at<now()-interval '1 minute' THEN 1 ELSE auth_limits.attempts+1 END RETURNING attempts
`

func (q *Queries) RateLimit(ctx context.Context, key string) (int32, error) {
	row := q.db.QueryRow(ctx, rateLimit, key)
	var attempts int32
	err := row.Scan(&attempts)
	return attempts, err
}

const rotateCredential = `-- name: RotateCredential :one
UPDATE connections SET ciphertext=$3,key_id=$4,credential_source=coalesce(nullif($5::text,''),'builtin'),revision=revision+1,scan_status='never',scan_error='',next_scan_at=now() WHERE org_id=$1 AND id=$2 AND deleted_at IS NULL RETURNING id,org_id,name,provider,region,enabled,created_at,scan_status,scan_error,last_scan_at,credential_source
`

type RotateCredentialParams struct {
	OrgID            string
	ID               string
	Ciphertext       []byte
	KeyID            string
	CredentialSource string
}

type RotateCredentialRow struct {
	ID               string
	OrgID            string
	Name             string
	Provider         string
	Region           string
	Enabled          bool
	CreatedAt        pgtype.Timestamptz
	ScanStatus       string
	ScanError        string
	LastScanAt       pgtype.Timestamptz
	CredentialSource string
}

func (q *Queries) RotateCredential(ctx context.Context, arg RotateCredentialParams) (RotateCredentialRow, error) {
	row := q.db.QueryRow(ctx, rotateCredential,
		arg.OrgID,
		arg.ID,
		arg.Ciphertext,
		arg.KeyID,
		arg.CredentialSource,
	)
	var i RotateCredentialRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Provider,
		&i.Region,
		&i.Enabled,
		&i.CreatedAt,
		&i.ScanStatus,
		&i.ScanError,
		&i.LastScanAt,
		&i.CredentialSource,
	)
	return i, err
}

const rotateSession = `-- name: RotateSession :exec
UPDATE sessions SET refresh_hash=$2 WHERE id=$1
`

type RotateSessionParams struct {
	ID          string
	RefreshHash []byte
}

func (q *Queries) RotateSession(ctx context.Context, arg RotateSessionParams) error {
	_, err := q.db.Exec(ctx, rotateSession, arg.ID, arg.RefreshHash)
	return err
}

const sessionByRefresh = `-- name: SessionByRefresh :one
SELECT s.id,s.user_id,s.mfa_at,s.oidc_id,u.email,u.mfa_enabled FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.refresh_hash=$1 AND s.expires_at>now() AND u.active FOR UPDATE OF s
`

type SessionByRefreshRow struct {
	ID         string
	UserID     string
	MfaAt      pgtype.Timestamptz
	OidcID     pgtype.UUID
	Email      string
	MfaEnabled bool
}

func (q *Queries) SessionByRefresh(ctx context.Context, refreshHash []byte) (SessionByRefreshRow, error) {
	row := q.db.QueryRow(ctx, sessionByRefresh, refreshHash)
	var i SessionByRefreshRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MfaAt,
		&i.OidcID,
		&i.Email,
		&i.MfaEnabled,
	)
	return i, err
}

const setConnectionEnabled = `-- name: SetConnectionEnabled :one
UPDATE connections SET enabled=$3,revision=revision+1,scan_status='never',scan_error='',next_scan_at=now() WHERE org_id=$1 AND id=$2 AND deleted_at IS NULL RETURNING id,org_id,name,provider,region,enabled,created_at,scan_status,scan_error,last_scan_at,credential_source
`

type SetConnectionEnabledParams struct {
	OrgID   string
	ID      string
	Enabled bool
}

type SetConnectionEnabledRow struct {
	ID               string
	OrgID            string
	Name             string
	Provider         string
	Region           string
	Enabled          bool
	CreatedAt        pgtype.Timestamptz
	ScanStatus       string
	ScanError        string
	LastScanAt       pgtype.Timestamptz
	CredentialSource string
}

func (q *Queries) SetConnectionEnabled(ctx context.Context, arg SetConnectionEnabledParams) (SetConnectionEnabledRow, error) {
	row := q.db.QueryRow(ctx, setConnectionEnabled, arg.OrgID, arg.ID, arg.Enabled)
	var i SetConnectionEnabledRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Provider,
		&i.Region,
		&i.Enabled,
		&i.CreatedAt,
		&i.ScanStatus,
		&i.ScanError,
		&i.LastScanAt,
		&i.CredentialSource,
	)
	return i, err
}

const setPendingSetup = `-- name: SetPendingSetup :exec
INSERT INTO setup_pending(id,ciphertext,expires_at) VALUES(true,$1,now()+interval '10 minutes') ON CONFLICT(id) DO UPDATE SET ciphertext=excluded.ciphertext,expires_at=excluded.expires_at
`

func (q *Queries) SetPendingSetup(ctx context.Context, ciphertext []byte) error {
	_, err := q.db.Exec(ctx, setPendingSetup, ciphertext)
	return err
}

const userByEmail = `-- name: UserByEmail :one
SELECT id, email, password_hash, totp_ciphertext, last_totp_step, active, global_admin, mfa_enabled, admin_seeded_at, admin_revision FROM users WHERE email=$1 AND active=true
`

func (q *Queries) UserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, userByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.TotpCiphertext,
		&i.LastTotpStep,
		&i.Active,
		&i.GlobalAdmin,
		&i.MfaEnabled,
		&i.AdminSeededAt,
		&i.AdminRevision,
	)
	return i, err
}

const userCount = `-- name: UserCount :one
SELECT count(*) FROM users
`

func (q *Queries) UserCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, userCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}
