// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboards.sql

package database

import (
	"context"
)

const countDashboards = `-- name: CountDashboards :one
SELECT count(*) FROM dashboards WHERE org_id=$1 AND user_id=$2
`

type CountDashboardsParams struct {
	OrgID  string
	UserID string
}

func (q *Queries) CountDashboards(ctx context.Context, arg CountDashboardsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDashboards, arg.OrgID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSharedDashboards = `-- name: CountSharedDashboards :one
SELECT count(*) FROM dashboards WHERE org_id=$1 AND (shared OR cardinality(team_ids)>0)
`

func (q *Queries) CountSharedDashboards(ctx context.Context, orgID string) (int64, error) {
	row := q.db.QueryRow(ctx, countSharedDashboards, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDashboard = `-- name: CreateDashboard :one
INSERT INTO dashboards(id,org_id,user_id,name,spec,shared,team_ids) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id, org_id, user_id, name, spec, revision, updated_at, shared, team_ids
`

type CreateDashboardParams struct {
	ID      string
	OrgID   string
	UserID  string
	Name    string
	Spec    []byte
	Shared  bool
	TeamIds []string
}

func (q *Queries) CreateDashboard(ctx context.Context, arg CreateDashboardParams) (Dashboard, error) {
	row := q.db.QueryRow(ctx, createDashboard,
		arg.ID,
		arg.OrgID,
		arg.UserID,
		arg.Name,
		arg.Spec,
		arg.Shared,
		arg.TeamIds,
	)
	var i Dashboard
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Name,
		&i.Spec,
		&i.Revision,
		&i.UpdatedAt,
		&i.Shared,
		&i.TeamIds,
	)
	return i, err
}

const deleteDashboard = `-- name: DeleteDashboard :execrows
DELETE FROM dashboards WHERE id=$1 AND org_id=$2 AND (user_id=$3 OR ((shared OR cardinality(team_ids)>0) AND $5::boolean)) AND revision=$4
`

type DeleteDashboardParams struct {
	ID           string
	OrgID        string
	UserID       string
	Revision     int64
	ManageShared bool
}

func (q *Queries) DeleteDashboard(ctx context.Context, arg DeleteDashboardParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDashboard,
		arg.ID,
		arg.OrgID,
		arg.UserID,
		arg.Revision,
		arg.ManageShared,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOwnedOrSharedDashboard = `-- name: GetOwnedOrSharedDashboard :one
SELECT id, org_id, user_id, name, spec, revision, updated_at, shared, team_ids FROM dashboards WHERE org_id=$1 AND id=$2 AND (user_id=$3 OR shared OR cardinality(team_ids)>0)
`

type GetOwnedOrSharedDashboardParams struct {
	OrgID  string
	ID     string
	UserID string
}

func (q *Queries) GetOwnedOrSharedDashboard(ctx context.Context, arg GetOwnedOrSharedDashboardParams) (Dashboard, error) {
	row := q.db.QueryRow(ctx, getOwnedOrSharedDashboard, arg.OrgID, arg.ID, arg.UserID)
	var i Dashboard
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Name,
		&i.Spec,
		&i.Revision,
		&i.UpdatedAt,
		&i.Shared,
		&i.TeamIds,
	)
	return i, err
}

const listDashboardTeams = `-- name: ListDashboardTeams :many
SELECT id,name,active FROM teams WHERE org_id=$1 ORDER BY name,id LIMIT 101
`

type ListDashboardTeamsRow struct {
	ID     string
	Name   string
	Active bool
}

func (q *Queries) ListDashboardTeams(ctx context.Context, orgID string) ([]ListDashboardTeamsRow, error) {
	rows, err := q.db.Query(ctx, listDashboardTeams, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDashboardTeamsRow{}
	for rows.Next() {
		var i ListDashboardTeamsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Active); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDashboards = `-- name: ListDashboards :many
SELECT d.id, d.org_id, d.user_id, d.name, d.spec, d.revision, d.updated_at, d.shared, d.team_ids FROM dashboards d WHERE d.org_id=$1 AND (d.user_id=$2 OR d.shared OR (cardinality(d.team_ids)>0 AND (
 EXISTS(SELECT 1 FROM effective_memberships m WHERE m.org_id=d.org_id AND m.user_id=$2 AND 'dashboards.manage'=ANY(m.permissions))
 OR EXISTS(SELECT 1 FROM teams t JOIN team_members tm ON tm.org_id=t.org_id AND tm.team_id=t.id WHERE t.org_id=d.org_id AND t.id=ANY(d.team_ids) AND t.active AND tm.user_id=$2)
))) ORDER BY d.name,d.id LIMIT 100
`

type ListDashboardsParams struct {
	OrgID  string
	UserID string
}

func (q *Queries) ListDashboards(ctx context.Context, arg ListDashboardsParams) ([]Dashboard, error) {
	rows, err := q.db.Query(ctx, listDashboards, arg.OrgID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Dashboard{}
	for rows.Next() {
		var i Dashboard
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.Name,
			&i.Spec,
			&i.Revision,
			&i.UpdatedAt,
			&i.Shared,
			&i.TeamIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDashboard = `-- name: UpdateDashboard :one
UPDATE dashboards SET name=$4,spec=$5,revision=revision+1,updated_at=now(),shared=$7,team_ids=$8
WHERE id=$1 AND org_id=$2 AND (user_id=$3 OR ((shared OR cardinality(team_ids)>0) AND $9::boolean)) AND revision=$6 RETURNING id, org_id, user_id, name, spec, revision, updated_at, shared, team_ids
`

type UpdateDashboardParams struct {
	ID           string
	OrgID        string
	UserID       string
	Name         string
	Spec         []byte
	Revision     int64
	Shared       bool
	TeamIds      []string
	ManageShared bool
}

func (q *Queries) UpdateDashboard(ctx context.Context, arg UpdateDashboardParams) (Dashboard, error) {
	row := q.db.QueryRow(ctx, updateDashboard,
		arg.ID,
		arg.OrgID,
		arg.UserID,
		arg.Name,
		arg.Spec,
		arg.Revision,
		arg.Shared,
		arg.TeamIds,
		arg.ManageShared,
	)
	var i Dashboard
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Name,
		&i.Spec,
		&i.Revision,
		&i.UpdatedAt,
		&i.Shared,
		&i.TeamIds,
	)
	return i, err
}
