// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: discovery.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activeScan = `-- name: ActiveScan :one
SELECT id FROM scan_jobs WHERE org_id=$1 AND connection_id=$2 AND status IN ('queued','running')
`

type ActiveScanParams struct {
	OrgID        string
	ConnectionID string
}

func (q *Queries) ActiveScan(ctx context.Context, arg ActiveScanParams) (string, error) {
	row := q.db.QueryRow(ctx, activeScan, arg.OrgID, arg.ConnectionID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const claimScan = `-- name: ClaimScan :one
UPDATE scan_jobs SET status='running',lease_until=now()+interval '3 minutes' WHERE id=(SELECT id FROM scan_jobs WHERE status='queued' ORDER BY created_at,id FOR UPDATE SKIP LOCKED LIMIT 1) RETURNING id, org_id, connection_id, revision, requester_id, actor, status, created_at, lease_until, finished_at, error, module_revision, runtime_id, trace_parent
`

func (q *Queries) ClaimScan(ctx context.Context) (ScanJob, error) {
	row := q.db.QueryRow(ctx, claimScan)
	var i ScanJob
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ConnectionID,
		&i.Revision,
		&i.RequesterID,
		&i.Actor,
		&i.Status,
		&i.CreatedAt,
		&i.LeaseUntil,
		&i.FinishedAt,
		&i.Error,
		&i.ModuleRevision,
		&i.RuntimeID,
		&i.TraceParent,
	)
	return i, err
}

const connectionForScan = `-- name: ConnectionForScan :one
SELECT c.id, c.org_id, c.name, c.provider, c.region, c.enabled, c.key_id, c.algorithm, c.ciphertext, c.created_at, c.deleted_at, c.revision, c.scan_status, c.scan_error, c.last_scan_at, c.next_scan_at, c.credential_source FROM connections c JOIN organizations o ON o.id=c.org_id WHERE c.org_id=$1 AND c.id=$2 AND c.deleted_at IS NULL AND o.active FOR UPDATE OF c
`

type ConnectionForScanParams struct {
	OrgID string
	ID    string
}

func (q *Queries) ConnectionForScan(ctx context.Context, arg ConnectionForScanParams) (Connection, error) {
	row := q.db.QueryRow(ctx, connectionForScan, arg.OrgID, arg.ID)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Provider,
		&i.Region,
		&i.Enabled,
		&i.KeyID,
		&i.Algorithm,
		&i.Ciphertext,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.Revision,
		&i.ScanStatus,
		&i.ScanError,
		&i.LastScanAt,
		&i.NextScanAt,
		&i.CredentialSource,
	)
	return i, err
}

const dueConnections = `-- name: DueConnections :many
SELECT c.org_id,c.id FROM connections c JOIN organizations o ON o.id=c.org_id WHERE c.enabled AND c.deleted_at IS NULL AND o.active AND coalesce((SELECT enabled FROM provider_modules WHERE org_id=c.org_id AND provider=c.provider),true) AND c.next_scan_at<=now() AND NOT EXISTS(SELECT 1 FROM scan_jobs j WHERE j.org_id=c.org_id AND j.connection_id=c.id AND j.status IN ('queued','running')) ORDER BY c.next_scan_at LIMIT 20
`

type DueConnectionsRow struct {
	OrgID string
	ID    string
}

func (q *Queries) DueConnections(ctx context.Context) ([]DueConnectionsRow, error) {
	rows, err := q.db.Query(ctx, dueConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DueConnectionsRow{}
	for rows.Next() {
		var i DueConnectionsRow
		if err := rows.Scan(&i.OrgID, &i.ID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expireScan = `-- name: ExpireScan :execrows
UPDATE scan_jobs SET status='failed',error='worker_interrupted',finished_at=now() WHERE id=$1 AND status='running' AND lease_until<=now()
`

func (q *Queries) ExpireScan(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, expireScan, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expiredScans = `-- name: ExpiredScans :many
SELECT id,org_id,connection_id,revision FROM scan_jobs WHERE status='running' AND lease_until<=now() LIMIT 100
`

type ExpiredScansRow struct {
	ID           string
	OrgID        string
	ConnectionID string
	Revision     int64
}

func (q *Queries) ExpiredScans(ctx context.Context) ([]ExpiredScansRow, error) {
	rows, err := q.db.Query(ctx, expiredScans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpiredScansRow{}
	for rows.Next() {
		var i ExpiredScansRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ConnectionID,
			&i.Revision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishScanJob = `-- name: FinishScanJob :exec
UPDATE scan_jobs SET status=$2,error=$3,finished_at=now() WHERE id=$1 AND status='running'
`

type FinishScanJobParams struct {
	ID     string
	Status string
	Error  string
}

func (q *Queries) FinishScanJob(ctx context.Context, arg FinishScanJobParams) error {
	_, err := q.db.Exec(ctx, finishScanJob, arg.ID, arg.Status, arg.Error)
	return err
}

const getResource = `-- name: GetResource :one
SELECT r.id,r.connection_id,r.native_id,r.name,r.provider,r.kind,r.region,r.status,r.observed_at,r.public_ip,r.private_ip,r.size,r.provider_identity,r.tag_metadata,c.enabled AS connection_enabled,c.name AS connection_name FROM resources r JOIN connections c ON c.org_id=r.org_id AND c.id=r.connection_id WHERE r.org_id=$1 AND r.id=$2 AND r.deleted_at IS NULL AND c.deleted_at IS NULL
`

type GetResourceParams struct {
	OrgID string
	ID    string
}

type GetResourceRow struct {
	ID                string
	ConnectionID      string
	NativeID          string
	Name              string
	Provider          string
	Kind              string
	Region            string
	Status            string
	ObservedAt        pgtype.Timestamptz
	PublicIp          string
	PrivateIp         string
	Size              string
	ProviderIdentity  string
	TagMetadata       []byte
	ConnectionEnabled bool
	ConnectionName    string
}

func (q *Queries) GetResource(ctx context.Context, arg GetResourceParams) (GetResourceRow, error) {
	row := q.db.QueryRow(ctx, getResource, arg.OrgID, arg.ID)
	var i GetResourceRow
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.NativeID,
		&i.Name,
		&i.Provider,
		&i.Kind,
		&i.Region,
		&i.Status,
		&i.ObservedAt,
		&i.PublicIp,
		&i.PrivateIp,
		&i.Size,
		&i.ProviderIdentity,
		&i.TagMetadata,
		&i.ConnectionEnabled,
		&i.ConnectionName,
	)
	return i, err
}

const lockRunningScan = `-- name: LockRunningScan :one
SELECT id, org_id, connection_id, revision, requester_id, actor, status, created_at, lease_until, finished_at, error, module_revision, runtime_id, trace_parent FROM scan_jobs WHERE id=$1 AND status='running' AND lease_until>now() FOR UPDATE
`

func (q *Queries) LockRunningScan(ctx context.Context, id string) (ScanJob, error) {
	row := q.db.QueryRow(ctx, lockRunningScan, id)
	var i ScanJob
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ConnectionID,
		&i.Revision,
		&i.RequesterID,
		&i.Actor,
		&i.Status,
		&i.CreatedAt,
		&i.LeaseUntil,
		&i.FinishedAt,
		&i.Error,
		&i.ModuleRevision,
		&i.RuntimeID,
		&i.TraceParent,
	)
	return i, err
}

const markScanQueued = `-- name: MarkScanQueued :exec
UPDATE connections SET scan_status='queued',scan_error='' WHERE org_id=$1 AND id=$2 AND enabled AND deleted_at IS NULL
`

type MarkScanQueuedParams struct {
	OrgID string
	ID    string
}

func (q *Queries) MarkScanQueued(ctx context.Context, arg MarkScanQueuedParams) error {
	_, err := q.db.Exec(ctx, markScanQueued, arg.OrgID, arg.ID)
	return err
}

const markScanRunning = `-- name: MarkScanRunning :exec
UPDATE connections SET scan_status='running' WHERE org_id=$1 AND id=$2 AND revision=$3 AND enabled AND deleted_at IS NULL
`

type MarkScanRunningParams struct {
	OrgID    string
	ID       string
	Revision int64
}

func (q *Queries) MarkScanRunning(ctx context.Context, arg MarkScanRunningParams) error {
	_, err := q.db.Exec(ctx, markScanRunning, arg.OrgID, arg.ID, arg.Revision)
	return err
}

const queueScan = `-- name: QueueScan :one
INSERT INTO scan_jobs(id,org_id,connection_id,revision,requester_id,actor,module_revision,runtime_id,trace_parent)
SELECT $1,c.org_id,c.id,c.revision,$2,$3,$4,$5,$6 FROM connections c JOIN organizations o ON o.id=c.org_id WHERE c.org_id=$7 AND c.id=$8 AND c.enabled AND c.deleted_at IS NULL AND o.active
ON CONFLICT (org_id,connection_id) WHERE status IN ('queued','running') DO NOTHING RETURNING id
`

type QueueScanParams struct {
	ID             string
	RequesterID    string
	Actor          string
	ModuleRevision int64
	RuntimeID      string
	TraceParent    string
	OrgID          string
	ConnectionID   string
}

func (q *Queries) QueueScan(ctx context.Context, arg QueueScanParams) (string, error) {
	row := q.db.QueryRow(ctx, queueScan,
		arg.ID,
		arg.RequesterID,
		arg.Actor,
		arg.ModuleRevision,
		arg.RuntimeID,
		arg.TraceParent,
		arg.OrgID,
		arg.ConnectionID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const recordScanFailure = `-- name: RecordScanFailure :exec
UPDATE connections SET scan_status='failed',scan_error=$4,next_scan_at=now()+interval '5 minutes' WHERE org_id=$1 AND id=$2 AND revision=$3 AND deleted_at IS NULL
`

type RecordScanFailureParams struct {
	OrgID     string
	ID        string
	Revision  int64
	ScanError string
}

func (q *Queries) RecordScanFailure(ctx context.Context, arg RecordScanFailureParams) error {
	_, err := q.db.Exec(ctx, recordScanFailure,
		arg.OrgID,
		arg.ID,
		arg.Revision,
		arg.ScanError,
	)
	return err
}

const recordScanSuccess = `-- name: RecordScanSuccess :exec
UPDATE connections SET scan_status='succeeded',scan_error='',last_scan_at=now(),next_scan_at=now()+interval '5 minutes' WHERE org_id=$1 AND id=$2 AND revision=$3 AND enabled AND deleted_at IS NULL
`

type RecordScanSuccessParams struct {
	OrgID    string
	ID       string
	Revision int64
}

func (q *Queries) RecordScanSuccess(ctx context.Context, arg RecordScanSuccessParams) error {
	_, err := q.db.Exec(ctx, recordScanSuccess, arg.OrgID, arg.ID, arg.Revision)
	return err
}

const rescheduleOvertakenScan = `-- name: RescheduleOvertakenScan :exec
UPDATE connections SET scan_status='queued',scan_error='',next_scan_at=now() WHERE org_id=$1 AND id=$2
`

type RescheduleOvertakenScanParams struct {
	OrgID string
	ID    string
}

func (q *Queries) RescheduleOvertakenScan(ctx context.Context, arg RescheduleOvertakenScanParams) error {
	_, err := q.db.Exec(ctx, rescheduleOvertakenScan, arg.OrgID, arg.ID)
	return err
}

const retireMissingResources = `-- name: RetireMissingResources :exec
UPDATE resources SET deleted_at=now() WHERE org_id=$1 AND connection_id=$2 AND kind=ANY($3::text[]) AND deleted_at IS NULL AND NOT(id=ANY($4::text[]))
`

type RetireMissingResourcesParams struct {
	OrgID        string
	ConnectionID string
	CoveredKinds []string
	PresentIds   []string
}

func (q *Queries) RetireMissingResources(ctx context.Context, arg RetireMissingResourcesParams) error {
	_, err := q.db.Exec(ctx, retireMissingResources,
		arg.OrgID,
		arg.ConnectionID,
		arg.CoveredKinds,
		arg.PresentIds,
	)
	return err
}

const scanOvertakenByOperation = `-- name: ScanOvertakenByOperation :one
SELECT EXISTS(SELECT 1 FROM operations WHERE org_id=$1 AND connection_id=$2 AND updated_at>=$3 AND status IN ('dispatching','observing','uncertain','succeeded','failed','resolved'))
`

type ScanOvertakenByOperationParams struct {
	OrgID        string
	ConnectionID string
	ScanStarted  pgtype.Timestamptz
}

func (q *Queries) ScanOvertakenByOperation(ctx context.Context, arg ScanOvertakenByOperationParams) (bool, error) {
	row := q.db.QueryRow(ctx, scanOvertakenByOperation, arg.OrgID, arg.ConnectionID, arg.ScanStarted)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const upsertResource = `-- name: UpsertResource :exec
INSERT INTO resources(id,org_id,connection_id,native_id,name,provider,kind,region,status,public_ip,private_ip,size,observed_at,provider_identity,tag_metadata)
VALUES($1,$2,$3,$4,$5,$6,$12,$7,$8,$9,$10,$11,now(),$13,$14)
ON CONFLICT(org_id,connection_id,kind,region,native_id) DO UPDATE SET tag_metadata=excluded.tag_metadata,name=excluded.name,status=excluded.status,public_ip=excluded.public_ip,private_ip=excluded.private_ip,size=excluded.size,provider_identity=excluded.provider_identity,observed_at=now(),deleted_at=NULL
`

type UpsertResourceParams struct {
	ID               string
	OrgID            string
	ConnectionID     string
	NativeID         string
	Name             string
	Provider         string
	Region           string
	Status           string
	PublicIp         string
	PrivateIp        string
	Size             string
	Kind             string
	ProviderIdentity string
	TagMetadata      []byte
}

func (q *Queries) UpsertResource(ctx context.Context, arg UpsertResourceParams) error {
	_, err := q.db.Exec(ctx, upsertResource,
		arg.ID,
		arg.OrgID,
		arg.ConnectionID,
		arg.NativeID,
		arg.Name,
		arg.Provider,
		arg.Region,
		arg.Status,
		arg.PublicIp,
		arg.PrivateIp,
		arg.Size,
		arg.Kind,
		arg.ProviderIdentity,
		arg.TagMetadata,
	)
	return err
}
