// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: identity_policy.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEligibleRecoveryUsers = `-- name: CountEligibleRecoveryUsers :one
SELECT count(*) FROM memberships m JOIN users u ON u.id=m.user_id WHERE m.org_id=$1 AND m.user_id=ANY($2::text[]) AND m.active AND u.active AND m.role_id='administrator'
`

type CountEligibleRecoveryUsersParams struct {
	OrgID string
	Users []string
}

func (q *Queries) CountEligibleRecoveryUsers(ctx context.Context, arg CountEligibleRecoveryUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEligibleRecoveryUsers, arg.OrgID, arg.Users)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getIdentityPolicy = `-- name: GetIdentityPolicy :one
SELECT o.id AS org_id,coalesce(p.enabled,false)::boolean AS enabled,coalesce(p.issuer,'')::text AS issuer,coalesce(p.recovery_users,'{}')::text[] AS recovery_users,coalesce(p.revision,0)::bigint AS revision FROM organizations o LEFT JOIN identity_policies p ON p.org_id=o.id WHERE o.id=$1
`

type GetIdentityPolicyRow struct {
	OrgID         string
	Enabled       bool
	Issuer        string
	RecoveryUsers []string
	Revision      int64
}

func (q *Queries) GetIdentityPolicy(ctx context.Context, id string) (GetIdentityPolicyRow, error) {
	row := q.db.QueryRow(ctx, getIdentityPolicy, id)
	var i GetIdentityPolicyRow
	err := row.Scan(
		&i.OrgID,
		&i.Enabled,
		&i.Issuer,
		&i.RecoveryUsers,
		&i.Revision,
	)
	return i, err
}

const identityAllows = `-- name: IdentityAllows :one
SELECT identity_allows($1::text,$2::text,$3::uuid)::boolean
`

type IdentityAllowsParams struct {
	OrgID  string
	UserID string
	OidcID pgtype.UUID
}

func (q *Queries) IdentityAllows(ctx context.Context, arg IdentityAllowsParams) (bool, error) {
	row := q.db.QueryRow(ctx, identityAllows, arg.OrgID, arg.UserID, arg.OidcID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const identityRecoveryMissing = `-- name: IdentityRecoveryMissing :one
SELECT EXISTS(SELECT 1 FROM identity_policies p WHERE p.org_id=$1 AND p.enabled AND NOT EXISTS(SELECT 1 FROM memberships m JOIN users u ON u.id=m.user_id WHERE m.org_id=p.org_id AND m.user_id=ANY(p.recovery_users) AND m.active AND u.active AND m.role_id='administrator'))
`

func (q *Queries) IdentityRecoveryMissing(ctx context.Context, orgID string) (bool, error) {
	row := q.db.QueryRow(ctx, identityRecoveryMissing, orgID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const organizationsForSession = `-- name: OrganizationsForSession :many
SELECT o.id,o.name,m.permissions,mfa_required(o.id)::boolean AS mfa_required,identity_allows(o.id,m.user_id,$1::uuid)::boolean AS allowed FROM organizations o JOIN effective_memberships m ON m.org_id=o.id WHERE m.user_id=$2 ORDER BY o.name,o.id
`

type OrganizationsForSessionParams struct {
	OidcID pgtype.UUID
	UserID string
}

type OrganizationsForSessionRow struct {
	ID          string
	Name        string
	Permissions []string
	MfaRequired bool
	Allowed     bool
}

func (q *Queries) OrganizationsForSession(ctx context.Context, arg OrganizationsForSessionParams) ([]OrganizationsForSessionRow, error) {
	rows, err := q.db.Query(ctx, organizationsForSession, arg.OidcID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationsForSessionRow{}
	for rows.Next() {
		var i OrganizationsForSessionRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Permissions,
			&i.MfaRequired,
			&i.Allowed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveIdentityPolicy = `-- name: SaveIdentityPolicy :exec
INSERT INTO identity_policies(org_id,enabled,issuer,recovery_users) VALUES($1,$2,$3,$4) ON CONFLICT(org_id) DO UPDATE SET enabled=excluded.enabled,issuer=excluded.issuer,recovery_users=excluded.recovery_users,revision=identity_policies.revision+1
`

type SaveIdentityPolicyParams struct {
	OrgID         string
	Enabled       bool
	Issuer        string
	RecoveryUsers []string
}

func (q *Queries) SaveIdentityPolicy(ctx context.Context, arg SaveIdentityPolicyParams) error {
	_, err := q.db.Exec(ctx, saveIdentityPolicy,
		arg.OrgID,
		arg.Enabled,
		arg.Issuer,
		arg.RecoveryUsers,
	)
	return err
}

const setSessionIdentity = `-- name: SetSessionIdentity :exec
UPDATE sessions SET oidc_id=$2 WHERE id=$1
`

type SetSessionIdentityParams struct {
	ID     string
	OidcID pgtype.UUID
}

func (q *Queries) SetSessionIdentity(ctx context.Context, arg SetSessionIdentityParams) error {
	_, err := q.db.Exec(ctx, setSessionIdentity, arg.ID, arg.OidcID)
	return err
}

const stampOperationIdentity = `-- name: StampOperationIdentity :exec
UPDATE operations SET requester_oidc_id=$3,approver_oidc_id=$4 WHERE org_id=$1 AND id=$2
`

type StampOperationIdentityParams struct {
	OrgID           string
	ID              string
	RequesterOidcID pgtype.UUID
	ApproverOidcID  pgtype.UUID
}

func (q *Queries) StampOperationIdentity(ctx context.Context, arg StampOperationIdentityParams) error {
	_, err := q.db.Exec(ctx, stampOperationIdentity,
		arg.OrgID,
		arg.ID,
		arg.RequesterOidcID,
		arg.ApproverOidcID,
	)
	return err
}

const stampScheduleIdentity = `-- name: StampScheduleIdentity :exec
UPDATE schedules SET editor_oidc_id=$3,approver_oidc_id=NULL WHERE org_id=$1 AND id=$2
`

type StampScheduleIdentityParams struct {
	OrgID        string
	ID           string
	EditorOidcID pgtype.UUID
}

func (q *Queries) StampScheduleIdentity(ctx context.Context, arg StampScheduleIdentityParams) error {
	_, err := q.db.Exec(ctx, stampScheduleIdentity, arg.OrgID, arg.ID, arg.EditorOidcID)
	return err
}
