// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: installation_directory.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addInstallationPolicyEvent = `-- name: AddInstallationPolicyEvent :exec
INSERT INTO installation_events(actor_id,target_id,action,details)
VALUES($1,NULL,$2,jsonb_build_object('required',$3::boolean,'revision',$4::bigint))
`

type AddInstallationPolicyEventParams struct {
	ActorID  pgtype.Text
	Action   string
	Required bool
	Revision int64
}

func (q *Queries) AddInstallationPolicyEvent(ctx context.Context, arg AddInstallationPolicyEventParams) error {
	_, err := q.db.Exec(ctx, addInstallationPolicyEvent,
		arg.ActorID,
		arg.Action,
		arg.Required,
		arg.Revision,
	)
	return err
}

const addInstallationUserEvent = `-- name: AddInstallationUserEvent :exec
INSERT INTO installation_events(actor_id,target_id,action,details)
VALUES($1,$2,'user.access_changed',jsonb_build_object('active',$3::boolean,'global_admin',$4::boolean))
`

type AddInstallationUserEventParams struct {
	ActorID     pgtype.Text
	TargetID    pgtype.Text
	Active      bool
	GlobalAdmin bool
}

func (q *Queries) AddInstallationUserEvent(ctx context.Context, arg AddInstallationUserEventParams) error {
	_, err := q.db.Exec(ctx, addInstallationUserEvent,
		arg.ActorID,
		arg.TargetID,
		arg.Active,
		arg.GlobalAdmin,
	)
	return err
}

const installationOrganizations = `-- name: InstallationOrganizations :many
SELECT id,name,active,admin_revision FROM organizations
WHERE id>$1 AND ($2::text='' OR strpos(lower(name),lower($2))>0)
AND ($3::text='' OR active=($3='active')) ORDER BY id LIMIT 101
`

type InstallationOrganizationsParams struct {
	AfterID string
	Search  string
	State   string
}

type InstallationOrganizationsRow struct {
	ID            string
	Name          string
	Active        bool
	AdminRevision int64
}

func (q *Queries) InstallationOrganizations(ctx context.Context, arg InstallationOrganizationsParams) ([]InstallationOrganizationsRow, error) {
	rows, err := q.db.Query(ctx, installationOrganizations, arg.AfterID, arg.Search, arg.State)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InstallationOrganizationsRow{}
	for rows.Next() {
		var i InstallationOrganizationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Active,
			&i.AdminRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const installationUsers = `-- name: InstallationUsers :many
SELECT id,email,active,global_admin,mfa_enabled,admin_revision FROM users
WHERE id>$1 AND ($2::text='' OR strpos(lower(email),lower($2))>0)
AND ($3::text='' OR active=($3='active')) ORDER BY id LIMIT 101
`

type InstallationUsersParams struct {
	AfterID string
	Search  string
	State   string
}

type InstallationUsersRow struct {
	ID            string
	Email         string
	Active        bool
	GlobalAdmin   bool
	MfaEnabled    bool
	AdminRevision int64
}

func (q *Queries) InstallationUsers(ctx context.Context, arg InstallationUsersParams) ([]InstallationUsersRow, error) {
	rows, err := q.db.Query(ctx, installationUsers, arg.AfterID, arg.Search, arg.State)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InstallationUsersRow{}
	for rows.Next() {
		var i InstallationUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Active,
			&i.GlobalAdmin,
			&i.MfaEnabled,
			&i.AdminRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGlobalOrganizationAudit = `-- name: ListGlobalOrganizationAudit :many
SELECT e.id,e.org_id,o.name AS organization_name,e.actor,e.action,e.target,e.details,e.occurred_at
FROM audit_events e JOIN organizations o ON o.id=e.org_id
WHERE e.id<$1
AND ($2::text='' OR e.actor=$2)
AND ($3::text='' OR e.action=$3)
AND ($4::text='' OR e.target=$4)
AND ($5::timestamptz IS NULL OR e.occurred_at>=$5)
AND ($6::timestamptz IS NULL OR e.occurred_at<$6)
AND ($7::text='' OR e.org_id=$7)
ORDER BY e.id DESC LIMIT 101
`

type ListGlobalOrganizationAuditParams struct {
	BeforeID       int64
	Actor          string
	Action         string
	Target         string
	OccurredFrom   pgtype.Timestamptz
	OccurredBefore pgtype.Timestamptz
	OrgID          string
}

type ListGlobalOrganizationAuditRow struct {
	ID               int64
	OrgID            string
	OrganizationName string
	Actor            string
	Action           string
	Target           string
	Details          []byte
	OccurredAt       pgtype.Timestamptz
}

func (q *Queries) ListGlobalOrganizationAudit(ctx context.Context, arg ListGlobalOrganizationAuditParams) ([]ListGlobalOrganizationAuditRow, error) {
	rows, err := q.db.Query(ctx, listGlobalOrganizationAudit,
		arg.BeforeID,
		arg.Actor,
		arg.Action,
		arg.Target,
		arg.OccurredFrom,
		arg.OccurredBefore,
		arg.OrgID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGlobalOrganizationAuditRow{}
	for rows.Next() {
		var i ListGlobalOrganizationAuditRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.OrganizationName,
			&i.Actor,
			&i.Action,
			&i.Target,
			&i.Details,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstallationAudit = `-- name: ListInstallationAudit :many
SELECT e.id,''::text AS org_id,''::text AS organization_name,e.actor_email AS actor,e.action,coalesce(e.target_id,'')::text AS target,e.details,e.occurred_at
FROM installation_events e
WHERE e.id<$1
AND ($2::text='' OR e.actor_email=$2)
AND ($3::text='' OR e.action=$3)
AND ($4::text='' OR e.target_id=$4)
AND ($5::timestamptz IS NULL OR e.occurred_at>=$5)
AND ($6::timestamptz IS NULL OR e.occurred_at<$6)

ORDER BY e.id DESC LIMIT 101
`

type ListInstallationAuditParams struct {
	BeforeID       int64
	Actor          string
	Action         string
	Target         string
	OccurredFrom   pgtype.Timestamptz
	OccurredBefore pgtype.Timestamptz
}

type ListInstallationAuditRow struct {
	ID               int64
	OrgID            string
	OrganizationName string
	Actor            string
	Action           string
	Target           string
	Details          []byte
	OccurredAt       pgtype.Timestamptz
}

func (q *Queries) ListInstallationAudit(ctx context.Context, arg ListInstallationAuditParams) ([]ListInstallationAuditRow, error) {
	rows, err := q.db.Query(ctx, listInstallationAudit,
		arg.BeforeID,
		arg.Actor,
		arg.Action,
		arg.Target,
		arg.OccurredFrom,
		arg.OccurredBefore,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInstallationAuditRow{}
	for rows.Next() {
		var i ListInstallationAuditRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.OrganizationName,
			&i.Actor,
			&i.Action,
			&i.Target,
			&i.Details,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInstallationOrganization = `-- name: UpdateInstallationOrganization :execrows
UPDATE organizations SET active=$1,admin_revision=admin_revision+1
WHERE id=$2 AND admin_revision=$3
`

type UpdateInstallationOrganizationParams struct {
	Active           bool
	ID               string
	ExpectedRevision int64
}

func (q *Queries) UpdateInstallationOrganization(ctx context.Context, arg UpdateInstallationOrganizationParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateInstallationOrganization, arg.Active, arg.ID, arg.ExpectedRevision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateInstallationUser = `-- name: UpdateInstallationUser :execrows
UPDATE users SET active=$1,global_admin=$2,admin_revision=admin_revision+1
WHERE id=$3 AND admin_revision=$4
`

type UpdateInstallationUserParams struct {
	Active           bool
	GlobalAdmin      bool
	ID               string
	ExpectedRevision int64
}

func (q *Queries) UpdateInstallationUser(ctx context.Context, arg UpdateInstallationUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateInstallationUser,
		arg.Active,
		arg.GlobalAdmin,
		arg.ID,
		arg.ExpectedRevision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
