// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory_views.sql

package database

import (
	"context"
)

const countInventoryViews = `-- name: CountInventoryViews :one
SELECT count(*) FROM inventory_views WHERE org_id=$1 AND user_id=$2
`

type CountInventoryViewsParams struct {
	OrgID  string
	UserID string
}

func (q *Queries) CountInventoryViews(ctx context.Context, arg CountInventoryViewsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countInventoryViews, arg.OrgID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInventoryView = `-- name: CreateInventoryView :one
INSERT INTO inventory_views(id,org_id,user_id,name,spec) VALUES($1,$2,$3,$4,$5) RETURNING id, org_id, user_id, name, spec, revision, updated_at
`

type CreateInventoryViewParams struct {
	ID     string
	OrgID  string
	UserID string
	Name   string
	Spec   []byte
}

func (q *Queries) CreateInventoryView(ctx context.Context, arg CreateInventoryViewParams) (InventoryView, error) {
	row := q.db.QueryRow(ctx, createInventoryView,
		arg.ID,
		arg.OrgID,
		arg.UserID,
		arg.Name,
		arg.Spec,
	)
	var i InventoryView
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Name,
		&i.Spec,
		&i.Revision,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteInventoryView = `-- name: DeleteInventoryView :execrows
DELETE FROM inventory_views WHERE id=$1 AND org_id=$2 AND user_id=$3 AND revision=$4
`

type DeleteInventoryViewParams struct {
	ID       string
	OrgID    string
	UserID   string
	Revision int64
}

func (q *Queries) DeleteInventoryView(ctx context.Context, arg DeleteInventoryViewParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInventoryView,
		arg.ID,
		arg.OrgID,
		arg.UserID,
		arg.Revision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listInventoryViews = `-- name: ListInventoryViews :many
SELECT id, org_id, user_id, name, spec, revision, updated_at FROM inventory_views WHERE org_id=$1 AND user_id=$2 ORDER BY name,id LIMIT 50
`

type ListInventoryViewsParams struct {
	OrgID  string
	UserID string
}

func (q *Queries) ListInventoryViews(ctx context.Context, arg ListInventoryViewsParams) ([]InventoryView, error) {
	rows, err := q.db.Query(ctx, listInventoryViews, arg.OrgID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryView{}
	for rows.Next() {
		var i InventoryView
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.Name,
			&i.Spec,
			&i.Revision,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInventoryView = `-- name: UpdateInventoryView :one
UPDATE inventory_views SET name=$4,spec=$5,revision=revision+1,updated_at=now()
WHERE id=$1 AND org_id=$2 AND user_id=$3 AND revision=$6 RETURNING id, org_id, user_id, name, spec, revision, updated_at
`

type UpdateInventoryViewParams struct {
	ID       string
	OrgID    string
	UserID   string
	Name     string
	Spec     []byte
	Revision int64
}

func (q *Queries) UpdateInventoryView(ctx context.Context, arg UpdateInventoryViewParams) (InventoryView, error) {
	row := q.db.QueryRow(ctx, updateInventoryView,
		arg.ID,
		arg.OrgID,
		arg.UserID,
		arg.Name,
		arg.Spec,
		arg.Revision,
	)
	var i InventoryView
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Name,
		&i.Spec,
		&i.Revision,
		&i.UpdatedAt,
	)
	return i, err
}
