// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: maintenance.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMaintenanceConnection = `-- name: AddMaintenanceConnection :exec
INSERT INTO maintenance_connections(org_id,policy_id,connection_id) VALUES($1,$2,$3)
`

type AddMaintenanceConnectionParams struct {
	OrgID        string
	PolicyID     string
	ConnectionID string
}

func (q *Queries) AddMaintenanceConnection(ctx context.Context, arg AddMaintenanceConnectionParams) error {
	_, err := q.db.Exec(ctx, addMaintenanceConnection, arg.OrgID, arg.PolicyID, arg.ConnectionID)
	return err
}

const bumpMaintenanceRevision = `-- name: BumpMaintenanceRevision :exec
UPDATE organizations SET maintenance_revision=maintenance_revision+1 WHERE id=$1
`

func (q *Queries) BumpMaintenanceRevision(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, bumpMaintenanceRevision, id)
	return err
}

const clearMaintenanceConnections = `-- name: ClearMaintenanceConnections :exec
DELETE FROM maintenance_connections WHERE org_id=$1 AND policy_id=$2
`

type ClearMaintenanceConnectionsParams struct {
	OrgID    string
	PolicyID string
}

func (q *Queries) ClearMaintenanceConnections(ctx context.Context, arg ClearMaintenanceConnectionsParams) error {
	_, err := q.db.Exec(ctx, clearMaintenanceConnections, arg.OrgID, arg.PolicyID)
	return err
}

const createMaintenancePolicy = `-- name: CreateMaintenancePolicy :exec
INSERT INTO maintenance_policies(id,org_id,name,spec,duration_minutes) VALUES($1,$2,$3,$4,$5)
`

type CreateMaintenancePolicyParams struct {
	ID              string
	OrgID           string
	Name            string
	Spec            []byte
	DurationMinutes int32
}

func (q *Queries) CreateMaintenancePolicy(ctx context.Context, arg CreateMaintenancePolicyParams) error {
	_, err := q.db.Exec(ctx, createMaintenancePolicy,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Spec,
		arg.DurationMinutes,
	)
	return err
}

const deleteMaintenancePolicy = `-- name: DeleteMaintenancePolicy :execrows
DELETE FROM maintenance_policies WHERE org_id=$1 AND id=$2 AND name=$3
`

type DeleteMaintenancePolicyParams struct {
	OrgID string
	ID    string
	Name  string
}

func (q *Queries) DeleteMaintenancePolicy(ctx context.Context, arg DeleteMaintenancePolicyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMaintenancePolicy, arg.OrgID, arg.ID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMaintenanceRevision = `-- name: GetMaintenanceRevision :one
SELECT maintenance_revision FROM organizations WHERE id=$1
`

func (q *Queries) GetMaintenanceRevision(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRow(ctx, getMaintenanceRevision, id)
	var maintenance_revision int64
	err := row.Scan(&maintenance_revision)
	return maintenance_revision, err
}

const listMaintenancePolicies = `-- name: ListMaintenancePolicies :many
SELECT p.id, p.org_id, p.name, p.spec, p.duration_minutes, p.created_at,ARRAY(SELECT c.connection_id FROM maintenance_connections c WHERE c.policy_id=p.id ORDER BY c.connection_id)::text[] AS connection_ids FROM maintenance_policies p WHERE p.org_id=$1 ORDER BY p.created_at,p.id
`

type ListMaintenancePoliciesRow struct {
	ID              string
	OrgID           string
	Name            string
	Spec            []byte
	DurationMinutes int32
	CreatedAt       pgtype.Timestamptz
	ConnectionIds   []string
}

func (q *Queries) ListMaintenancePolicies(ctx context.Context, orgID string) ([]ListMaintenancePoliciesRow, error) {
	rows, err := q.db.Query(ctx, listMaintenancePolicies, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMaintenancePoliciesRow{}
	for rows.Next() {
		var i ListMaintenancePoliciesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Spec,
			&i.DurationMinutes,
			&i.CreatedAt,
			&i.ConnectionIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMaintenancePolicy = `-- name: UpdateMaintenancePolicy :execrows
UPDATE maintenance_policies SET name=$3,spec=$4,duration_minutes=$5 WHERE org_id=$1 AND id=$2
`

type UpdateMaintenancePolicyParams struct {
	OrgID           string
	ID              string
	Name            string
	Spec            []byte
	DurationMinutes int32
}

func (q *Queries) UpdateMaintenancePolicy(ctx context.Context, arg UpdateMaintenancePolicyParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateMaintenancePolicy,
		arg.OrgID,
		arg.ID,
		arg.Name,
		arg.Spec,
		arg.DurationMinutes,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
