// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: managed_state.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceAutomationState = `-- name: AdvanceAutomationState :exec
UPDATE automation_projects SET state_id=$3,lineage=$4,serial=$5,sha256=$6,state_bytes=$7 WHERE org_id=$1 AND id=$2
`

type AdvanceAutomationStateParams struct {
	OrgID      string
	ID         string
	StateID    string
	Lineage    string
	Serial     int64
	Sha256     string
	StateBytes int32
}

func (q *Queries) AdvanceAutomationState(ctx context.Context, arg AdvanceAutomationStateParams) error {
	_, err := q.db.Exec(ctx, advanceAutomationState,
		arg.OrgID,
		arg.ID,
		arg.StateID,
		arg.Lineage,
		arg.Serial,
		arg.Sha256,
		arg.StateBytes,
	)
	return err
}

const automationStateSession = `-- name: AutomationStateSession :one
SELECT id, org_id, project_id, requester_id, requester_oidc_id, secret_hash, writable, expires_at, revoked FROM automation_state_sessions WHERE id=$1 AND project_id=$2 AND expires_at>now() AND NOT revoked
`

type AutomationStateSessionParams struct {
	ID        string
	ProjectID string
}

func (q *Queries) AutomationStateSession(ctx context.Context, arg AutomationStateSessionParams) (AutomationStateSession, error) {
	row := q.db.QueryRow(ctx, automationStateSession, arg.ID, arg.ProjectID)
	var i AutomationStateSession
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.RequesterID,
		&i.RequesterOidcID,
		&i.SecretHash,
		&i.Writable,
		&i.ExpiresAt,
		&i.Revoked,
	)
	return i, err
}

const createAutomationProject = `-- name: CreateAutomationProject :one
INSERT INTO automation_projects(id,org_id,name,version_id,inputs_ciphertext,inputs_hash) VALUES($1,$2,$3,$4,$5,$6) RETURNING id, org_id, name, version_id, state_id, lineage, serial, sha256, state_bytes, lock_id, lock_session_id, created_at, inputs_ciphertext, inputs_hash
`

type CreateAutomationProjectParams struct {
	ID               string
	OrgID            string
	Name             string
	VersionID        string
	InputsCiphertext []byte
	InputsHash       string
}

func (q *Queries) CreateAutomationProject(ctx context.Context, arg CreateAutomationProjectParams) (AutomationProject, error) {
	row := q.db.QueryRow(ctx, createAutomationProject,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.VersionID,
		arg.InputsCiphertext,
		arg.InputsHash,
	)
	var i AutomationProject
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.VersionID,
		&i.StateID,
		&i.Lineage,
		&i.Serial,
		&i.Sha256,
		&i.StateBytes,
		&i.LockID,
		&i.LockSessionID,
		&i.CreatedAt,
		&i.InputsCiphertext,
		&i.InputsHash,
	)
	return i, err
}

const createAutomationStateSession = `-- name: CreateAutomationStateSession :exec
INSERT INTO automation_state_sessions(id,org_id,project_id,requester_id,requester_oidc_id,secret_hash,writable,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,now()+interval '15 minutes')
`

type CreateAutomationStateSessionParams struct {
	ID              string
	OrgID           string
	ProjectID       string
	RequesterID     string
	RequesterOidcID pgtype.UUID
	SecretHash      []byte
	Writable        bool
}

func (q *Queries) CreateAutomationStateSession(ctx context.Context, arg CreateAutomationStateSessionParams) error {
	_, err := q.db.Exec(ctx, createAutomationStateSession,
		arg.ID,
		arg.OrgID,
		arg.ProjectID,
		arg.RequesterID,
		arg.RequesterOidcID,
		arg.SecretHash,
		arg.Writable,
	)
	return err
}

const currentAutomationState = `-- name: CurrentAutomationState :one
SELECT s.id, s.org_id, s.project_id, s.lineage, s.serial, s.sha256, s.state_bytes, s.ciphertext, s.created_at, s.storage FROM automation_states s JOIN automation_projects p ON p.state_id=s.id AND p.org_id=s.org_id AND p.id=s.project_id WHERE p.org_id=$1 AND p.id=$2
`

type CurrentAutomationStateParams struct {
	OrgID string
	ID    string
}

func (q *Queries) CurrentAutomationState(ctx context.Context, arg CurrentAutomationStateParams) (AutomationState, error) {
	row := q.db.QueryRow(ctx, currentAutomationState, arg.OrgID, arg.ID)
	var i AutomationState
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Lineage,
		&i.Serial,
		&i.Sha256,
		&i.StateBytes,
		&i.Ciphertext,
		&i.CreatedAt,
		&i.Storage,
	)
	return i, err
}

const getAutomationProject = `-- name: GetAutomationProject :one
SELECT id, org_id, name, version_id, state_id, lineage, serial, sha256, state_bytes, lock_id, lock_session_id, created_at, inputs_ciphertext, inputs_hash FROM automation_projects WHERE org_id=$1 AND id=$2
`

type GetAutomationProjectParams struct {
	OrgID string
	ID    string
}

func (q *Queries) GetAutomationProject(ctx context.Context, arg GetAutomationProjectParams) (AutomationProject, error) {
	row := q.db.QueryRow(ctx, getAutomationProject, arg.OrgID, arg.ID)
	var i AutomationProject
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.VersionID,
		&i.StateID,
		&i.Lineage,
		&i.Serial,
		&i.Sha256,
		&i.StateBytes,
		&i.LockID,
		&i.LockSessionID,
		&i.CreatedAt,
		&i.InputsCiphertext,
		&i.InputsHash,
	)
	return i, err
}

const insertAutomationState = `-- name: InsertAutomationState :exec
INSERT INTO automation_states(id,org_id,project_id,lineage,serial,sha256,state_bytes,ciphertext,storage) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)
`

type InsertAutomationStateParams struct {
	ID         string
	OrgID      string
	ProjectID  string
	Lineage    string
	Serial     int64
	Sha256     string
	StateBytes int32
	Ciphertext []byte
	Storage    string
}

func (q *Queries) InsertAutomationState(ctx context.Context, arg InsertAutomationStateParams) error {
	_, err := q.db.Exec(ctx, insertAutomationState,
		arg.ID,
		arg.OrgID,
		arg.ProjectID,
		arg.Lineage,
		arg.Serial,
		arg.Sha256,
		arg.StateBytes,
		arg.Ciphertext,
		arg.Storage,
	)
	return err
}

const invalidAutomationStatePointer = `-- name: InvalidAutomationStatePointer :one
SELECT EXISTS(SELECT 1 FROM automation_projects p LEFT JOIN automation_states s ON s.id=p.state_id AND s.org_id=p.org_id AND s.project_id=p.id WHERE (p.state_id='' AND EXISTS(SELECT 1 FROM automation_states history WHERE history.project_id=p.id)) OR (p.state_id<>'' AND (s.id IS NULL OR s.serial<>p.serial OR s.lineage<>p.lineage OR s.sha256<>p.sha256 OR s.state_bytes<>p.state_bytes OR EXISTS(SELECT 1 FROM automation_states newer WHERE newer.project_id=p.id AND newer.serial>p.serial))))::boolean
`

func (q *Queries) InvalidAutomationStatePointer(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, invalidAutomationStatePointer)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listAutomationProjects = `-- name: ListAutomationProjects :many
SELECT id, org_id, name, version_id, state_id, lineage, serial, sha256, state_bytes, lock_id, lock_session_id, created_at, inputs_ciphertext, inputs_hash FROM automation_projects WHERE org_id=$1 ORDER BY name,id LIMIT 201
`

func (q *Queries) ListAutomationProjects(ctx context.Context, orgID string) ([]AutomationProject, error) {
	rows, err := q.db.Query(ctx, listAutomationProjects, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AutomationProject{}
	for rows.Next() {
		var i AutomationProject
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.VersionID,
			&i.StateID,
			&i.Lineage,
			&i.Serial,
			&i.Sha256,
			&i.StateBytes,
			&i.LockID,
			&i.LockSessionID,
			&i.CreatedAt,
			&i.InputsCiphertext,
			&i.InputsHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAutomationStates = `-- name: ListAutomationStates :many
SELECT id,lineage,serial,sha256,state_bytes,created_at FROM automation_states WHERE org_id=$1 AND project_id=$2 AND ($3::bigint<0 OR serial<$3::bigint) ORDER BY serial DESC LIMIT 101
`

type ListAutomationStatesParams struct {
	OrgID        string
	ProjectID    string
	BeforeSerial int64
}

type ListAutomationStatesRow struct {
	ID         string
	Lineage    string
	Serial     int64
	Sha256     string
	StateBytes int32
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) ListAutomationStates(ctx context.Context, arg ListAutomationStatesParams) ([]ListAutomationStatesRow, error) {
	rows, err := q.db.Query(ctx, listAutomationStates, arg.OrgID, arg.ProjectID, arg.BeforeSerial)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAutomationStatesRow{}
	for rows.Next() {
		var i ListAutomationStatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Lineage,
			&i.Serial,
			&i.Sha256,
			&i.StateBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAutomationProject = `-- name: LockAutomationProject :one
SELECT id, org_id, name, version_id, state_id, lineage, serial, sha256, state_bytes, lock_id, lock_session_id, created_at, inputs_ciphertext, inputs_hash FROM automation_projects WHERE org_id=$1 AND id=$2 FOR UPDATE
`

type LockAutomationProjectParams struct {
	OrgID string
	ID    string
}

func (q *Queries) LockAutomationProject(ctx context.Context, arg LockAutomationProjectParams) (AutomationProject, error) {
	row := q.db.QueryRow(ctx, lockAutomationProject, arg.OrgID, arg.ID)
	var i AutomationProject
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.VersionID,
		&i.StateID,
		&i.Lineage,
		&i.Serial,
		&i.Sha256,
		&i.StateBytes,
		&i.LockID,
		&i.LockSessionID,
		&i.CreatedAt,
		&i.InputsCiphertext,
		&i.InputsHash,
	)
	return i, err
}

const setAutomationStateLock = `-- name: SetAutomationStateLock :exec
UPDATE automation_projects SET lock_id=$3,lock_session_id=$4 WHERE org_id=$1 AND id=$2
`

type SetAutomationStateLockParams struct {
	OrgID         string
	ID            string
	LockID        string
	LockSessionID string
}

func (q *Queries) SetAutomationStateLock(ctx context.Context, arg SetAutomationStateLockParams) error {
	_, err := q.db.Exec(ctx, setAutomationStateLock,
		arg.OrgID,
		arg.ID,
		arg.LockID,
		arg.LockSessionID,
	)
	return err
}

const verifyAutomationState = `-- name: VerifyAutomationState :one
SELECT id, org_id, project_id, lineage, serial, sha256, state_bytes, ciphertext, created_at, storage FROM automation_states WHERE id>$1 ORDER BY id LIMIT 1
`

func (q *Queries) VerifyAutomationState(ctx context.Context, id string) (AutomationState, error) {
	row := q.db.QueryRow(ctx, verifyAutomationState, id)
	var i AutomationState
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Lineage,
		&i.Serial,
		&i.Sha256,
		&i.StateBytes,
		&i.Ciphertext,
		&i.CreatedAt,
		&i.Storage,
	)
	return i, err
}
