// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mfa_policy.sql

package database

import (
	"context"
)

const getMFAPolicy = `-- name: GetMFAPolicy :one
SELECT coalesce((SELECT required FROM mfa_policies p WHERE p.scope=$1),false)::boolean AS required,
coalesce((SELECT revision FROM mfa_policies p WHERE p.scope=$1),0)::bigint AS revision,
coalesce((SELECT required FROM mfa_policies p WHERE p.scope=''),false)::boolean AS global_required
`

type GetMFAPolicyRow struct {
	Required       bool
	Revision       int64
	GlobalRequired bool
}

func (q *Queries) GetMFAPolicy(ctx context.Context, scope string) (GetMFAPolicyRow, error) {
	row := q.db.QueryRow(ctx, getMFAPolicy, scope)
	var i GetMFAPolicyRow
	err := row.Scan(&i.Required, &i.Revision, &i.GlobalRequired)
	return i, err
}

const lockMFAPolicies = `-- name: LockMFAPolicies :exec
SELECT scope FROM mfa_policies WHERE scope='' FOR UPDATE
`

func (q *Queries) LockMFAPolicies(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockMFAPolicies)
	return err
}

const mFARequiredForUser = `-- name: MFARequiredForUser :one
SELECT EXISTS(SELECT 1 FROM mfa_policies p WHERE required AND (scope='' OR EXISTS(SELECT 1 FROM effective_memberships m WHERE m.user_id=$1 AND m.org_id=p.scope)))::boolean
`

func (q *Queries) MFARequiredForUser(ctx context.Context, userID string) (bool, error) {
	row := q.db.QueryRow(ctx, mFARequiredForUser, userID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const saveMFAPolicy = `-- name: SaveMFAPolicy :exec
INSERT INTO mfa_policies(scope,required) VALUES($1,$2) ON CONFLICT(scope) DO UPDATE SET required=excluded.required,revision=mfa_policies.revision+1
`

type SaveMFAPolicyParams struct {
	Scope    string
	Required bool
}

func (q *Queries) SaveMFAPolicy(ctx context.Context, arg SaveMFAPolicyParams) error {
	_, err := q.db.Exec(ctx, saveMFAPolicy, arg.Scope, arg.Required)
	return err
}
