// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccountEvent struct {
	ID         int64
	UserID     string
	Action     string
	OccurredAt pgtype.Timestamptz
}

type AuditEvent struct {
	ID         int64
	OrgID      string
	Actor      string
	Action     string
	Target     string
	Details    []byte
	OccurredAt pgtype.Timestamptz
}

type AuditExport struct {
	OrgID       string
	Endpoint    string
	Region      string
	Bucket      string
	Ciphertext  []byte
	Revision    int64
	Enabled     bool
	Verified    bool
	CursorID    int64
	NextBatchAt pgtype.Timestamptz
	Detail      string
	UpdatedAt   pgtype.Timestamptz
}

type AuditExportBatch struct {
	ID          string
	OrgID       string
	Revision    int64
	Kind        string
	FirstID     int64
	LastID      int64
	EventCount  int32
	Payload     []byte
	Checksum    string
	ObjectKey   string
	Status      string
	Attempts    int32
	NextAttempt pgtype.Timestamptz
	LeaseUntil  pgtype.Timestamptz
	Detail      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type AuthLimit struct {
	Key      string
	WindowAt pgtype.Timestamptz
	Attempts int32
}

type AutomationProject struct {
	ID               string
	OrgID            string
	Name             string
	VersionID        string
	StateID          string
	Lineage          string
	Serial           int64
	Sha256           string
	StateBytes       int32
	LockID           string
	LockSessionID    string
	CreatedAt        pgtype.Timestamptz
	InputsCiphertext []byte
	InputsHash       string
}

type AutomationSource struct {
	ID            string
	OrgID         string
	Name          string
	Runtime       string
	Entrypoint    string
	Sha256        string
	Files         []string
	ArchiveBytes  int32
	ExpandedBytes int64
	// Encrypted source ZIP for database storage; encrypted object reference and per-object age identity for s3 storage.
	Ciphertext  []byte
	CreatedAt   pgtype.Timestamptz
	InputSchema []byte
	Storage     string
}

type AutomationState struct {
	ID         string
	OrgID      string
	ProjectID  string
	Lineage    string
	Serial     int64
	Sha256     string
	StateBytes int32
	// Encrypted state bytes for database storage; encrypted object reference and per-object age identity for s3 storage.
	Ciphertext []byte
	CreatedAt  pgtype.Timestamptz
	Storage    string
}

type AutomationStateSession struct {
	ID              string
	OrgID           string
	ProjectID       string
	RequesterID     string
	RequesterOidcID pgtype.UUID
	SecretHash      []byte
	Writable        bool
	ExpiresAt       pgtype.Timestamptz
	Revoked         bool
}

type AutomationValidation struct {
	ID              string
	OrgID           string
	VersionID       string
	RequesterID     string
	RequesterEmail  string
	RequesterOidcID pgtype.UUID
	Status          string
	Detail          string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	LeaseUntil      pgtype.Timestamptz
	ProjectID       string
}

type AutomationVersion struct {
	ID                 string
	OrgID              string
	Name               string
	Version            int32
	SourceID           string
	RuntimeImage       string
	RuntimeVersion     string
	Runtime            string
	ConnectionID       string
	ConnectionRevision int64
	Region             string
	ReviewNote         string
	Status             string
	CreatedAt          pgtype.Timestamptz
	RuntimePolicy      string
	DependencyHosts    []string
}

type Connection struct {
	ID               string
	OrgID            string
	Name             string
	Provider         string
	Region           string
	Enabled          bool
	KeyID            string
	Algorithm        string
	Ciphertext       []byte
	CreatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
	Revision         int64
	ScanStatus       string
	ScanError        string
	LastScanAt       pgtype.Timestamptz
	NextScanAt       pgtype.Timestamptz
	CredentialSource string
}

type Dashboard struct {
	ID        string
	OrgID     string
	UserID    string
	Name      string
	Spec      []byte
	Revision  int64
	UpdatedAt pgtype.Timestamptz
	Shared    bool
	TeamIds   []string
}

type EffectiveMembership struct {
	OrgID       string
	UserID      string
	Permissions []string
}

type IdentityPolicy struct {
	OrgID         string
	Enabled       bool
	Issuer        string
	RecoveryUsers []string
	Revision      int64
}

type InstallationEdition struct {
	Singleton bool
	Edition   string
}

type InstallationEvent struct {
	ID         int64
	ActorID    pgtype.Text
	TargetID   pgtype.Text
	Action     string
	Details    []byte
	OccurredAt pgtype.Timestamptz
	ActorEmail string
}

type InventoryView struct {
	ID        string
	OrgID     string
	UserID    string
	Name      string
	Spec      []byte
	Revision  int64
	UpdatedAt pgtype.Timestamptz
}

type Invitation struct {
	ID             string
	OrgID          string
	Email          string
	RoleID         string
	RoleRevision   int64
	InviterID      string
	TokenHash      []byte
	CreatedAt      pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
	RevokedAt      pgtype.Timestamptz
	AcceptedAt     pgtype.Timestamptz
	TotpCiphertext []byte
}

type MaintenanceConnection struct {
	OrgID        string
	PolicyID     string
	ConnectionID string
}

type MaintenancePolicy struct {
	ID              string
	OrgID           string
	Name            string
	Spec            []byte
	DurationMinutes int32
	CreatedAt       pgtype.Timestamptz
}

type Membership struct {
	OrgID       string
	UserID      string
	Permissions []string
	RoleID      pgtype.Text
	Active      bool
	Revision    int64
}

type MfaPolicy struct {
	Scope    string
	Required bool
	Revision int64
}

type NotificationAttempt struct {
	ID           string
	OrgID        string
	DeliveryID   string
	Number       int32
	Status       string
	ResponseCode int32
	Detail       string
	CreatedAt    pgtype.Timestamptz
}

type NotificationDelivery struct {
	ID                     string
	OrgID                  string
	EventID                string
	DestinationID          string
	DestinationRevision    int64
	VerificationCiphertext []byte
	Status                 string
	Attempts               int32
	RetryCount             int32
	NextAttempt            pgtype.Timestamptz
	LeaseUntil             pgtype.Timestamptz
	Detail                 string
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

type NotificationDestination struct {
	ID                  string
	OrgID               string
	Name                string
	Kind                string
	Endpoint            string
	Ciphertext          []byte
	Revision            int64
	Enabled             bool
	Verified            bool
	IncludeSuccess      bool
	VerificationHash    []byte
	SenderHash          []byte
	VerificationExpires pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	EventTypes          []string
	DeletedAt           pgtype.Timestamptz
}

type NotificationEvent struct {
	ID               string
	OrgID            string
	Type             string
	Target           string
	Payload          []byte
	CreatedAt        pgtype.Timestamptz
	Bucket           pgtype.Int8
	GroupingRevision int64
}

type NotificationSmtp struct {
	OrgID      string
	Ciphertext []byte
	Revision   int64
}

type OidcFlow struct {
	ID          string
	CookieHash  []byte
	ProviderKey string
	UserID      pgtype.Text
	SessionID   pgtype.Text
	Mode        string
	Subject     string
	Claimed     bool
	CreatedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
	ReturnTo    string
}

type OidcLink struct {
	Issuer    string
	Subject   string
	UserID    string
	CreatedAt pgtype.Timestamptz
	ID        pgtype.UUID
}

type Operation struct {
	ID                         string
	OrgID                      string
	ResourceID                 pgtype.Text
	ConnectionID               string
	ConnectionRevision         int64
	Provider                   string
	NativeID                   string
	Region                     string
	ResourceName               string
	Action                     string
	ExpectedStatus             string
	Reason                     string
	RequesterID                string
	RequesterEmail             string
	ApproverID                 pgtype.Text
	PolicyVersion              string
	Status                     string
	IdempotencyKey             string
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
	ApprovalExpiresAt          pgtype.Timestamptz
	ExpiresAt                  pgtype.Timestamptz
	LeaseUntil                 pgtype.Timestamptz
	NextAttemptAt              pgtype.Timestamptz
	ObservationDeadline        pgtype.Timestamptz
	ProviderActionID           string
	ObservedStatus             string
	Detail                     string
	ScheduleID                 pgtype.Text
	ScheduleRevision           pgtype.Int8
	AutomationIdentityID       pgtype.Text
	ScheduledFor               pgtype.Timestamptz
	MaintenanceRevision        int64
	MaintenanceExceptionReason string
	MaintenanceExpiresAt       pgtype.Timestamptz
	ModuleRevision             int64
	RuntimeID                  string
	DeletionImpact             string
	Creation                   []byte
	RequesterOidcID            pgtype.UUID
	ApproverOidcID             pgtype.UUID
	ResourceKind               string
	ExpectedSize               string
	TargetSize                 string
	ProviderIdentity           string
	TemplateID                 pgtype.Text
	ExpectedTags               []byte
	TargetTags                 []byte
	TraceParent                string
}

type Organization struct {
	ID                        string
	Name                      string
	Active                    bool
	Revision                  int64
	MaintenanceRevision       int64
	AdminRevision             int64
	NotificationGroupSeconds  int32
	NotificationGroupRevision int64
}

type ProviderModule struct {
	OrgID     string
	Provider  string
	Enabled   bool
	Revision  int64
	RuntimeID string
}

type RecoveryCode struct {
	UserID    string
	Verifier  []byte
	CreatedAt pgtype.Timestamptz
}

type Resource struct {
	ID               string
	OrgID            string
	ConnectionID     string
	NativeID         string
	Name             string
	Provider         string
	Kind             string
	Region           string
	Status           string
	ObservedAt       pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
	PublicIp         string
	PrivateIp        string
	Size             string
	ProviderIdentity string
	TagMetadata      []byte
}

type ResourceOwnershipClaim struct {
	OrgID        string
	ConnectionID string
	ProjectID    string
	Provider     string
	Kind         string
	Region       string
	NativeID     string
	FirstStateID string
	CreatedAt    pgtype.Timestamptz
}

type Role struct {
	OrgID       string
	ID          string
	Name        string
	Permissions []string
	Builtin     bool
	Revision    int64
}

type ScanJob struct {
	ID             string
	OrgID          string
	ConnectionID   string
	Revision       int64
	RequesterID    string
	Actor          string
	Status         string
	CreatedAt      pgtype.Timestamptz
	LeaseUntil     pgtype.Timestamptz
	FinishedAt     pgtype.Timestamptz
	Error          string
	ModuleRevision int64
	RuntimeID      string
	TraceParent    string
}

type Schedule struct {
	ID                  string
	OrgID               string
	Name                string
	EditorID            string
	EditorEmail         string
	IdentityID          string
	IdentityEnabled     bool
	Enabled             bool
	Revision            int64
	Spec                []byte
	PolicyVersion       string
	ApprovedRevision    pgtype.Int8
	ApproverID          pgtype.Text
	ApprovedAt          pgtype.Timestamptz
	NextDue             pgtype.Timestamptz
	NextAction          string
	NextLocal           string
	NextSkip            string
	LastOutcome         string
	LastDetail          string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	DeletedAt           pgtype.Timestamptz
	MaintenanceRevision int64
	ClockVersion        int16
	EditorOidcID        pgtype.UUID
	ApproverOidcID      pgtype.UUID
	WriteRevision       int64
}

type ScheduleOccurrence struct {
	ID           int64
	OrgID        string
	ScheduleID   string
	Revision     int64
	ResourceID   string
	ScheduledFor pgtype.Timestamptz
	Action       string
	Outcome      string
	Detail       string
	OperationID  pgtype.Text
	CreatedAt    pgtype.Timestamptz
	LocalTime    string
}

type ScheduleTarget struct {
	OrgID              string
	ScheduleID         string
	ResourceID         string
	ConnectionID       string
	ConnectionRevision int64
	ModuleRevision     int64
}

type ServerTemplate struct {
	ID           string
	OrgID        string
	ConnectionID string
	Name         string
	Version      int32
	Region       string
	Creation     []byte
	Status       string
	CreatedAt    pgtype.Timestamptz
}

type Session struct {
	ID          string
	UserID      string
	RefreshHash []byte
	ExpiresAt   pgtype.Timestamptz
	MfaAt       pgtype.Timestamptz
	OidcID      pgtype.UUID
}

type SetupPending struct {
	ID         bool
	Ciphertext []byte
	ExpiresAt  pgtype.Timestamptz
}

type StateOwnershipScan struct {
	StateID        string
	Status         string
	Unsupported    int32
	ScannedAt      pgtype.Timestamptz
	ScannerVersion int32
}

type Team struct {
	OrgID    string
	ID       string
	Name     string
	RoleID   string
	Active   bool
	Revision int64
}

type TeamMember struct {
	OrgID  string
	TeamID string
	UserID string
}

type User struct {
	ID             string
	Email          string
	PasswordHash   []byte
	TotpCiphertext []byte
	LastTotpStep   int64
	Active         bool
	GlobalAdmin    bool
	MfaEnabled     bool
	AdminSeededAt  pgtype.Timestamptz
	AdminRevision  int64
}
