// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: modules.sql

package database

import (
	"context"
)

const getProviderModule = `-- name: GetProviderModule :one
SELECT coalesce(m.enabled,true)::boolean AS enabled,coalesce(m.revision,1)::bigint AS revision,coalesce(m.runtime_id,'')::text AS runtime_id FROM (SELECT $1::text AS org_id,$2::text AS provider) p LEFT JOIN provider_modules m ON m.org_id=p.org_id AND m.provider=p.provider
`

type GetProviderModuleParams struct {
	OrgID    string
	Provider string
}

type GetProviderModuleRow struct {
	Enabled   bool
	Revision  int64
	RuntimeID string
}

func (q *Queries) GetProviderModule(ctx context.Context, arg GetProviderModuleParams) (GetProviderModuleRow, error) {
	row := q.db.QueryRow(ctx, getProviderModule, arg.OrgID, arg.Provider)
	var i GetProviderModuleRow
	err := row.Scan(&i.Enabled, &i.Revision, &i.RuntimeID)
	return i, err
}

const listProviderModules = `-- name: ListProviderModules :many
SELECT p.provider,coalesce(m.enabled,true)::boolean AS enabled,coalesce(m.revision,1)::bigint AS revision,coalesce(m.runtime_id,'')::text AS runtime_id,
 (SELECT count(*) FROM connections c WHERE c.org_id=$1 AND c.provider=p.provider AND c.deleted_at IS NULL)::bigint AS connections,
 (SELECT count(*) FROM operations o WHERE o.org_id=$1 AND o.provider=p.provider AND o.status IN ('dispatching','observing','uncertain'))::bigint AS active_operations
FROM (SELECT 'aws'::text AS provider UNION ALL SELECT 'digitalocean'::text UNION ALL SELECT 'hetzner'::text) p LEFT JOIN provider_modules m ON m.org_id=$1 AND m.provider=p.provider ORDER BY p.provider
`

type ListProviderModulesRow struct {
	Provider         string
	Enabled          bool
	Revision         int64
	RuntimeID        string
	Connections      int64
	ActiveOperations int64
}

func (q *Queries) ListProviderModules(ctx context.Context, orgID string) ([]ListProviderModulesRow, error) {
	rows, err := q.db.Query(ctx, listProviderModules, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProviderModulesRow{}
	for rows.Next() {
		var i ListProviderModulesRow
		if err := rows.Scan(
			&i.Provider,
			&i.Enabled,
			&i.Revision,
			&i.RuntimeID,
			&i.Connections,
			&i.ActiveOperations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordModuleScanCanceled = `-- name: RecordModuleScanCanceled :exec
UPDATE connections SET scan_status='never',scan_error='Provider module changed; refresh after enabling it.' WHERE org_id=$1 AND id=$2 AND revision=$3
`

type RecordModuleScanCanceledParams struct {
	OrgID    string
	ID       string
	Revision int64
}

func (q *Queries) RecordModuleScanCanceled(ctx context.Context, arg RecordModuleScanCanceledParams) error {
	_, err := q.db.Exec(ctx, recordModuleScanCanceled, arg.OrgID, arg.ID, arg.Revision)
	return err
}

const setProviderModule = `-- name: SetProviderModule :exec
INSERT INTO provider_modules(org_id,provider,enabled,revision) VALUES($1,$2,$3,2)
ON CONFLICT(org_id,provider) DO UPDATE SET enabled=excluded.enabled,revision=provider_modules.revision+1 WHERE provider_modules.enabled IS DISTINCT FROM excluded.enabled
`

type SetProviderModuleParams struct {
	OrgID    string
	Provider string
	Enabled  bool
}

func (q *Queries) SetProviderModule(ctx context.Context, arg SetProviderModuleParams) error {
	_, err := q.db.Exec(ctx, setProviderModule, arg.OrgID, arg.Provider, arg.Enabled)
	return err
}

const setProviderRuntime = `-- name: SetProviderRuntime :exec
INSERT INTO provider_modules(org_id,provider,runtime_id,revision) VALUES($1,$2,$3,2)
ON CONFLICT(org_id,provider) DO UPDATE SET runtime_id=excluded.runtime_id,revision=provider_modules.revision+1 WHERE provider_modules.runtime_id IS DISTINCT FROM excluded.runtime_id
`

type SetProviderRuntimeParams struct {
	OrgID     string
	Provider  string
	RuntimeID string
}

func (q *Queries) SetProviderRuntime(ctx context.Context, arg SetProviderRuntimeParams) error {
	_, err := q.db.Exec(ctx, setProviderRuntime, arg.OrgID, arg.Provider, arg.RuntimeID)
	return err
}
