// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addNotificationAttempt = `-- name: AddNotificationAttempt :exec
INSERT INTO notification_attempts(id,org_id,delivery_id,number) VALUES($1,$2,$3,$4)
`

type AddNotificationAttemptParams struct {
	ID         string
	OrgID      string
	DeliveryID string
	Number     int32
}

func (q *Queries) AddNotificationAttempt(ctx context.Context, arg AddNotificationAttemptParams) error {
	_, err := q.db.Exec(ctx, addNotificationAttempt,
		arg.ID,
		arg.OrgID,
		arg.DeliveryID,
		arg.Number,
	)
	return err
}

const cancelRemovedDestinationDeliveries = `-- name: CancelRemovedDestinationDeliveries :exec
UPDATE notification_deliveries SET status='canceled',detail='Destination removed.',lease_until=NULL,updated_at=now() WHERE org_id=$1 AND destination_id=$2 AND status='pending'
`

type CancelRemovedDestinationDeliveriesParams struct {
	OrgID         string
	DestinationID string
}

func (q *Queries) CancelRemovedDestinationDeliveries(ctx context.Context, arg CancelRemovedDestinationDeliveriesParams) error {
	_, err := q.db.Exec(ctx, cancelRemovedDestinationDeliveries, arg.OrgID, arg.DestinationID)
	return err
}

const claimNotificationDelivery = `-- name: ClaimNotificationDelivery :one
UPDATE notification_deliveries SET status='sending',attempts=attempts+1,retry_count=retry_count+1,lease_until=now()+interval '60 seconds',updated_at=now()
WHERE id=(SELECT id FROM notification_deliveries WHERE EXISTS(SELECT 1 FROM organizations o WHERE o.id=notification_deliveries.org_id AND o.active) AND ((status='pending' AND next_attempt<=now()) OR (status='sending' AND lease_until<now())) ORDER BY next_attempt,id FOR UPDATE SKIP LOCKED LIMIT 1) RETURNING id, org_id, event_id, destination_id, destination_revision, verification_ciphertext, status, attempts, retry_count, next_attempt, lease_until, detail, created_at, updated_at
`

func (q *Queries) ClaimNotificationDelivery(ctx context.Context) (NotificationDelivery, error) {
	row := q.db.QueryRow(ctx, claimNotificationDelivery)
	var i NotificationDelivery
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.EventID,
		&i.DestinationID,
		&i.DestinationRevision,
		&i.VerificationCiphertext,
		&i.Status,
		&i.Attempts,
		&i.RetryCount,
		&i.NextAttempt,
		&i.LeaseUntil,
		&i.Detail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const clearDestinationChallenges = `-- name: ClearDestinationChallenges :exec
UPDATE notification_deliveries SET verification_ciphertext=NULL WHERE org_id=$1 AND destination_id=$2 AND verification_ciphertext IS NOT NULL
`

type ClearDestinationChallengesParams struct {
	OrgID         string
	DestinationID string
}

func (q *Queries) ClearDestinationChallenges(ctx context.Context, arg ClearDestinationChallengesParams) error {
	_, err := q.db.Exec(ctx, clearDestinationChallenges, arg.OrgID, arg.DestinationID)
	return err
}

const createDirectNotification = `-- name: CreateDirectNotification :exec
WITH event AS (INSERT INTO notification_events(id,org_id,type,target,payload,bucket) VALUES($1,$2,$3,$4,$5,$6) RETURNING id, org_id, type, target, payload, created_at, bucket, grouping_revision)
INSERT INTO notification_deliveries(id,org_id,event_id,destination_id,destination_revision,verification_ciphertext)
SELECT event.id||':'||d.id,event.org_id,event.id,d.id,d.revision,$7::bytea FROM event JOIN notification_destinations d ON d.org_id=event.org_id AND d.id=event.target
`

type CreateDirectNotificationParams struct {
	ID                     string
	OrgID                  string
	Type                   string
	Target                 string
	Payload                []byte
	Bucket                 pgtype.Int8
	VerificationCiphertext []byte
}

func (q *Queries) CreateDirectNotification(ctx context.Context, arg CreateDirectNotificationParams) error {
	_, err := q.db.Exec(ctx, createDirectNotification,
		arg.ID,
		arg.OrgID,
		arg.Type,
		arg.Target,
		arg.Payload,
		arg.Bucket,
		arg.VerificationCiphertext,
	)
	return err
}

const createNotificationDestination = `-- name: CreateNotificationDestination :exec
INSERT INTO notification_destinations(id,org_id,name,kind,endpoint,ciphertext,include_success) VALUES($1,$2,$3,$4,$5,$6,$7)
`

type CreateNotificationDestinationParams struct {
	ID             string
	OrgID          string
	Name           string
	Kind           string
	Endpoint       string
	Ciphertext     []byte
	IncludeSuccess bool
}

func (q *Queries) CreateNotificationDestination(ctx context.Context, arg CreateNotificationDestinationParams) error {
	_, err := q.db.Exec(ctx, createNotificationDestination,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Kind,
		arg.Endpoint,
		arg.Ciphertext,
		arg.IncludeSuccess,
	)
	return err
}

const deleteNotificationDestination = `-- name: DeleteNotificationDestination :exec
UPDATE notification_destinations SET deleted_at=now(),enabled=false,verified=false,ciphertext=NULL,endpoint='',verification_hash=NULL,sender_hash=NULL,verification_expires=NULL,revision=revision+1 WHERE org_id=$1 AND id=$2
`

type DeleteNotificationDestinationParams struct {
	OrgID string
	ID    string
}

func (q *Queries) DeleteNotificationDestination(ctx context.Context, arg DeleteNotificationDestinationParams) error {
	_, err := q.db.Exec(ctx, deleteNotificationDestination, arg.OrgID, arg.ID)
	return err
}

const enqueueNotificationEvent = `-- name: EnqueueNotificationEvent :exec
WITH event AS (
 INSERT INTO notification_events(id,org_id,type,target,payload,bucket,grouping_revision)
 SELECT $2,o.id,$3,$4,$5,
 CASE WHEN o.notification_group_seconds=0 THEN NULL ELSE floor(extract(epoch FROM statement_timestamp())/o.notification_group_seconds)::bigint END,o.notification_group_revision
 FROM organizations o WHERE o.id=$6
 ON CONFLICT(org_id,type,target,grouping_revision,bucket) DO NOTHING RETURNING id, org_id, type, target, payload, created_at, bucket, grouping_revision
)
INSERT INTO notification_deliveries(id,org_id,event_id,destination_id,destination_revision)
SELECT event.id||':'||d.id,event.org_id,event.id,d.id,d.revision FROM event JOIN notification_destinations d ON d.org_id=event.org_id WHERE d.enabled AND d.verified AND ((cardinality(d.event_types)=0 AND (NOT $1::boolean OR d.include_success)) OR event.type=ANY(d.event_types))
`

type EnqueueNotificationEventParams struct {
	Success bool
	ID      string
	Type    string
	Target  string
	Payload []byte
	OrgID   string
}

func (q *Queries) EnqueueNotificationEvent(ctx context.Context, arg EnqueueNotificationEventParams) error {
	_, err := q.db.Exec(ctx, enqueueNotificationEvent,
		arg.Success,
		arg.ID,
		arg.Type,
		arg.Target,
		arg.Payload,
		arg.OrgID,
	)
	return err
}

const finishNotificationAttempt = `-- name: FinishNotificationAttempt :exec
UPDATE notification_attempts SET status=$3,response_code=$4,detail=$5 WHERE org_id=$1 AND id=$2
`

type FinishNotificationAttemptParams struct {
	OrgID        string
	ID           string
	Status       string
	ResponseCode int32
	Detail       string
}

func (q *Queries) FinishNotificationAttempt(ctx context.Context, arg FinishNotificationAttemptParams) error {
	_, err := q.db.Exec(ctx, finishNotificationAttempt,
		arg.OrgID,
		arg.ID,
		arg.Status,
		arg.ResponseCode,
		arg.Detail,
	)
	return err
}

const finishNotificationDelivery = `-- name: FinishNotificationDelivery :exec
UPDATE notification_deliveries SET status=$3,detail=$4,next_attempt=$5,lease_until=NULL,updated_at=now() WHERE org_id=$1 AND id=$2
`

type FinishNotificationDeliveryParams struct {
	OrgID       string
	ID          string
	Status      string
	Detail      string
	NextAttempt pgtype.Timestamptz
}

func (q *Queries) FinishNotificationDelivery(ctx context.Context, arg FinishNotificationDeliveryParams) error {
	_, err := q.db.Exec(ctx, finishNotificationDelivery,
		arg.OrgID,
		arg.ID,
		arg.Status,
		arg.Detail,
		arg.NextAttempt,
	)
	return err
}

const getNotificationDeliveryMetadata = `-- name: GetNotificationDeliveryMetadata :one
SELECT d.id,d.event_id,d.status,d.attempts,d.detail,d.updated_at,e.type,n.name AS destination_name FROM notification_deliveries d JOIN notification_events e ON e.org_id=d.org_id AND e.id=d.event_id JOIN notification_destinations n ON n.org_id=d.org_id AND n.id=d.destination_id WHERE d.org_id=$1 AND d.id=$2
`

type GetNotificationDeliveryMetadataParams struct {
	OrgID string
	ID    string
}

type GetNotificationDeliveryMetadataRow struct {
	ID              string
	EventID         string
	Status          string
	Attempts        int32
	Detail          string
	UpdatedAt       pgtype.Timestamptz
	Type            string
	DestinationName string
}

func (q *Queries) GetNotificationDeliveryMetadata(ctx context.Context, arg GetNotificationDeliveryMetadataParams) (GetNotificationDeliveryMetadataRow, error) {
	row := q.db.QueryRow(ctx, getNotificationDeliveryMetadata, arg.OrgID, arg.ID)
	var i GetNotificationDeliveryMetadataRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Status,
		&i.Attempts,
		&i.Detail,
		&i.UpdatedAt,
		&i.Type,
		&i.DestinationName,
	)
	return i, err
}

const getNotificationDestination = `-- name: GetNotificationDestination :one
SELECT id, org_id, name, kind, endpoint, ciphertext, revision, enabled, verified, include_success, verification_hash, sender_hash, verification_expires, created_at, event_types, deleted_at FROM notification_destinations WHERE org_id=$1 AND id=$2
`

type GetNotificationDestinationParams struct {
	OrgID string
	ID    string
}

func (q *Queries) GetNotificationDestination(ctx context.Context, arg GetNotificationDestinationParams) (NotificationDestination, error) {
	row := q.db.QueryRow(ctx, getNotificationDestination, arg.OrgID, arg.ID)
	var i NotificationDestination
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Kind,
		&i.Endpoint,
		&i.Ciphertext,
		&i.Revision,
		&i.Enabled,
		&i.Verified,
		&i.IncludeSuccess,
		&i.VerificationHash,
		&i.SenderHash,
		&i.VerificationExpires,
		&i.CreatedAt,
		&i.EventTypes,
		&i.DeletedAt,
	)
	return i, err
}

const getNotificationDestinationMetadata = `-- name: GetNotificationDestinationMetadata :one
SELECT id,name,kind,endpoint,enabled,verified,include_success,event_types,revision FROM notification_destinations WHERE org_id=$1 AND id=$2 AND deleted_at IS NULL
`

type GetNotificationDestinationMetadataParams struct {
	OrgID string
	ID    string
}

type GetNotificationDestinationMetadataRow struct {
	ID             string
	Name           string
	Kind           string
	Endpoint       string
	Enabled        bool
	Verified       bool
	IncludeSuccess bool
	EventTypes     []string
	Revision       int64
}

func (q *Queries) GetNotificationDestinationMetadata(ctx context.Context, arg GetNotificationDestinationMetadataParams) (GetNotificationDestinationMetadataRow, error) {
	row := q.db.QueryRow(ctx, getNotificationDestinationMetadata, arg.OrgID, arg.ID)
	var i GetNotificationDestinationMetadataRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Endpoint,
		&i.Enabled,
		&i.Verified,
		&i.IncludeSuccess,
		&i.EventTypes,
		&i.Revision,
	)
	return i, err
}

const getNotificationEvent = `-- name: GetNotificationEvent :one
SELECT id, org_id, type, target, payload, created_at, bucket, grouping_revision FROM notification_events WHERE org_id=$1 AND id=$2
`

type GetNotificationEventParams struct {
	OrgID string
	ID    string
}

func (q *Queries) GetNotificationEvent(ctx context.Context, arg GetNotificationEventParams) (NotificationEvent, error) {
	row := q.db.QueryRow(ctx, getNotificationEvent, arg.OrgID, arg.ID)
	var i NotificationEvent
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Type,
		&i.Target,
		&i.Payload,
		&i.CreatedAt,
		&i.Bucket,
		&i.GroupingRevision,
	)
	return i, err
}

const getNotificationGrouping = `-- name: GetNotificationGrouping :one
SELECT notification_group_seconds,notification_group_revision FROM organizations WHERE id=$1
`

type GetNotificationGroupingRow struct {
	NotificationGroupSeconds  int32
	NotificationGroupRevision int64
}

func (q *Queries) GetNotificationGrouping(ctx context.Context, id string) (GetNotificationGroupingRow, error) {
	row := q.db.QueryRow(ctx, getNotificationGrouping, id)
	var i GetNotificationGroupingRow
	err := row.Scan(&i.NotificationGroupSeconds, &i.NotificationGroupRevision)
	return i, err
}

const getOrganizationSMTP = `-- name: GetOrganizationSMTP :one
SELECT org_id, ciphertext, revision FROM notification_smtp WHERE org_id=$1
`

func (q *Queries) GetOrganizationSMTP(ctx context.Context, orgID string) (NotificationSmtp, error) {
	row := q.db.QueryRow(ctx, getOrganizationSMTP, orgID)
	var i NotificationSmtp
	err := row.Scan(&i.OrgID, &i.Ciphertext, &i.Revision)
	return i, err
}

const getOrganizationSMTPMetadata = `-- name: GetOrganizationSMTPMetadata :one
SELECT (s.ciphertext IS NOT NULL)::boolean AS configured, COALESCE(s.revision,0)::bigint AS revision FROM organizations o LEFT JOIN notification_smtp s ON s.org_id=o.id WHERE o.id=$1
`

type GetOrganizationSMTPMetadataRow struct {
	Configured bool
	Revision   int64
}

func (q *Queries) GetOrganizationSMTPMetadata(ctx context.Context, id string) (GetOrganizationSMTPMetadataRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationSMTPMetadata, id)
	var i GetOrganizationSMTPMetadataRow
	err := row.Scan(&i.Configured, &i.Revision)
	return i, err
}

const listNotificationAttempts = `-- name: ListNotificationAttempts :many
SELECT id, org_id, delivery_id, number, status, response_code, detail, created_at FROM notification_attempts WHERE org_id=$1 AND delivery_id=$2 ORDER BY number DESC LIMIT 100
`

type ListNotificationAttemptsParams struct {
	OrgID      string
	DeliveryID string
}

func (q *Queries) ListNotificationAttempts(ctx context.Context, arg ListNotificationAttemptsParams) ([]NotificationAttempt, error) {
	rows, err := q.db.Query(ctx, listNotificationAttempts, arg.OrgID, arg.DeliveryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationAttempt{}
	for rows.Next() {
		var i NotificationAttempt
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.DeliveryID,
			&i.Number,
			&i.Status,
			&i.ResponseCode,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationDeliveries = `-- name: ListNotificationDeliveries :many
SELECT d.id, d.org_id, d.event_id, d.destination_id, d.destination_revision, d.verification_ciphertext, d.status, d.attempts, d.retry_count, d.next_attempt, d.lease_until, d.detail, d.created_at, d.updated_at,e.type,n.name AS destination_name FROM notification_deliveries d JOIN notification_events e ON e.id=d.event_id JOIN notification_destinations n ON n.id=d.destination_id WHERE d.org_id=$1 AND d.id<$2 ORDER BY d.id DESC LIMIT 101
`

type ListNotificationDeliveriesParams struct {
	OrgID string
	ID    string
}

type ListNotificationDeliveriesRow struct {
	ID                     string
	OrgID                  string
	EventID                string
	DestinationID          string
	DestinationRevision    int64
	VerificationCiphertext []byte
	Status                 string
	Attempts               int32
	RetryCount             int32
	NextAttempt            pgtype.Timestamptz
	LeaseUntil             pgtype.Timestamptz
	Detail                 string
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	Type                   string
	DestinationName        string
}

func (q *Queries) ListNotificationDeliveries(ctx context.Context, arg ListNotificationDeliveriesParams) ([]ListNotificationDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, listNotificationDeliveries, arg.OrgID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotificationDeliveriesRow{}
	for rows.Next() {
		var i ListNotificationDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.EventID,
			&i.DestinationID,
			&i.DestinationRevision,
			&i.VerificationCiphertext,
			&i.Status,
			&i.Attempts,
			&i.RetryCount,
			&i.NextAttempt,
			&i.LeaseUntil,
			&i.Detail,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Type,
			&i.DestinationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationDestinations = `-- name: ListNotificationDestinations :many
SELECT id, org_id, name, kind, endpoint, ciphertext, revision, enabled, verified, include_success, verification_hash, sender_hash, verification_expires, created_at, event_types, deleted_at FROM notification_destinations WHERE org_id=$1 AND deleted_at IS NULL ORDER BY created_at,id LIMIT 101
`

func (q *Queries) ListNotificationDestinations(ctx context.Context, orgID string) ([]NotificationDestination, error) {
	rows, err := q.db.Query(ctx, listNotificationDestinations, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationDestination{}
	for rows.Next() {
		var i NotificationDestination
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Kind,
			&i.Endpoint,
			&i.Ciphertext,
			&i.Revision,
			&i.Enabled,
			&i.Verified,
			&i.IncludeSuccess,
			&i.VerificationHash,
			&i.SenderHash,
			&i.VerificationExpires,
			&i.CreatedAt,
			&i.EventTypes,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockNotificationDelivery = `-- name: LockNotificationDelivery :one
SELECT id, org_id, event_id, destination_id, destination_revision, verification_ciphertext, status, attempts, retry_count, next_attempt, lease_until, detail, created_at, updated_at FROM notification_deliveries WHERE org_id=$1 AND id=$2 FOR UPDATE
`

type LockNotificationDeliveryParams struct {
	OrgID string
	ID    string
}

func (q *Queries) LockNotificationDelivery(ctx context.Context, arg LockNotificationDeliveryParams) (NotificationDelivery, error) {
	row := q.db.QueryRow(ctx, lockNotificationDelivery, arg.OrgID, arg.ID)
	var i NotificationDelivery
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.EventID,
		&i.DestinationID,
		&i.DestinationRevision,
		&i.VerificationCiphertext,
		&i.Status,
		&i.Attempts,
		&i.RetryCount,
		&i.NextAttempt,
		&i.LeaseUntil,
		&i.Detail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockNotificationDestination = `-- name: LockNotificationDestination :one
SELECT id, org_id, name, kind, endpoint, ciphertext, revision, enabled, verified, include_success, verification_hash, sender_hash, verification_expires, created_at, event_types, deleted_at FROM notification_destinations WHERE org_id=$1 AND id=$2 AND deleted_at IS NULL FOR UPDATE
`

type LockNotificationDestinationParams struct {
	OrgID string
	ID    string
}

func (q *Queries) LockNotificationDestination(ctx context.Context, arg LockNotificationDestinationParams) (NotificationDestination, error) {
	row := q.db.QueryRow(ctx, lockNotificationDestination, arg.OrgID, arg.ID)
	var i NotificationDestination
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Kind,
		&i.Endpoint,
		&i.Ciphertext,
		&i.Revision,
		&i.Enabled,
		&i.Verified,
		&i.IncludeSuccess,
		&i.VerificationHash,
		&i.SenderHash,
		&i.VerificationExpires,
		&i.CreatedAt,
		&i.EventTypes,
		&i.DeletedAt,
	)
	return i, err
}

const markNotificationLostAttempts = `-- name: MarkNotificationLostAttempts :exec
UPDATE notification_attempts SET status='uncertain',detail='Worker lease expired; delivery may have reached the destination.' WHERE org_id=$1 AND delivery_id=$2 AND status='sending'
`

type MarkNotificationLostAttemptsParams struct {
	OrgID      string
	DeliveryID string
}

func (q *Queries) MarkNotificationLostAttempts(ctx context.Context, arg MarkNotificationLostAttemptsParams) error {
	_, err := q.db.Exec(ctx, markNotificationLostAttempts, arg.OrgID, arg.DeliveryID)
	return err
}

const redeliverNotification = `-- name: RedeliverNotification :exec
UPDATE notification_deliveries SET status='pending',retry_count=0,next_attempt=now(),lease_until=NULL,updated_at=now() WHERE org_id=$1 AND id=$2
`

type RedeliverNotificationParams struct {
	OrgID string
	ID    string
}

func (q *Queries) RedeliverNotification(ctx context.Context, arg RedeliverNotificationParams) error {
	_, err := q.db.Exec(ctx, redeliverNotification, arg.OrgID, arg.ID)
	return err
}

const setNotificationChallenge = `-- name: SetNotificationChallenge :exec
UPDATE notification_destinations SET verification_hash=$3,sender_hash=$4,verification_expires=now()+interval '30 minutes',verified=false,revision=revision+1 WHERE org_id=$1 AND id=$2
`

type SetNotificationChallengeParams struct {
	OrgID            string
	ID               string
	VerificationHash []byte
	SenderHash       []byte
}

func (q *Queries) SetNotificationChallenge(ctx context.Context, arg SetNotificationChallengeParams) error {
	_, err := q.db.Exec(ctx, setNotificationChallenge,
		arg.OrgID,
		arg.ID,
		arg.VerificationHash,
		arg.SenderHash,
	)
	return err
}

const setNotificationDestinationEnabled = `-- name: SetNotificationDestinationEnabled :exec
UPDATE notification_destinations SET enabled=$3,revision=revision+1 WHERE org_id=$1 AND id=$2
`

type SetNotificationDestinationEnabledParams struct {
	OrgID   string
	ID      string
	Enabled bool
}

func (q *Queries) SetNotificationDestinationEnabled(ctx context.Context, arg SetNotificationDestinationEnabledParams) error {
	_, err := q.db.Exec(ctx, setNotificationDestinationEnabled, arg.OrgID, arg.ID, arg.Enabled)
	return err
}

const setNotificationGrouping = `-- name: SetNotificationGrouping :one
UPDATE organizations SET notification_group_seconds=$2,notification_group_revision=notification_group_revision+1 WHERE id=$1 AND notification_group_revision=$3 RETURNING notification_group_seconds,notification_group_revision
`

type SetNotificationGroupingParams struct {
	ID                        string
	NotificationGroupSeconds  int32
	NotificationGroupRevision int64
}

type SetNotificationGroupingRow struct {
	NotificationGroupSeconds  int32
	NotificationGroupRevision int64
}

func (q *Queries) SetNotificationGrouping(ctx context.Context, arg SetNotificationGroupingParams) (SetNotificationGroupingRow, error) {
	row := q.db.QueryRow(ctx, setNotificationGrouping, arg.ID, arg.NotificationGroupSeconds, arg.NotificationGroupRevision)
	var i SetNotificationGroupingRow
	err := row.Scan(&i.NotificationGroupSeconds, &i.NotificationGroupRevision)
	return i, err
}

const setNotificationSubscriptions = `-- name: SetNotificationSubscriptions :exec
UPDATE notification_destinations SET event_types=$3,revision=revision+1 WHERE org_id=$1 AND id=$2
`

type SetNotificationSubscriptionsParams struct {
	OrgID      string
	ID         string
	EventTypes []string
}

func (q *Queries) SetNotificationSubscriptions(ctx context.Context, arg SetNotificationSubscriptionsParams) error {
	_, err := q.db.Exec(ctx, setNotificationSubscriptions, arg.OrgID, arg.ID, arg.EventTypes)
	return err
}

const setOrganizationSMTP = `-- name: SetOrganizationSMTP :one
INSERT INTO notification_smtp(org_id,ciphertext) VALUES($1,$2) ON CONFLICT(org_id) DO UPDATE SET ciphertext=EXCLUDED.ciphertext,revision=notification_smtp.revision+1 RETURNING revision
`

type SetOrganizationSMTPParams struct {
	OrgID      string
	Ciphertext []byte
}

func (q *Queries) SetOrganizationSMTP(ctx context.Context, arg SetOrganizationSMTPParams) (int64, error) {
	row := q.db.QueryRow(ctx, setOrganizationSMTP, arg.OrgID, arg.Ciphertext)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const updateNotificationDestination = `-- name: UpdateNotificationDestination :exec
UPDATE notification_destinations SET name=$3,endpoint=$4,ciphertext=$5,include_success=$6,revision=revision+1,verified=false,verification_hash=NULL,sender_hash=NULL,verification_expires=NULL WHERE org_id=$1 AND id=$2
`

type UpdateNotificationDestinationParams struct {
	OrgID          string
	ID             string
	Name           string
	Endpoint       string
	Ciphertext     []byte
	IncludeSuccess bool
}

func (q *Queries) UpdateNotificationDestination(ctx context.Context, arg UpdateNotificationDestinationParams) error {
	_, err := q.db.Exec(ctx, updateNotificationDestination,
		arg.OrgID,
		arg.ID,
		arg.Name,
		arg.Endpoint,
		arg.Ciphertext,
		arg.IncludeSuccess,
	)
	return err
}

const verifyNotificationDestination = `-- name: VerifyNotificationDestination :exec
UPDATE notification_destinations SET verified=true,verification_hash=NULL,sender_hash=NULL,verification_expires=NULL WHERE org_id=$1 AND id=$2
`

type VerifyNotificationDestinationParams struct {
	OrgID string
	ID    string
}

func (q *Queries) VerifyNotificationDestination(ctx context.Context, arg VerifyNotificationDestinationParams) error {
	_, err := q.db.Exec(ctx, verifyNotificationDestination, arg.OrgID, arg.ID)
	return err
}
