// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oidc.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimOIDCFlow = `-- name: ClaimOIDCFlow :one
UPDATE oidc_flows SET claimed=true WHERE id=$1 AND cookie_hash=$2 AND provider_key=$3 AND expires_at>now() AND NOT claimed AND mode IN ('login','link') RETURNING id, cookie_hash, provider_key, user_id, session_id, mode, subject, claimed, created_at, expires_at, return_to
`

type ClaimOIDCFlowParams struct {
	ID          string
	CookieHash  []byte
	ProviderKey string
}

func (q *Queries) ClaimOIDCFlow(ctx context.Context, arg ClaimOIDCFlowParams) (OidcFlow, error) {
	row := q.db.QueryRow(ctx, claimOIDCFlow, arg.ID, arg.CookieHash, arg.ProviderKey)
	var i OidcFlow
	err := row.Scan(
		&i.ID,
		&i.CookieHash,
		&i.ProviderKey,
		&i.UserID,
		&i.SessionID,
		&i.Mode,
		&i.Subject,
		&i.Claimed,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ReturnTo,
	)
	return i, err
}

const clearExpiredOIDCFlows = `-- name: ClearExpiredOIDCFlows :exec
DELETE FROM oidc_flows WHERE expires_at<=now()
`

func (q *Queries) ClearExpiredOIDCFlows(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearExpiredOIDCFlows)
	return err
}

const deleteOIDCFlow = `-- name: DeleteOIDCFlow :exec
DELETE FROM oidc_flows WHERE id=$1
`

func (q *Queries) DeleteOIDCFlow(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteOIDCFlow, id)
	return err
}

const getVerifiedOIDCFlow = `-- name: GetVerifiedOIDCFlow :one
SELECT id, cookie_hash, provider_key, user_id, session_id, mode, subject, claimed, created_at, expires_at, return_to FROM oidc_flows WHERE id=$1 AND cookie_hash=$2 AND provider_key=$3 AND mode='verified' AND expires_at>now()
`

type GetVerifiedOIDCFlowParams struct {
	ID          string
	CookieHash  []byte
	ProviderKey string
}

func (q *Queries) GetVerifiedOIDCFlow(ctx context.Context, arg GetVerifiedOIDCFlowParams) (OidcFlow, error) {
	row := q.db.QueryRow(ctx, getVerifiedOIDCFlow, arg.ID, arg.CookieHash, arg.ProviderKey)
	var i OidcFlow
	err := row.Scan(
		&i.ID,
		&i.CookieHash,
		&i.ProviderKey,
		&i.UserID,
		&i.SessionID,
		&i.Mode,
		&i.Subject,
		&i.Claimed,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ReturnTo,
	)
	return i, err
}

const linkOIDC = `-- name: LinkOIDC :exec
INSERT INTO oidc_links(issuer,subject,user_id) VALUES($1,$2,$3)
`

type LinkOIDCParams struct {
	Issuer  string
	Subject string
	UserID  string
}

func (q *Queries) LinkOIDC(ctx context.Context, arg LinkOIDCParams) error {
	_, err := q.db.Exec(ctx, linkOIDC, arg.Issuer, arg.Subject, arg.UserID)
	return err
}

const lockOIDCFlow = `-- name: LockOIDCFlow :one
SELECT id, cookie_hash, provider_key, user_id, session_id, mode, subject, claimed, created_at, expires_at, return_to FROM oidc_flows WHERE id=$1 AND cookie_hash=$2 AND provider_key=$3 AND mode='verified' AND expires_at>now() FOR UPDATE
`

type LockOIDCFlowParams struct {
	ID          string
	CookieHash  []byte
	ProviderKey string
}

func (q *Queries) LockOIDCFlow(ctx context.Context, arg LockOIDCFlowParams) (OidcFlow, error) {
	row := q.db.QueryRow(ctx, lockOIDCFlow, arg.ID, arg.CookieHash, arg.ProviderKey)
	var i OidcFlow
	err := row.Scan(
		&i.ID,
		&i.CookieHash,
		&i.ProviderKey,
		&i.UserID,
		&i.SessionID,
		&i.Mode,
		&i.Subject,
		&i.Claimed,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ReturnTo,
	)
	return i, err
}

const newOIDCFlow = `-- name: NewOIDCFlow :exec
INSERT INTO oidc_flows(id,cookie_hash,provider_key,user_id,session_id,mode,return_to) VALUES($1,$2,$3,$4,$5,$6,$7)
`

type NewOIDCFlowParams struct {
	ID          string
	CookieHash  []byte
	ProviderKey string
	UserID      pgtype.Text
	SessionID   pgtype.Text
	Mode        string
	ReturnTo    string
}

func (q *Queries) NewOIDCFlow(ctx context.Context, arg NewOIDCFlowParams) error {
	_, err := q.db.Exec(ctx, newOIDCFlow,
		arg.ID,
		arg.CookieHash,
		arg.ProviderKey,
		arg.UserID,
		arg.SessionID,
		arg.Mode,
		arg.ReturnTo,
	)
	return err
}

const oIDCLinkedUser = `-- name: OIDCLinkedUser :one
SELECT u.id, u.email, u.password_hash, u.totp_ciphertext, u.last_totp_step, u.active, u.global_admin, u.mfa_enabled, u.admin_seeded_at, u.admin_revision FROM oidc_links l JOIN users u ON u.id=l.user_id WHERE l.issuer=$1 AND l.subject=$2 AND u.active
`

type OIDCLinkedUserParams struct {
	Issuer  string
	Subject string
}

func (q *Queries) OIDCLinkedUser(ctx context.Context, arg OIDCLinkedUserParams) (User, error) {
	row := q.db.QueryRow(ctx, oIDCLinkedUser, arg.Issuer, arg.Subject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.TotpCiphertext,
		&i.LastTotpStep,
		&i.Active,
		&i.GlobalAdmin,
		&i.MfaEnabled,
		&i.AdminSeededAt,
		&i.AdminRevision,
	)
	return i, err
}

const unlinkOIDC = `-- name: UnlinkOIDC :exec
DELETE FROM oidc_links WHERE user_id=$1 AND issuer=$2
`

type UnlinkOIDCParams struct {
	UserID string
	Issuer string
}

func (q *Queries) UnlinkOIDC(ctx context.Context, arg UnlinkOIDCParams) error {
	_, err := q.db.Exec(ctx, unlinkOIDC, arg.UserID, arg.Issuer)
	return err
}

const userOIDCLink = `-- name: UserOIDCLink :one
SELECT issuer, subject, user_id, created_at, id FROM oidc_links WHERE user_id=$1 AND issuer=$2
`

type UserOIDCLinkParams struct {
	UserID string
	Issuer string
}

func (q *Queries) UserOIDCLink(ctx context.Context, arg UserOIDCLinkParams) (OidcLink, error) {
	row := q.db.QueryRow(ctx, userOIDCLink, arg.UserID, arg.Issuer)
	var i OidcLink
	err := row.Scan(
		&i.Issuer,
		&i.Subject,
		&i.UserID,
		&i.CreatedAt,
		&i.ID,
	)
	return i, err
}

const verifyOIDCFlow = `-- name: VerifyOIDCFlow :exec
UPDATE oidc_flows SET mode='verified',user_id=$2,subject=$3 WHERE id=$1 AND mode='login' AND claimed
`

type VerifyOIDCFlowParams struct {
	ID      string
	UserID  pgtype.Text
	Subject string
}

func (q *Queries) VerifyOIDCFlow(ctx context.Context, arg VerifyOIDCFlowParams) error {
	_, err := q.db.Exec(ctx, verifyOIDCFlow, arg.ID, arg.UserID, arg.Subject)
	return err
}
