// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: operations.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bindCreatedServer = `-- name: BindCreatedServer :exec
UPDATE operations SET native_id=$3,resource_id=$4 WHERE org_id=$1 AND id=$2 AND action='create' AND (native_id='' OR native_id=$3)
`

type BindCreatedServerParams struct {
	OrgID      string
	ID         string
	NativeID   string
	ResourceID pgtype.Text
}

func (q *Queries) BindCreatedServer(ctx context.Context, arg BindCreatedServerParams) error {
	_, err := q.db.Exec(ctx, bindCreatedServer,
		arg.OrgID,
		arg.ID,
		arg.NativeID,
		arg.ResourceID,
	)
	return err
}

const claimOperation = `-- name: ClaimOperation :one
UPDATE operations SET lease_until=now()+interval '3 minutes',updated_at=now(),status=CASE WHEN status='queued' THEN 'dispatching' ELSE status END
WHERE id=(SELECT id FROM operations WHERE status IN ('queued','observing') AND (lease_until IS NULL OR lease_until<=now()) AND next_attempt_at<=now() ORDER BY next_attempt_at,id FOR UPDATE SKIP LOCKED LIMIT 1) RETURNING id, org_id, resource_id, connection_id, connection_revision, provider, native_id, region, resource_name, action, expected_status, reason, requester_id, requester_email, approver_id, policy_version, status, idempotency_key, created_at, updated_at, approval_expires_at, expires_at, lease_until, next_attempt_at, observation_deadline, provider_action_id, observed_status, detail, schedule_id, schedule_revision, automation_identity_id, scheduled_for, maintenance_revision, maintenance_exception_reason, maintenance_expires_at, module_revision, runtime_id, deletion_impact, creation, requester_oidc_id, approver_oidc_id, resource_kind, expected_size, target_size, provider_identity, template_id, expected_tags, target_tags, trace_parent
`

func (q *Queries) ClaimOperation(ctx context.Context) (Operation, error) {
	row := q.db.QueryRow(ctx, claimOperation)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ResourceID,
		&i.ConnectionID,
		&i.ConnectionRevision,
		&i.Provider,
		&i.NativeID,
		&i.Region,
		&i.ResourceName,
		&i.Action,
		&i.ExpectedStatus,
		&i.Reason,
		&i.RequesterID,
		&i.RequesterEmail,
		&i.ApproverID,
		&i.PolicyVersion,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ApprovalExpiresAt,
		&i.ExpiresAt,
		&i.LeaseUntil,
		&i.NextAttemptAt,
		&i.ObservationDeadline,
		&i.ProviderActionID,
		&i.ObservedStatus,
		&i.Detail,
		&i.ScheduleID,
		&i.ScheduleRevision,
		&i.AutomationIdentityID,
		&i.ScheduledFor,
		&i.MaintenanceRevision,
		&i.MaintenanceExceptionReason,
		&i.MaintenanceExpiresAt,
		&i.ModuleRevision,
		&i.RuntimeID,
		&i.DeletionImpact,
		&i.Creation,
		&i.RequesterOidcID,
		&i.ApproverOidcID,
		&i.ResourceKind,
		&i.ExpectedSize,
		&i.TargetSize,
		&i.ProviderIdentity,
		&i.TemplateID,
		&i.ExpectedTags,
		&i.TargetTags,
		&i.TraceParent,
	)
	return i, err
}

const createOperation = `-- name: CreateOperation :one
INSERT INTO operations(id,org_id,resource_id,connection_id,connection_revision,provider,native_id,region,resource_name,action,expected_status,reason,requester_id,requester_email,status,idempotency_key,maintenance_revision,maintenance_exception_reason,maintenance_expires_at,module_revision,runtime_id,deletion_impact,resource_kind,expected_size,target_size,provider_identity,expected_tags,target_tags,trace_parent)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,coalesce(nullif($23::text,''),'compute.server'),$24,$25,$26,$27,$28,$29) RETURNING id, org_id, resource_id, connection_id, connection_revision, provider, native_id, region, resource_name, action, expected_status, reason, requester_id, requester_email, approver_id, policy_version, status, idempotency_key, created_at, updated_at, approval_expires_at, expires_at, lease_until, next_attempt_at, observation_deadline, provider_action_id, observed_status, detail, schedule_id, schedule_revision, automation_identity_id, scheduled_for, maintenance_revision, maintenance_exception_reason, maintenance_expires_at, module_revision, runtime_id, deletion_impact, creation, requester_oidc_id, approver_oidc_id, resource_kind, expected_size, target_size, provider_identity, template_id, expected_tags, target_tags, trace_parent
`

type CreateOperationParams struct {
	ID                         string
	OrgID                      string
	ResourceID                 pgtype.Text
	ConnectionID               string
	ConnectionRevision         int64
	Provider                   string
	NativeID                   string
	Region                     string
	ResourceName               string
	Action                     string
	ExpectedStatus             string
	Reason                     string
	RequesterID                string
	RequesterEmail             string
	Status                     string
	IdempotencyKey             string
	MaintenanceRevision        int64
	MaintenanceExceptionReason string
	MaintenanceExpiresAt       pgtype.Timestamptz
	ModuleRevision             int64
	RuntimeID                  string
	DeletionImpact             string
	ResourceKind               string
	ExpectedSize               string
	TargetSize                 string
	ProviderIdentity           string
	ExpectedTags               []byte
	TargetTags                 []byte
	TraceParent                string
}

func (q *Queries) CreateOperation(ctx context.Context, arg CreateOperationParams) (Operation, error) {
	row := q.db.QueryRow(ctx, createOperation,
		arg.ID,
		arg.OrgID,
		arg.ResourceID,
		arg.ConnectionID,
		arg.ConnectionRevision,
		arg.Provider,
		arg.NativeID,
		arg.Region,
		arg.ResourceName,
		arg.Action,
		arg.ExpectedStatus,
		arg.Reason,
		arg.RequesterID,
		arg.RequesterEmail,
		arg.Status,
		arg.IdempotencyKey,
		arg.MaintenanceRevision,
		arg.MaintenanceExceptionReason,
		arg.MaintenanceExpiresAt,
		arg.ModuleRevision,
		arg.RuntimeID,
		arg.DeletionImpact,
		arg.ResourceKind,
		arg.ExpectedSize,
		arg.TargetSize,
		arg.ProviderIdentity,
		arg.ExpectedTags,
		arg.TargetTags,
		arg.TraceParent,
	)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ResourceID,
		&i.ConnectionID,
		&i.ConnectionRevision,
		&i.Provider,
		&i.NativeID,
		&i.Region,
		&i.ResourceName,
		&i.Action,
		&i.ExpectedStatus,
		&i.Reason,
		&i.RequesterID,
		&i.RequesterEmail,
		&i.ApproverID,
		&i.PolicyVersion,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ApprovalExpiresAt,
		&i.ExpiresAt,
		&i.LeaseUntil,
		&i.NextAttemptAt,
		&i.ObservationDeadline,
		&i.ProviderActionID,
		&i.ObservedStatus,
		&i.Detail,
		&i.ScheduleID,
		&i.ScheduleRevision,
		&i.AutomationIdentityID,
		&i.ScheduledFor,
		&i.MaintenanceRevision,
		&i.MaintenanceExceptionReason,
		&i.MaintenanceExpiresAt,
		&i.ModuleRevision,
		&i.RuntimeID,
		&i.DeletionImpact,
		&i.Creation,
		&i.RequesterOidcID,
		&i.ApproverOidcID,
		&i.ResourceKind,
		&i.ExpectedSize,
		&i.TargetSize,
		&i.ProviderIdentity,
		&i.TemplateID,
		&i.ExpectedTags,
		&i.TargetTags,
		&i.TraceParent,
	)
	return i, err
}

const expiredDispatches = `-- name: ExpiredDispatches :many
SELECT id, org_id, resource_id, connection_id, connection_revision, provider, native_id, region, resource_name, action, expected_status, reason, requester_id, requester_email, approver_id, policy_version, status, idempotency_key, created_at, updated_at, approval_expires_at, expires_at, lease_until, next_attempt_at, observation_deadline, provider_action_id, observed_status, detail, schedule_id, schedule_revision, automation_identity_id, scheduled_for, maintenance_revision, maintenance_exception_reason, maintenance_expires_at, module_revision, runtime_id, deletion_impact, creation, requester_oidc_id, approver_oidc_id, resource_kind, expected_size, target_size, provider_identity, template_id, expected_tags, target_tags, trace_parent FROM operations WHERE status='dispatching' AND lease_until<=now() LIMIT 100
`

func (q *Queries) ExpiredDispatches(ctx context.Context) ([]Operation, error) {
	rows, err := q.db.Query(ctx, expiredDispatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Operation{}
	for rows.Next() {
		var i Operation
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ResourceID,
			&i.ConnectionID,
			&i.ConnectionRevision,
			&i.Provider,
			&i.NativeID,
			&i.Region,
			&i.ResourceName,
			&i.Action,
			&i.ExpectedStatus,
			&i.Reason,
			&i.RequesterID,
			&i.RequesterEmail,
			&i.ApproverID,
			&i.PolicyVersion,
			&i.Status,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ApprovalExpiresAt,
			&i.ExpiresAt,
			&i.LeaseUntil,
			&i.NextAttemptAt,
			&i.ObservationDeadline,
			&i.ProviderActionID,
			&i.ObservedStatus,
			&i.Detail,
			&i.ScheduleID,
			&i.ScheduleRevision,
			&i.AutomationIdentityID,
			&i.ScheduledFor,
			&i.MaintenanceRevision,
			&i.MaintenanceExceptionReason,
			&i.MaintenanceExpiresAt,
			&i.ModuleRevision,
			&i.RuntimeID,
			&i.DeletionImpact,
			&i.Creation,
			&i.RequesterOidcID,
			&i.ApproverOidcID,
			&i.ResourceKind,
			&i.ExpectedSize,
			&i.TargetSize,
			&i.ProviderIdentity,
			&i.TemplateID,
			&i.ExpectedTags,
			&i.TargetTags,
			&i.TraceParent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expiredPendingOperations = `-- name: ExpiredPendingOperations :many
SELECT id, org_id, resource_id, connection_id, connection_revision, provider, native_id, region, resource_name, action, expected_status, reason, requester_id, requester_email, approver_id, policy_version, status, idempotency_key, created_at, updated_at, approval_expires_at, expires_at, lease_until, next_attempt_at, observation_deadline, provider_action_id, observed_status, detail, schedule_id, schedule_revision, automation_identity_id, scheduled_for, maintenance_revision, maintenance_exception_reason, maintenance_expires_at, module_revision, runtime_id, deletion_impact, creation, requester_oidc_id, approver_oidc_id, resource_kind, expected_size, target_size, provider_identity, template_id, expected_tags, target_tags, trace_parent FROM operations WHERE status IN ('awaiting_approval','queued') AND (expires_at<=now() OR approval_expires_at<=now()) LIMIT 100
`

func (q *Queries) ExpiredPendingOperations(ctx context.Context) ([]Operation, error) {
	rows, err := q.db.Query(ctx, expiredPendingOperations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Operation{}
	for rows.Next() {
		var i Operation
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ResourceID,
			&i.ConnectionID,
			&i.ConnectionRevision,
			&i.Provider,
			&i.NativeID,
			&i.Region,
			&i.ResourceName,
			&i.Action,
			&i.ExpectedStatus,
			&i.Reason,
			&i.RequesterID,
			&i.RequesterEmail,
			&i.ApproverID,
			&i.PolicyVersion,
			&i.Status,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ApprovalExpiresAt,
			&i.ExpiresAt,
			&i.LeaseUntil,
			&i.NextAttemptAt,
			&i.ObservationDeadline,
			&i.ProviderActionID,
			&i.ObservedStatus,
			&i.Detail,
			&i.ScheduleID,
			&i.ScheduleRevision,
			&i.AutomationIdentityID,
			&i.ScheduledFor,
			&i.MaintenanceRevision,
			&i.MaintenanceExceptionReason,
			&i.MaintenanceExpiresAt,
			&i.ModuleRevision,
			&i.RuntimeID,
			&i.DeletionImpact,
			&i.Creation,
			&i.RequesterOidcID,
			&i.ApproverOidcID,
			&i.ResourceKind,
			&i.ExpectedSize,
			&i.TargetSize,
			&i.ProviderIdentity,
			&i.TemplateID,
			&i.ExpectedTags,
			&i.TargetTags,
			&i.TraceParent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOperation = `-- name: GetOperation :one
SELECT id, org_id, resource_id, connection_id, connection_revision, provider, native_id, region, resource_name, action, expected_status, reason, requester_id, requester_email, approver_id, policy_version, status, idempotency_key, created_at, updated_at, approval_expires_at, expires_at, lease_until, next_attempt_at, observation_deadline, provider_action_id, observed_status, detail, schedule_id, schedule_revision, automation_identity_id, scheduled_for, maintenance_revision, maintenance_exception_reason, maintenance_expires_at, module_revision, runtime_id, deletion_impact, creation, requester_oidc_id, approver_oidc_id, resource_kind, expected_size, target_size, provider_identity, template_id, expected_tags, target_tags, trace_parent FROM operations WHERE org_id=$1 AND id=$2
`

type GetOperationParams struct {
	OrgID string
	ID    string
}

func (q *Queries) GetOperation(ctx context.Context, arg GetOperationParams) (Operation, error) {
	row := q.db.QueryRow(ctx, getOperation, arg.OrgID, arg.ID)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ResourceID,
		&i.ConnectionID,
		&i.ConnectionRevision,
		&i.Provider,
		&i.NativeID,
		&i.Region,
		&i.ResourceName,
		&i.Action,
		&i.ExpectedStatus,
		&i.Reason,
		&i.RequesterID,
		&i.RequesterEmail,
		&i.ApproverID,
		&i.PolicyVersion,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ApprovalExpiresAt,
		&i.ExpiresAt,
		&i.LeaseUntil,
		&i.NextAttemptAt,
		&i.ObservationDeadline,
		&i.ProviderActionID,
		&i.ObservedStatus,
		&i.Detail,
		&i.ScheduleID,
		&i.ScheduleRevision,
		&i.AutomationIdentityID,
		&i.ScheduledFor,
		&i.MaintenanceRevision,
		&i.MaintenanceExceptionReason,
		&i.MaintenanceExpiresAt,
		&i.ModuleRevision,
		&i.RuntimeID,
		&i.DeletionImpact,
		&i.Creation,
		&i.RequesterOidcID,
		&i.ApproverOidcID,
		&i.ResourceKind,
		&i.ExpectedSize,
		&i.TargetSize,
		&i.ProviderIdentity,
		&i.TemplateID,
		&i.ExpectedTags,
		&i.TargetTags,
		&i.TraceParent,
	)
	return i, err
}

const listOperations = `-- name: ListOperations :many
SELECT id, org_id, resource_id, connection_id, connection_revision, provider, native_id, region, resource_name, action, expected_status, reason, requester_id, requester_email, approver_id, policy_version, status, idempotency_key, created_at, updated_at, approval_expires_at, expires_at, lease_until, next_attempt_at, observation_deadline, provider_action_id, observed_status, detail, schedule_id, schedule_revision, automation_identity_id, scheduled_for, maintenance_revision, maintenance_exception_reason, maintenance_expires_at, module_revision, runtime_id, deletion_impact, creation, requester_oidc_id, approver_oidc_id, resource_kind, expected_size, target_size, provider_identity, template_id, expected_tags, target_tags, trace_parent FROM operations WHERE org_id=$1 AND id<$2
AND (NOT $3::boolean OR resource_id IN (SELECT id FROM filtered_inventory($1::text,$4::text,$5::text,$6::text,$7::text,$8::text,$9::text,$10::boolean,$11::text,$12::jsonb,$13::boolean,$14::text,$15::text)))
ORDER BY id DESC LIMIT 101
`

type ListOperationsParams struct {
	OrgID           string
	ID              string
	FilterResources bool
	Search          string
	Provider        string
	Kind            string
	ConnectionID    string
	TagKey          string
	TagValue        string
	TagExists       bool
	TagName         string
	TagConditions   []byte
	TagMatchAny     bool
	FilterRegion    string
	FilterStatus    string
}

func (q *Queries) ListOperations(ctx context.Context, arg ListOperationsParams) ([]Operation, error) {
	rows, err := q.db.Query(ctx, listOperations,
		arg.OrgID,
		arg.ID,
		arg.FilterResources,
		arg.Search,
		arg.Provider,
		arg.Kind,
		arg.ConnectionID,
		arg.TagKey,
		arg.TagValue,
		arg.TagExists,
		arg.TagName,
		arg.TagConditions,
		arg.TagMatchAny,
		arg.FilterRegion,
		arg.FilterStatus,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Operation{}
	for rows.Next() {
		var i Operation
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ResourceID,
			&i.ConnectionID,
			&i.ConnectionRevision,
			&i.Provider,
			&i.NativeID,
			&i.Region,
			&i.ResourceName,
			&i.Action,
			&i.ExpectedStatus,
			&i.Reason,
			&i.RequesterID,
			&i.RequesterEmail,
			&i.ApproverID,
			&i.PolicyVersion,
			&i.Status,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ApprovalExpiresAt,
			&i.ExpiresAt,
			&i.LeaseUntil,
			&i.NextAttemptAt,
			&i.ObservationDeadline,
			&i.ProviderActionID,
			&i.ObservedStatus,
			&i.Detail,
			&i.ScheduleID,
			&i.ScheduleRevision,
			&i.AutomationIdentityID,
			&i.ScheduledFor,
			&i.MaintenanceRevision,
			&i.MaintenanceExceptionReason,
			&i.MaintenanceExpiresAt,
			&i.ModuleRevision,
			&i.RuntimeID,
			&i.DeletionImpact,
			&i.Creation,
			&i.RequesterOidcID,
			&i.ApproverOidcID,
			&i.ResourceKind,
			&i.ExpectedSize,
			&i.TargetSize,
			&i.ProviderIdentity,
			&i.TemplateID,
			&i.ExpectedTags,
			&i.TargetTags,
			&i.TraceParent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverviewOperations = `-- name: ListOverviewOperations :many
SELECT id, org_id, resource_id, connection_id, connection_revision, provider, native_id, region, resource_name, action, expected_status, reason, requester_id, requester_email, approver_id, policy_version, status, idempotency_key, created_at, updated_at, approval_expires_at, expires_at, lease_until, next_attempt_at, observation_deadline, provider_action_id, observed_status, detail, schedule_id, schedule_revision, automation_identity_id, scheduled_for, maintenance_revision, maintenance_exception_reason, maintenance_expires_at, module_revision, runtime_id, deletion_impact, creation, requester_oidc_id, approver_oidc_id, resource_kind, expected_size, target_size, provider_identity, template_id, expected_tags, target_tags, trace_parent FROM operations WHERE org_id=$1 AND status=ANY($2::text[]) ORDER BY updated_at DESC,id DESC LIMIT 10
`

type ListOverviewOperationsParams struct {
	OrgID    string
	Statuses []string
}

func (q *Queries) ListOverviewOperations(ctx context.Context, arg ListOverviewOperationsParams) ([]Operation, error) {
	rows, err := q.db.Query(ctx, listOverviewOperations, arg.OrgID, arg.Statuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Operation{}
	for rows.Next() {
		var i Operation
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ResourceID,
			&i.ConnectionID,
			&i.ConnectionRevision,
			&i.Provider,
			&i.NativeID,
			&i.Region,
			&i.ResourceName,
			&i.Action,
			&i.ExpectedStatus,
			&i.Reason,
			&i.RequesterID,
			&i.RequesterEmail,
			&i.ApproverID,
			&i.PolicyVersion,
			&i.Status,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ApprovalExpiresAt,
			&i.ExpiresAt,
			&i.LeaseUntil,
			&i.NextAttemptAt,
			&i.ObservationDeadline,
			&i.ProviderActionID,
			&i.ObservedStatus,
			&i.Detail,
			&i.ScheduleID,
			&i.ScheduleRevision,
			&i.AutomationIdentityID,
			&i.ScheduledFor,
			&i.MaintenanceRevision,
			&i.MaintenanceExceptionReason,
			&i.MaintenanceExpiresAt,
			&i.ModuleRevision,
			&i.RuntimeID,
			&i.DeletionImpact,
			&i.Creation,
			&i.RequesterOidcID,
			&i.ApproverOidcID,
			&i.ResourceKind,
			&i.ExpectedSize,
			&i.TargetSize,
			&i.ProviderIdentity,
			&i.TemplateID,
			&i.ExpectedTags,
			&i.TargetTags,
			&i.TraceParent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOperation = `-- name: LockOperation :one
SELECT id, org_id, resource_id, connection_id, connection_revision, provider, native_id, region, resource_name, action, expected_status, reason, requester_id, requester_email, approver_id, policy_version, status, idempotency_key, created_at, updated_at, approval_expires_at, expires_at, lease_until, next_attempt_at, observation_deadline, provider_action_id, observed_status, detail, schedule_id, schedule_revision, automation_identity_id, scheduled_for, maintenance_revision, maintenance_exception_reason, maintenance_expires_at, module_revision, runtime_id, deletion_impact, creation, requester_oidc_id, approver_oidc_id, resource_kind, expected_size, target_size, provider_identity, template_id, expected_tags, target_tags, trace_parent FROM operations WHERE org_id=$1 AND id=$2 FOR UPDATE
`

type LockOperationParams struct {
	OrgID string
	ID    string
}

func (q *Queries) LockOperation(ctx context.Context, arg LockOperationParams) (Operation, error) {
	row := q.db.QueryRow(ctx, lockOperation, arg.OrgID, arg.ID)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ResourceID,
		&i.ConnectionID,
		&i.ConnectionRevision,
		&i.Provider,
		&i.NativeID,
		&i.Region,
		&i.ResourceName,
		&i.Action,
		&i.ExpectedStatus,
		&i.Reason,
		&i.RequesterID,
		&i.RequesterEmail,
		&i.ApproverID,
		&i.PolicyVersion,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ApprovalExpiresAt,
		&i.ExpiresAt,
		&i.LeaseUntil,
		&i.NextAttemptAt,
		&i.ObservationDeadline,
		&i.ProviderActionID,
		&i.ObservedStatus,
		&i.Detail,
		&i.ScheduleID,
		&i.ScheduleRevision,
		&i.AutomationIdentityID,
		&i.ScheduledFor,
		&i.MaintenanceRevision,
		&i.MaintenanceExceptionReason,
		&i.MaintenanceExpiresAt,
		&i.ModuleRevision,
		&i.RuntimeID,
		&i.DeletionImpact,
		&i.Creation,
		&i.RequesterOidcID,
		&i.ApproverOidcID,
		&i.ResourceKind,
		&i.ExpectedSize,
		&i.TargetSize,
		&i.ProviderIdentity,
		&i.TemplateID,
		&i.ExpectedTags,
		&i.TargetTags,
		&i.TraceParent,
	)
	return i, err
}

const lockOperationConnection = `-- name: LockOperationConnection :one
SELECT id, org_id, name, provider, region, enabled, key_id, algorithm, ciphertext, created_at, deleted_at, revision, scan_status, scan_error, last_scan_at, next_scan_at, credential_source FROM connections WHERE org_id=$1 AND id=$2 FOR UPDATE
`

type LockOperationConnectionParams struct {
	OrgID string
	ID    string
}

func (q *Queries) LockOperationConnection(ctx context.Context, arg LockOperationConnectionParams) (Connection, error) {
	row := q.db.QueryRow(ctx, lockOperationConnection, arg.OrgID, arg.ID)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Provider,
		&i.Region,
		&i.Enabled,
		&i.KeyID,
		&i.Algorithm,
		&i.Ciphertext,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.Revision,
		&i.ScanStatus,
		&i.ScanError,
		&i.LastScanAt,
		&i.NextScanAt,
		&i.CredentialSource,
	)
	return i, err
}

const markCloudProjectDeleted = `-- name: MarkCloudProjectDeleted :exec
UPDATE resources SET deleted_at=now(),status='deleted',observed_at=now() WHERE org_id=$1 AND connection_id=$2 AND native_id=$3 AND kind='organization.project'
`

type MarkCloudProjectDeletedParams struct {
	OrgID        string
	ConnectionID string
	NativeID     string
}

func (q *Queries) MarkCloudProjectDeleted(ctx context.Context, arg MarkCloudProjectDeletedParams) error {
	_, err := q.db.Exec(ctx, markCloudProjectDeleted, arg.OrgID, arg.ConnectionID, arg.NativeID)
	return err
}

const markDatabaseSnapshotDeleted = `-- name: MarkDatabaseSnapshotDeleted :exec
UPDATE resources SET deleted_at=now(),status='deleted',observed_at=now() WHERE org_id=$1 AND connection_id=$2 AND native_id=$3 AND kind=$4 AND region=$5 AND kind IN ('database.snapshot','database.cluster_snapshot')
`

type MarkDatabaseSnapshotDeletedParams struct {
	OrgID        string
	ConnectionID string
	NativeID     string
	Kind         string
	Region       string
}

func (q *Queries) MarkDatabaseSnapshotDeleted(ctx context.Context, arg MarkDatabaseSnapshotDeletedParams) error {
	_, err := q.db.Exec(ctx, markDatabaseSnapshotDeleted,
		arg.OrgID,
		arg.ConnectionID,
		arg.NativeID,
		arg.Kind,
		arg.Region,
	)
	return err
}

const markImageDeleted = `-- name: MarkImageDeleted :exec
UPDATE resources SET deleted_at=now(),status='deleted',observed_at=now() WHERE org_id=$1 AND connection_id=$2 AND native_id=$3 AND region=$4 AND kind='compute.image'
`

type MarkImageDeletedParams struct {
	OrgID        string
	ConnectionID string
	NativeID     string
	Region       string
}

func (q *Queries) MarkImageDeleted(ctx context.Context, arg MarkImageDeletedParams) error {
	_, err := q.db.Exec(ctx, markImageDeleted,
		arg.OrgID,
		arg.ConnectionID,
		arg.NativeID,
		arg.Region,
	)
	return err
}

const markNetworkDeleted = `-- name: MarkNetworkDeleted :exec
UPDATE resources SET deleted_at=now(),status='deleted',observed_at=now() WHERE org_id=$1 AND connection_id=$2 AND native_id=$3 AND kind=$4 AND kind IN ('network.network','network.firewall','network.load_balancer') AND (provider<>'aws' OR region=$5)
`

type MarkNetworkDeletedParams struct {
	OrgID        string
	ConnectionID string
	NativeID     string
	Kind         string
	Region       string
}

func (q *Queries) MarkNetworkDeleted(ctx context.Context, arg MarkNetworkDeletedParams) error {
	_, err := q.db.Exec(ctx, markNetworkDeleted,
		arg.OrgID,
		arg.ConnectionID,
		arg.NativeID,
		arg.Kind,
		arg.Region,
	)
	return err
}

const markPlacementGroupDeleted = `-- name: MarkPlacementGroupDeleted :exec
UPDATE resources SET deleted_at=now(),status='deleted',observed_at=now() WHERE org_id=$1 AND connection_id=$2 AND native_id=$3 AND kind='compute.placement_group' AND (provider<>'aws' OR region=$4)
`

type MarkPlacementGroupDeletedParams struct {
	OrgID        string
	ConnectionID string
	NativeID     string
	Region       string
}

func (q *Queries) MarkPlacementGroupDeleted(ctx context.Context, arg MarkPlacementGroupDeletedParams) error {
	_, err := q.db.Exec(ctx, markPlacementGroupDeleted,
		arg.OrgID,
		arg.ConnectionID,
		arg.NativeID,
		arg.Region,
	)
	return err
}

const markSSHKeyDeleted = `-- name: MarkSSHKeyDeleted :exec
UPDATE resources SET deleted_at=now(),status='deleted',observed_at=now() WHERE org_id=$1 AND connection_id=$2 AND native_id=$3 AND kind='access.ssh_key' AND (provider<>'aws' OR region=$4)
`

type MarkSSHKeyDeletedParams struct {
	OrgID        string
	ConnectionID string
	NativeID     string
	Region       string
}

func (q *Queries) MarkSSHKeyDeleted(ctx context.Context, arg MarkSSHKeyDeletedParams) error {
	_, err := q.db.Exec(ctx, markSSHKeyDeleted,
		arg.OrgID,
		arg.ConnectionID,
		arg.NativeID,
		arg.Region,
	)
	return err
}

const markServerDeleted = `-- name: MarkServerDeleted :exec
UPDATE resources SET deleted_at=now(),status='deleted',observed_at=now() WHERE org_id=$1 AND id=$2 AND kind='compute.server'
`

type MarkServerDeletedParams struct {
	OrgID string
	ID    string
}

func (q *Queries) MarkServerDeleted(ctx context.Context, arg MarkServerDeletedParams) error {
	_, err := q.db.Exec(ctx, markServerDeleted, arg.OrgID, arg.ID)
	return err
}

const markSnapshotDeleted = `-- name: MarkSnapshotDeleted :exec
UPDATE resources SET deleted_at=now(),status='deleted',observed_at=now() WHERE org_id=$1 AND connection_id=$2 AND native_id=$3 AND kind IN ('storage.snapshot','compute.image')
`

type MarkSnapshotDeletedParams struct {
	OrgID        string
	ConnectionID string
	NativeID     string
}

func (q *Queries) MarkSnapshotDeleted(ctx context.Context, arg MarkSnapshotDeletedParams) error {
	_, err := q.db.Exec(ctx, markSnapshotDeleted, arg.OrgID, arg.ConnectionID, arg.NativeID)
	return err
}

const markVolumeDeleted = `-- name: MarkVolumeDeleted :exec
UPDATE resources SET deleted_at=now(),status='deleted',observed_at=now() WHERE org_id=$1 AND connection_id=$2 AND native_id=$3 AND kind='storage.volume'
`

type MarkVolumeDeletedParams struct {
	OrgID        string
	ConnectionID string
	NativeID     string
}

func (q *Queries) MarkVolumeDeleted(ctx context.Context, arg MarkVolumeDeletedParams) error {
	_, err := q.db.Exec(ctx, markVolumeDeleted, arg.OrgID, arg.ConnectionID, arg.NativeID)
	return err
}

const operationByKey = `-- name: OperationByKey :one
SELECT id, org_id, resource_id, connection_id, connection_revision, provider, native_id, region, resource_name, action, expected_status, reason, requester_id, requester_email, approver_id, policy_version, status, idempotency_key, created_at, updated_at, approval_expires_at, expires_at, lease_until, next_attempt_at, observation_deadline, provider_action_id, observed_status, detail, schedule_id, schedule_revision, automation_identity_id, scheduled_for, maintenance_revision, maintenance_exception_reason, maintenance_expires_at, module_revision, runtime_id, deletion_impact, creation, requester_oidc_id, approver_oidc_id, resource_kind, expected_size, target_size, provider_identity, template_id, expected_tags, target_tags, trace_parent FROM operations WHERE org_id=$1 AND requester_id=$2 AND idempotency_key=$3
`

type OperationByKeyParams struct {
	OrgID          string
	RequesterID    string
	IdempotencyKey string
}

func (q *Queries) OperationByKey(ctx context.Context, arg OperationByKeyParams) (Operation, error) {
	row := q.db.QueryRow(ctx, operationByKey, arg.OrgID, arg.RequesterID, arg.IdempotencyKey)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ResourceID,
		&i.ConnectionID,
		&i.ConnectionRevision,
		&i.Provider,
		&i.NativeID,
		&i.Region,
		&i.ResourceName,
		&i.Action,
		&i.ExpectedStatus,
		&i.Reason,
		&i.RequesterID,
		&i.RequesterEmail,
		&i.ApproverID,
		&i.PolicyVersion,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ApprovalExpiresAt,
		&i.ExpiresAt,
		&i.LeaseUntil,
		&i.NextAttemptAt,
		&i.ObservationDeadline,
		&i.ProviderActionID,
		&i.ObservedStatus,
		&i.Detail,
		&i.ScheduleID,
		&i.ScheduleRevision,
		&i.AutomationIdentityID,
		&i.ScheduledFor,
		&i.MaintenanceRevision,
		&i.MaintenanceExceptionReason,
		&i.MaintenanceExpiresAt,
		&i.ModuleRevision,
		&i.RuntimeID,
		&i.DeletionImpact,
		&i.Creation,
		&i.RequesterOidcID,
		&i.ApproverOidcID,
		&i.ResourceKind,
		&i.ExpectedSize,
		&i.TargetSize,
		&i.ProviderIdentity,
		&i.TemplateID,
		&i.ExpectedTags,
		&i.TargetTags,
		&i.TraceParent,
	)
	return i, err
}

const operationOverviewCounts = `-- name: OperationOverviewCounts :one
SELECT count(*) FILTER (WHERE status='awaiting_approval') AS pending,
 count(*) FILTER (WHERE status IN ('queued','dispatching','observing')) AS active,
 count(*) FILTER (WHERE status='failed') AS failed,
 count(*) FILTER (WHERE status='uncertain') AS uncertain
FROM operations WHERE org_id=$1
`

type OperationOverviewCountsRow struct {
	Pending   int64
	Active    int64
	Failed    int64
	Uncertain int64
}

func (q *Queries) OperationOverviewCounts(ctx context.Context, orgID string) (OperationOverviewCountsRow, error) {
	row := q.db.QueryRow(ctx, operationOverviewCounts, orgID)
	var i OperationOverviewCountsRow
	err := row.Scan(
		&i.Pending,
		&i.Active,
		&i.Failed,
		&i.Uncertain,
	)
	return i, err
}

const recheckOperation = `-- name: RecheckOperation :exec
UPDATE operations SET status='observing',lease_until=NULL,next_attempt_at=now(),observation_deadline=now()+interval '15 minutes',updated_at=now(),detail='Checking provider state; no action will be resubmitted.' WHERE org_id=$1 AND id=$2
`

type RecheckOperationParams struct {
	OrgID string
	ID    string
}

func (q *Queries) RecheckOperation(ctx context.Context, arg RecheckOperationParams) error {
	_, err := q.db.Exec(ctx, recheckOperation, arg.OrgID, arg.ID)
	return err
}

const refreshAfterOperation = `-- name: RefreshAfterOperation :exec
UPDATE connections SET next_scan_at=now() WHERE org_id=$1 AND id=$2 AND enabled AND deleted_at IS NULL
`

type RefreshAfterOperationParams struct {
	OrgID string
	ID    string
}

func (q *Queries) RefreshAfterOperation(ctx context.Context, arg RefreshAfterOperationParams) error {
	_, err := q.db.Exec(ctx, refreshAfterOperation, arg.OrgID, arg.ID)
	return err
}

const reviewOperation = `-- name: ReviewOperation :exec
UPDATE operations SET status=$3,approver_id=$4,approval_expires_at=now()+interval '1 hour',updated_at=now(),detail=$5,approver_oidc_id=$6::uuid WHERE org_id=$1 AND id=$2
`

type ReviewOperationParams struct {
	OrgID      string
	ID         string
	Status     string
	ApproverID pgtype.Text
	Detail     string
	OidcID     pgtype.UUID
}

func (q *Queries) ReviewOperation(ctx context.Context, arg ReviewOperationParams) error {
	_, err := q.db.Exec(ctx, reviewOperation,
		arg.OrgID,
		arg.ID,
		arg.Status,
		arg.ApproverID,
		arg.Detail,
		arg.OidcID,
	)
	return err
}

const saveCreationInput = `-- name: SaveCreationInput :exec
UPDATE operations SET creation=$3 WHERE org_id=$1 AND id=$2
`

type SaveCreationInputParams struct {
	OrgID    string
	ID       string
	Creation []byte
}

func (q *Queries) SaveCreationInput(ctx context.Context, arg SaveCreationInputParams) error {
	_, err := q.db.Exec(ctx, saveCreationInput, arg.OrgID, arg.ID, arg.Creation)
	return err
}

const saveOperationOutcome = `-- name: SaveOperationOutcome :exec
UPDATE operations SET status=$3,provider_action_id=$4,observed_status=$5,detail=$6,updated_at=now(),next_attempt_at=now()+interval '5 seconds',
 observation_deadline=coalesce(observation_deadline,now()+interval '15 minutes'),lease_until=CASE WHEN $3='observing' THEN NULL ELSE lease_until END
WHERE org_id=$1 AND id=$2
`

type SaveOperationOutcomeParams struct {
	OrgID            string
	ID               string
	Status           string
	ProviderActionID string
	ObservedStatus   string
	Detail           string
}

func (q *Queries) SaveOperationOutcome(ctx context.Context, arg SaveOperationOutcomeParams) error {
	_, err := q.db.Exec(ctx, saveOperationOutcome,
		arg.OrgID,
		arg.ID,
		arg.Status,
		arg.ProviderActionID,
		arg.ObservedStatus,
		arg.Detail,
	)
	return err
}

const updateObservedServerTags = `-- name: UpdateObservedServerTags :exec
UPDATE resources SET tag_metadata=$5 WHERE org_id=$1 AND connection_id=$2 AND native_id=$3 AND region=$4 AND kind='compute.server' AND deleted_at IS NULL
`

type UpdateObservedServerTagsParams struct {
	OrgID        string
	ConnectionID string
	NativeID     string
	Region       string
	TagMetadata  []byte
}

func (q *Queries) UpdateObservedServerTags(ctx context.Context, arg UpdateObservedServerTagsParams) error {
	_, err := q.db.Exec(ctx, updateObservedServerTags,
		arg.OrgID,
		arg.ConnectionID,
		arg.NativeID,
		arg.Region,
		arg.TagMetadata,
	)
	return err
}

const upsertCreatedSSHKey = `-- name: UpsertCreatedSSHKey :one
INSERT INTO resources(id,org_id,connection_id,native_id,name,provider,kind,region,status)
VALUES($1,$2,$3,$4,$5,$6,'access.ssh_key',$7,$8)
ON CONFLICT(org_id,connection_id,kind,region,native_id) DO UPDATE SET status=excluded.status,observed_at=now(),deleted_at=NULL
RETURNING id
`

type UpsertCreatedSSHKeyParams struct {
	ID           string
	OrgID        string
	ConnectionID string
	NativeID     string
	Name         string
	Provider     string
	Region       string
	Status       string
}

func (q *Queries) UpsertCreatedSSHKey(ctx context.Context, arg UpsertCreatedSSHKeyParams) (string, error) {
	row := q.db.QueryRow(ctx, upsertCreatedSSHKey,
		arg.ID,
		arg.OrgID,
		arg.ConnectionID,
		arg.NativeID,
		arg.Name,
		arg.Provider,
		arg.Region,
		arg.Status,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const upsertCreatedServer = `-- name: UpsertCreatedServer :one
INSERT INTO resources(id,org_id,connection_id,native_id,name,provider,kind,region,status,size)
VALUES($1,$2,$3,$4,$5,$6,'compute.server',$7,$8,$9)
ON CONFLICT(org_id,connection_id,kind,region,native_id) DO UPDATE SET status=excluded.status,observed_at=now(),deleted_at=NULL
RETURNING id
`

type UpsertCreatedServerParams struct {
	ID           string
	OrgID        string
	ConnectionID string
	NativeID     string
	Name         string
	Provider     string
	Region       string
	Status       string
	Size         string
}

func (q *Queries) UpsertCreatedServer(ctx context.Context, arg UpsertCreatedServerParams) (string, error) {
	row := q.db.QueryRow(ctx, upsertCreatedServer,
		arg.ID,
		arg.OrgID,
		arg.ConnectionID,
		arg.NativeID,
		arg.Name,
		arg.Provider,
		arg.Region,
		arg.Status,
		arg.Size,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
