// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ownership.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertOwnershipClaims = `-- name: InsertOwnershipClaims :exec
INSERT INTO resource_ownership_claims(org_id,connection_id,project_id,provider,kind,region,native_id,first_state_id)
SELECT $1,$2,$3,$4,r.kind,r.region,r.native_id,$5
FROM jsonb_to_recordset($6::jsonb) AS r(kind text,native_id text,region text)
ON CONFLICT DO NOTHING
`

type InsertOwnershipClaimsParams struct {
	OrgID        string
	ConnectionID string
	ProjectID    string
	Provider     string
	StateID      string
	Refs         []byte
}

func (q *Queries) InsertOwnershipClaims(ctx context.Context, arg InsertOwnershipClaimsParams) error {
	_, err := q.db.Exec(ctx, insertOwnershipClaims,
		arg.OrgID,
		arg.ConnectionID,
		arg.ProjectID,
		arg.Provider,
		arg.StateID,
		arg.Refs,
	)
	return err
}

const listProjectOwnership = `-- name: ListProjectOwnership :many
SELECT c.org_id, c.connection_id, c.project_id, c.provider, c.kind, c.region, c.native_id, c.first_state_id, c.created_at, (c.kind||'/'||c.region||'/'||c.native_id)::text AS page_key,
 COALESCE((SELECT r.id FROM resources r WHERE r.org_id=c.org_id AND r.connection_id=c.connection_id AND r.kind=c.kind AND r.native_id=c.native_id AND (c.provider<>'aws' OR r.region=c.region) AND r.deleted_at IS NULL ORDER BY r.region,r.id LIMIT 1),'')::text AS resource_id,
 EXISTS(SELECT 1 FROM resource_ownership_claims other WHERE other.org_id=c.org_id AND other.connection_id=c.connection_id AND other.kind=c.kind AND other.native_id=c.native_id AND (c.provider<>'aws' OR other.region=c.region) AND other.project_id<>c.project_id) AS conflicting
FROM resource_ownership_claims c WHERE c.org_id=$1 AND c.project_id=$2 AND (c.kind||'/'||c.region||'/'||c.native_id)>$3::text ORDER BY page_key LIMIT 101
`

type ListProjectOwnershipParams struct {
	OrgID     string
	ProjectID string
	AfterKey  string
}

type ListProjectOwnershipRow struct {
	OrgID        string
	ConnectionID string
	ProjectID    string
	Provider     string
	Kind         string
	Region       string
	NativeID     string
	FirstStateID string
	CreatedAt    pgtype.Timestamptz
	PageKey      string
	ResourceID   string
	Conflicting  bool
}

func (q *Queries) ListProjectOwnership(ctx context.Context, arg ListProjectOwnershipParams) ([]ListProjectOwnershipRow, error) {
	rows, err := q.db.Query(ctx, listProjectOwnership, arg.OrgID, arg.ProjectID, arg.AfterKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectOwnershipRow{}
	for rows.Next() {
		var i ListProjectOwnershipRow
		if err := rows.Scan(
			&i.OrgID,
			&i.ConnectionID,
			&i.ProjectID,
			&i.Provider,
			&i.Kind,
			&i.Region,
			&i.NativeID,
			&i.FirstStateID,
			&i.CreatedAt,
			&i.PageKey,
			&i.ResourceID,
			&i.Conflicting,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ownershipProjectScope = `-- name: OwnershipProjectScope :one
SELECT c.provider,v.connection_id,v.region FROM automation_projects p JOIN automation_versions v ON v.org_id=p.org_id AND v.id=p.version_id JOIN connections c ON c.org_id=v.org_id AND c.id=v.connection_id WHERE p.org_id=$1 AND p.id=$2
`

type OwnershipProjectScopeParams struct {
	OrgID string
	ID    string
}

type OwnershipProjectScopeRow struct {
	Provider     string
	ConnectionID string
	Region       string
}

func (q *Queries) OwnershipProjectScope(ctx context.Context, arg OwnershipProjectScopeParams) (OwnershipProjectScopeRow, error) {
	row := q.db.QueryRow(ctx, ownershipProjectScope, arg.OrgID, arg.ID)
	var i OwnershipProjectScopeRow
	err := row.Scan(&i.Provider, &i.ConnectionID, &i.Region)
	return i, err
}

const projectOwnershipSummary = `-- name: ProjectOwnershipSummary :one
SELECT COALESCE(scan.status,CASE WHEN p.state_id='' THEN 'no_state' ELSE 'pending' END)::text AS status,
 COALESCE(scan.unsupported,0)::integer AS unsupported, COALESCE(scan.scanner_version,0)::integer AS scanner_version,
 scan.scanned_at,
 (SELECT count(*) FROM resource_ownership_claims c WHERE c.org_id=p.org_id AND c.project_id=p.id)::bigint AS protected_references,
 (SELECT count(*) FROM automation_states s LEFT JOIN state_ownership_scans x ON x.state_id=s.id WHERE s.org_id=p.org_id AND s.project_id=p.id AND (x.state_id IS NULL OR x.status<>'complete' OR x.scanner_version<11))::bigint AS incomplete_versions
FROM automation_projects p LEFT JOIN state_ownership_scans scan ON scan.state_id=p.state_id WHERE p.org_id=$1 AND p.id=$2
`

type ProjectOwnershipSummaryParams struct {
	OrgID string
	ID    string
}

type ProjectOwnershipSummaryRow struct {
	Status              string
	Unsupported         int32
	ScannerVersion      int32
	ScannedAt           pgtype.Timestamptz
	ProtectedReferences int64
	IncompleteVersions  int64
}

func (q *Queries) ProjectOwnershipSummary(ctx context.Context, arg ProjectOwnershipSummaryParams) (ProjectOwnershipSummaryRow, error) {
	row := q.db.QueryRow(ctx, projectOwnershipSummary, arg.OrgID, arg.ID)
	var i ProjectOwnershipSummaryRow
	err := row.Scan(
		&i.Status,
		&i.Unsupported,
		&i.ScannerVersion,
		&i.ScannedAt,
		&i.ProtectedReferences,
		&i.IncompleteVersions,
	)
	return i, err
}

const recordOwnershipScan = `-- name: RecordOwnershipScan :exec
INSERT INTO state_ownership_scans(state_id,status,unsupported,scanner_version) VALUES($1,$2,$3,11) ON CONFLICT(state_id) DO UPDATE SET status=EXCLUDED.status,unsupported=EXCLUDED.unsupported,scanner_version=EXCLUDED.scanner_version,scanned_at=now()
`

type RecordOwnershipScanParams struct {
	StateID     string
	Status      string
	Unsupported int32
}

func (q *Queries) RecordOwnershipScan(ctx context.Context, arg RecordOwnershipScanParams) error {
	_, err := q.db.Exec(ctx, recordOwnershipScan, arg.StateID, arg.Status, arg.Unsupported)
	return err
}

const resourceOwnership = `-- name: ResourceOwnership :many
SELECT DISTINCT project_id FROM resource_ownership_claims WHERE org_id=$1 AND connection_id=$2 AND kind=$3 AND native_id=$4 AND (provider<>'aws' OR region=$5) ORDER BY project_id
`

type ResourceOwnershipParams struct {
	OrgID        string
	ConnectionID string
	Kind         string
	NativeID     string
	Region       string
}

func (q *Queries) ResourceOwnership(ctx context.Context, arg ResourceOwnershipParams) ([]string, error) {
	rows, err := q.db.Query(ctx, resourceOwnership,
		arg.OrgID,
		arg.ConnectionID,
		arg.Kind,
		arg.NativeID,
		arg.Region,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var project_id string
		if err := rows.Scan(&project_id); err != nil {
			return nil, err
		}
		items = append(items, project_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unindexedOwnershipState = `-- name: UnindexedOwnershipState :one
SELECT s.id, s.org_id, s.project_id, s.lineage, s.serial, s.sha256, s.state_bytes, s.ciphertext, s.created_at, s.storage FROM automation_states s LEFT JOIN state_ownership_scans scan ON scan.state_id=s.id WHERE scan.state_id IS NULL OR scan.scanner_version < 11 ORDER BY s.created_at,s.id LIMIT 1
`

func (q *Queries) UnindexedOwnershipState(ctx context.Context) (AutomationState, error) {
	row := q.db.QueryRow(ctx, unindexedOwnershipState)
	var i AutomationState
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Lineage,
		&i.Serial,
		&i.Sha256,
		&i.StateBytes,
		&i.Ciphertext,
		&i.CreatedAt,
		&i.Storage,
	)
	return i, err
}
