// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recovery.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addAccountEvent = `-- name: AddAccountEvent :exec
INSERT INTO account_events(user_id,action) VALUES($1,$2)
`

type AddAccountEventParams struct {
	UserID string
	Action string
}

func (q *Queries) AddAccountEvent(ctx context.Context, arg AddAccountEventParams) error {
	_, err := q.db.Exec(ctx, addAccountEvent, arg.UserID, arg.Action)
	return err
}

const addRecoveryCode = `-- name: AddRecoveryCode :exec
INSERT INTO recovery_codes(user_id,verifier) VALUES($1,$2)
`

type AddRecoveryCodeParams struct {
	UserID   string
	Verifier []byte
}

func (q *Queries) AddRecoveryCode(ctx context.Context, arg AddRecoveryCodeParams) error {
	_, err := q.db.Exec(ctx, addRecoveryCode, arg.UserID, arg.Verifier)
	return err
}

const changePassword = `-- name: ChangePassword :exec
UPDATE users SET password_hash=$2 WHERE id=$1
`

type ChangePasswordParams struct {
	ID           string
	PasswordHash []byte
}

func (q *Queries) ChangePassword(ctx context.Context, arg ChangePasswordParams) error {
	_, err := q.db.Exec(ctx, changePassword, arg.ID, arg.PasswordHash)
	return err
}

const clearRecoveryCodes = `-- name: ClearRecoveryCodes :exec
DELETE FROM recovery_codes WHERE user_id=$1
`

func (q *Queries) ClearRecoveryCodes(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, clearRecoveryCodes, userID)
	return err
}

const consumeRecoveryCode = `-- name: ConsumeRecoveryCode :execrows
DELETE FROM recovery_codes WHERE user_id=$1 AND verifier=$2
`

type ConsumeRecoveryCodeParams struct {
	UserID   string
	Verifier []byte
}

func (q *Queries) ConsumeRecoveryCode(ctx context.Context, arg ConsumeRecoveryCodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeRecoveryCode, arg.UserID, arg.Verifier)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAccountSession = `-- name: DeleteAccountSession :execrows
DELETE FROM sessions WHERE user_id=$1 AND id=$2
`

type DeleteAccountSessionParams struct {
	UserID string
	ID     string
}

func (q *Queries) DeleteAccountSession(ctx context.Context, arg DeleteAccountSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAccountSession, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id=$1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userID)
	return err
}

const listAccountEvents = `-- name: ListAccountEvents :many
SELECT id,action,occurred_at FROM account_events WHERE user_id=$1 ORDER BY id DESC LIMIT 25
`

type ListAccountEventsRow struct {
	ID         int64
	Action     string
	OccurredAt pgtype.Timestamptz
}

func (q *Queries) ListAccountEvents(ctx context.Context, userID string) ([]ListAccountEventsRow, error) {
	rows, err := q.db.Query(ctx, listAccountEvents, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountEventsRow{}
	for rows.Next() {
		var i ListAccountEventsRow
		if err := rows.Scan(&i.ID, &i.Action, &i.OccurredAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountSessions = `-- name: ListAccountSessions :many
SELECT id,expires_at,mfa_at,oidc_id FROM sessions WHERE user_id=$1 AND expires_at>now() AND id<$2 ORDER BY id DESC LIMIT 101
`

type ListAccountSessionsParams struct {
	UserID string
	ID     string
}

type ListAccountSessionsRow struct {
	ID        string
	ExpiresAt pgtype.Timestamptz
	MfaAt     pgtype.Timestamptz
	OidcID    pgtype.UUID
}

func (q *Queries) ListAccountSessions(ctx context.Context, arg ListAccountSessionsParams) ([]ListAccountSessionsRow, error) {
	rows, err := q.db.Query(ctx, listAccountSessions, arg.UserID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountSessionsRow{}
	for rows.Next() {
		var i ListAccountSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ExpiresAt,
			&i.MfaAt,
			&i.OidcID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRecoveryUser = `-- name: LockRecoveryUser :one
SELECT id, email, password_hash, totp_ciphertext, last_totp_step, active, global_admin, mfa_enabled, admin_seeded_at, admin_revision FROM users WHERE id=$1 AND active FOR UPDATE
`

func (q *Queries) LockRecoveryUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, lockRecoveryUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.TotpCiphertext,
		&i.LastTotpStep,
		&i.Active,
		&i.GlobalAdmin,
		&i.MfaEnabled,
		&i.AdminSeededAt,
		&i.AdminRevision,
	)
	return i, err
}

const recoveryCodeCount = `-- name: RecoveryCodeCount :one
SELECT count(*) FROM recovery_codes WHERE user_id=$1
`

func (q *Queries) RecoveryCodeCount(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, recoveryCodeCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const restrictRecoverySession = `-- name: RestrictRecoverySession :exec
UPDATE sessions SET mfa_at='epoch' WHERE id=$1
`

func (q *Queries) RestrictRecoverySession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, restrictRecoverySession, id)
	return err
}

const seedGlobalAdmin = `-- name: SeedGlobalAdmin :execrows
UPDATE users SET global_admin=true,mfa_enabled=false,admin_seeded_at=now() WHERE email=$1 AND active AND admin_seeded_at IS NULL
`

func (q *Queries) SeedGlobalAdmin(ctx context.Context, email string) (int64, error) {
	result, err := q.db.Exec(ctx, seedGlobalAdmin, email)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAccountMFA = `-- name: SetAccountMFA :exec
UPDATE users SET mfa_enabled=$2 WHERE id=$1
`

type SetAccountMFAParams struct {
	ID         string
	MfaEnabled bool
}

func (q *Queries) SetAccountMFA(ctx context.Context, arg SetAccountMFAParams) error {
	_, err := q.db.Exec(ctx, setAccountMFA, arg.ID, arg.MfaEnabled)
	return err
}

const setDisabledMFASeed = `-- name: SetDisabledMFASeed :exec
UPDATE users SET totp_ciphertext=$2,last_totp_step=0 WHERE id=$1 AND NOT mfa_enabled
`

type SetDisabledMFASeedParams struct {
	ID             string
	TotpCiphertext []byte
}

func (q *Queries) SetDisabledMFASeed(ctx context.Context, arg SetDisabledMFASeedParams) error {
	_, err := q.db.Exec(ctx, setDisabledMFASeed, arg.ID, arg.TotpCiphertext)
	return err
}
