// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resource_summary.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const resourceSummary = `-- name: ResourceSummary :many
SELECT (CASE $1::text WHEN 'provider' THEN provider WHEN 'kind' THEN kind ELSE status END)::text AS label,
count(*)::bigint AS total, min(observed_at)::timestamptz AS oldest_observation
FROM filtered_inventory($2::text,$3::text,$4::text,$5::text,$6::text,$7::text,$8::text,$9::boolean,$10::text,$11::jsonb,$12::boolean,$13::text,$14::text) GROUP BY 1 ORDER BY 1 LIMIT 1001
`

type ResourceSummaryParams struct {
	GroupBy       string
	OrgID         string
	Search        string
	Provider      string
	Kind          string
	ConnectionID  string
	TagKey        string
	TagValue      string
	TagExists     bool
	TagName       string
	TagConditions []byte
	TagMatchAny   bool
	FilterRegion  string
	FilterStatus  string
}

type ResourceSummaryRow struct {
	Label             string
	Total             int64
	OldestObservation pgtype.Timestamptz
}

func (q *Queries) ResourceSummary(ctx context.Context, arg ResourceSummaryParams) ([]ResourceSummaryRow, error) {
	rows, err := q.db.Query(ctx, resourceSummary,
		arg.GroupBy,
		arg.OrgID,
		arg.Search,
		arg.Provider,
		arg.Kind,
		arg.ConnectionID,
		arg.TagKey,
		arg.TagValue,
		arg.TagExists,
		arg.TagName,
		arg.TagConditions,
		arg.TagMatchAny,
		arg.FilterRegion,
		arg.FilterStatus,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResourceSummaryRow{}
	for rows.Next() {
		var i ResourceSummaryRow
		if err := rows.Scan(&i.Label, &i.Total, &i.OldestObservation); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
