// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resource_policy.sql

package database

import (
	"context"
)

const getResourcePolicy = `-- name: GetResourcePolicy :one
SELECT approval_actions,creation_enabled,resource_policy_revision AS revision FROM organizations WHERE id=$1
`

type GetResourcePolicyRow struct {
	ApprovalActions []string
	CreationEnabled bool
	Revision        int64
}

func (q *Queries) GetResourcePolicy(ctx context.Context, id string) (GetResourcePolicyRow, error) {
	row := q.db.QueryRow(ctx, getResourcePolicy, id)
	var i GetResourcePolicyRow
	err := row.Scan(&i.ApprovalActions, &i.CreationEnabled, &i.Revision)
	return i, err
}

const saveResourcePolicy = `-- name: SaveResourcePolicy :execrows
UPDATE organizations SET creation_enabled=$2,approval_actions=$4::text[],resource_policy_revision=resource_policy_revision+1 WHERE id=$1 AND resource_policy_revision=$3
`

type SaveResourcePolicyParams struct {
	ID                     string
	CreationEnabled        bool
	ResourcePolicyRevision int64
	ApprovalActions        []string
}

func (q *Queries) SaveResourcePolicy(ctx context.Context, arg SaveResourcePolicyParams) (int64, error) {
	result, err := q.db.Exec(ctx, saveResourcePolicy,
		arg.ID,
		arg.CreationEnabled,
		arg.ResourcePolicyRevision,
		arg.ApprovalActions,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
