// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resource_scopes.sql

package database

import (
	"context"
)

const listResourceScopes = `-- name: ListResourceScopes :many
SELECT 'connection'::text AS kind,c.id::text AS value,c.name::text AS label FROM connections c WHERE c.org_id=$1 AND EXISTS(SELECT 1 FROM resources r WHERE r.org_id=c.org_id AND r.connection_id=c.id AND r.deleted_at IS NULL)
UNION ALL
SELECT DISTINCT 'region'::text,region::text,region::text FROM resources WHERE org_id=$1 AND deleted_at IS NULL AND region<>''
UNION ALL
SELECT DISTINCT 'status'::text,status::text,status::text FROM resources WHERE org_id=$1 AND deleted_at IS NULL AND status<>''
ORDER BY 1,3,2 LIMIT 1001
`

type ListResourceScopesRow struct {
	Kind  string
	Value string
	Label string
}

func (q *Queries) ListResourceScopes(ctx context.Context, orgID string) ([]ListResourceScopesRow, error) {
	rows, err := q.db.Query(ctx, listResourceScopes, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListResourceScopesRow{}
	for rows.Next() {
		var i ListResourceScopesRow
		if err := rows.Scan(&i.Kind, &i.Value, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
