// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schedules.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addScheduleOccurrence = `-- name: AddScheduleOccurrence :exec
INSERT INTO schedule_occurrences(org_id,schedule_id,revision,resource_id,scheduled_for,action,outcome,detail,operation_id,local_time) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT DO NOTHING
`

type AddScheduleOccurrenceParams struct {
	OrgID        string
	ScheduleID   string
	Revision     int64
	ResourceID   string
	ScheduledFor pgtype.Timestamptz
	Action       string
	Outcome      string
	Detail       string
	OperationID  pgtype.Text
	LocalTime    string
}

func (q *Queries) AddScheduleOccurrence(ctx context.Context, arg AddScheduleOccurrenceParams) error {
	_, err := q.db.Exec(ctx, addScheduleOccurrence,
		arg.OrgID,
		arg.ScheduleID,
		arg.Revision,
		arg.ResourceID,
		arg.ScheduledFor,
		arg.Action,
		arg.Outcome,
		arg.Detail,
		arg.OperationID,
		arg.LocalTime,
	)
	return err
}

const addScheduleTarget = `-- name: AddScheduleTarget :exec
INSERT INTO schedule_targets(org_id,schedule_id,resource_id,connection_id,connection_revision,module_revision) VALUES($1,$2,$3,$4,$5,coalesce((SELECT m.revision FROM provider_modules m JOIN connections c ON c.org_id=m.org_id AND c.provider=m.provider WHERE c.org_id=$1 AND c.id=$4),1))
`

type AddScheduleTargetParams struct {
	OrgID              string
	ScheduleID         string
	ResourceID         string
	ConnectionID       string
	ConnectionRevision int64
}

func (q *Queries) AddScheduleTarget(ctx context.Context, arg AddScheduleTargetParams) error {
	_, err := q.db.Exec(ctx, addScheduleTarget,
		arg.OrgID,
		arg.ScheduleID,
		arg.ResourceID,
		arg.ConnectionID,
		arg.ConnectionRevision,
	)
	return err
}

const advanceSchedule = `-- name: AdvanceSchedule :exec
UPDATE schedules SET clock_version=2,next_due=$3,next_action=$4,next_local=$5,next_skip=$6,last_outcome=$7,last_detail=$8,updated_at=now() WHERE org_id=$1 AND id=$2
`

type AdvanceScheduleParams struct {
	OrgID       string
	ID          string
	NextDue     pgtype.Timestamptz
	NextAction  string
	NextLocal   string
	NextSkip    string
	LastOutcome string
	LastDetail  string
}

func (q *Queries) AdvanceSchedule(ctx context.Context, arg AdvanceScheduleParams) error {
	_, err := q.db.Exec(ctx, advanceSchedule,
		arg.OrgID,
		arg.ID,
		arg.NextDue,
		arg.NextAction,
		arg.NextLocal,
		arg.NextSkip,
		arg.LastOutcome,
		arg.LastDetail,
	)
	return err
}

const approveSchedule = `-- name: ApproveSchedule :exec
UPDATE schedules SET write_revision=write_revision+1,approved_revision=revision,approver_id=$3,maintenance_revision=$4,approver_oidc_id=$5::uuid,approved_at=now(),updated_at=now() WHERE org_id=$1 AND id=$2
`

type ApproveScheduleParams struct {
	OrgID               string
	ID                  string
	ApproverID          pgtype.Text
	MaintenanceRevision int64
	OidcID              pgtype.UUID
}

func (q *Queries) ApproveSchedule(ctx context.Context, arg ApproveScheduleParams) error {
	_, err := q.db.Exec(ctx, approveSchedule,
		arg.OrgID,
		arg.ID,
		arg.ApproverID,
		arg.MaintenanceRevision,
		arg.OidcID,
	)
	return err
}

const bindScheduledOperation = `-- name: BindScheduledOperation :exec
UPDATE operations SET schedule_id=$3,schedule_revision=$4,automation_identity_id=$5,scheduled_for=$6,approver_id=$7,approval_expires_at=$8,expires_at=$8 WHERE org_id=$1 AND id=$2
`

type BindScheduledOperationParams struct {
	OrgID                string
	ID                   string
	ScheduleID           pgtype.Text
	ScheduleRevision     pgtype.Int8
	AutomationIdentityID pgtype.Text
	ScheduledFor         pgtype.Timestamptz
	ApproverID           pgtype.Text
	ApprovalExpiresAt    pgtype.Timestamptz
}

func (q *Queries) BindScheduledOperation(ctx context.Context, arg BindScheduledOperationParams) error {
	_, err := q.db.Exec(ctx, bindScheduledOperation,
		arg.OrgID,
		arg.ID,
		arg.ScheduleID,
		arg.ScheduleRevision,
		arg.AutomationIdentityID,
		arg.ScheduledFor,
		arg.ApproverID,
		arg.ApprovalExpiresAt,
	)
	return err
}

const claimDueSchedule = `-- name: ClaimDueSchedule :one
SELECT id, org_id, name, editor_id, editor_email, identity_id, identity_enabled, enabled, revision, spec, policy_version, approved_revision, approver_id, approved_at, next_due, next_action, next_local, next_skip, last_outcome, last_detail, created_at, updated_at, deleted_at, maintenance_revision, clock_version, editor_oidc_id, approver_oidc_id, write_revision FROM schedules WHERE deleted_at IS NULL AND (next_due<=now() OR (clock_version<2 AND next_due IS NOT NULL)) ORDER BY next_due,id FOR UPDATE SKIP LOCKED LIMIT 1
`

func (q *Queries) ClaimDueSchedule(ctx context.Context) (Schedule, error) {
	row := q.db.QueryRow(ctx, claimDueSchedule)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.EditorID,
		&i.EditorEmail,
		&i.IdentityID,
		&i.IdentityEnabled,
		&i.Enabled,
		&i.Revision,
		&i.Spec,
		&i.PolicyVersion,
		&i.ApprovedRevision,
		&i.ApproverID,
		&i.ApprovedAt,
		&i.NextDue,
		&i.NextAction,
		&i.NextLocal,
		&i.NextSkip,
		&i.LastOutcome,
		&i.LastDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.MaintenanceRevision,
		&i.ClockVersion,
		&i.EditorOidcID,
		&i.ApproverOidcID,
		&i.WriteRevision,
	)
	return i, err
}

const clearScheduleTargets = `-- name: ClearScheduleTargets :exec
DELETE FROM schedule_targets WHERE org_id=$1 AND schedule_id=$2
`

type ClearScheduleTargetsParams struct {
	OrgID      string
	ScheduleID string
}

func (q *Queries) ClearScheduleTargets(ctx context.Context, arg ClearScheduleTargetsParams) error {
	_, err := q.db.Exec(ctx, clearScheduleTargets, arg.OrgID, arg.ScheduleID)
	return err
}

const createSchedule = `-- name: CreateSchedule :exec
INSERT INTO schedules(id,org_id,name,editor_id,editor_email,identity_id,spec,next_due,next_action,next_local,next_skip) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
`

type CreateScheduleParams struct {
	ID          string
	OrgID       string
	Name        string
	EditorID    string
	EditorEmail string
	IdentityID  string
	Spec        []byte
	NextDue     pgtype.Timestamptz
	NextAction  string
	NextLocal   string
	NextSkip    string
}

func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) error {
	_, err := q.db.Exec(ctx, createSchedule,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.EditorID,
		arg.EditorEmail,
		arg.IdentityID,
		arg.Spec,
		arg.NextDue,
		arg.NextAction,
		arg.NextLocal,
		arg.NextSkip,
	)
	return err
}

const deleteSchedule = `-- name: DeleteSchedule :exec
UPDATE schedules SET write_revision=write_revision+1,enabled=false,identity_enabled=false,deleted_at=now(),updated_at=now() WHERE org_id=$1 AND id=$2
`

type DeleteScheduleParams struct {
	OrgID string
	ID    string
}

func (q *Queries) DeleteSchedule(ctx context.Context, arg DeleteScheduleParams) error {
	_, err := q.db.Exec(ctx, deleteSchedule, arg.OrgID, arg.ID)
	return err
}

const getSchedule = `-- name: GetSchedule :one
SELECT id, org_id, name, editor_id, editor_email, identity_id, identity_enabled, enabled, revision, spec, policy_version, approved_revision, approver_id, approved_at, next_due, next_action, next_local, next_skip, last_outcome, last_detail, created_at, updated_at, deleted_at, maintenance_revision, clock_version, editor_oidc_id, approver_oidc_id, write_revision FROM schedules WHERE org_id=$1 AND id=$2 AND deleted_at IS NULL
`

type GetScheduleParams struct {
	OrgID string
	ID    string
}

func (q *Queries) GetSchedule(ctx context.Context, arg GetScheduleParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, getSchedule, arg.OrgID, arg.ID)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.EditorID,
		&i.EditorEmail,
		&i.IdentityID,
		&i.IdentityEnabled,
		&i.Enabled,
		&i.Revision,
		&i.Spec,
		&i.PolicyVersion,
		&i.ApprovedRevision,
		&i.ApproverID,
		&i.ApprovedAt,
		&i.NextDue,
		&i.NextAction,
		&i.NextLocal,
		&i.NextSkip,
		&i.LastOutcome,
		&i.LastDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.MaintenanceRevision,
		&i.ClockVersion,
		&i.EditorOidcID,
		&i.ApproverOidcID,
		&i.WriteRevision,
	)
	return i, err
}

const listScheduleOccurrences = `-- name: ListScheduleOccurrences :many
SELECT x.id, x.org_id, x.schedule_id, x.revision, x.resource_id, x.scheduled_for, x.action, x.outcome, x.detail, x.operation_id, x.created_at, x.local_time,coalesce(o.status,'')::text AS operation_status,r.name AS resource_name FROM schedule_occurrences x JOIN resources r ON r.org_id=x.org_id AND r.id=x.resource_id LEFT JOIN operations o ON o.org_id=x.org_id AND o.id=x.operation_id WHERE x.org_id=$1 AND x.id<$2 AND ($3::text='' OR x.schedule_id=$3) AND ($4::text='' OR x.outcome=$4) ORDER BY x.id DESC LIMIT 101
`

type ListScheduleOccurrencesParams struct {
	OrgID      string
	ID         int64
	ScheduleID string
	Outcome    string
}

type ListScheduleOccurrencesRow struct {
	ID              int64
	OrgID           string
	ScheduleID      string
	Revision        int64
	ResourceID      string
	ScheduledFor    pgtype.Timestamptz
	Action          string
	Outcome         string
	Detail          string
	OperationID     pgtype.Text
	CreatedAt       pgtype.Timestamptz
	LocalTime       string
	OperationStatus string
	ResourceName    string
}

func (q *Queries) ListScheduleOccurrences(ctx context.Context, arg ListScheduleOccurrencesParams) ([]ListScheduleOccurrencesRow, error) {
	rows, err := q.db.Query(ctx, listScheduleOccurrences,
		arg.OrgID,
		arg.ID,
		arg.ScheduleID,
		arg.Outcome,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScheduleOccurrencesRow{}
	for rows.Next() {
		var i ListScheduleOccurrencesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ScheduleID,
			&i.Revision,
			&i.ResourceID,
			&i.ScheduledFor,
			&i.Action,
			&i.Outcome,
			&i.Detail,
			&i.OperationID,
			&i.CreatedAt,
			&i.LocalTime,
			&i.OperationStatus,
			&i.ResourceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleTargets = `-- name: ListScheduleTargets :many
SELECT t.org_id, t.schedule_id, t.resource_id, t.connection_id, t.connection_revision, t.module_revision,r.name,r.native_id,r.provider,r.region,r.status,r.kind,r.observed_at,r.deleted_at FROM schedule_targets t JOIN resources r ON r.org_id=t.org_id AND r.id=t.resource_id WHERE t.org_id=$1 AND t.schedule_id=$2 ORDER BY t.connection_id,t.resource_id
`

type ListScheduleTargetsParams struct {
	OrgID      string
	ScheduleID string
}

type ListScheduleTargetsRow struct {
	OrgID              string
	ScheduleID         string
	ResourceID         string
	ConnectionID       string
	ConnectionRevision int64
	ModuleRevision     int64
	Name               string
	NativeID           string
	Provider           string
	Region             string
	Status             string
	Kind               string
	ObservedAt         pgtype.Timestamptz
	DeletedAt          pgtype.Timestamptz
}

func (q *Queries) ListScheduleTargets(ctx context.Context, arg ListScheduleTargetsParams) ([]ListScheduleTargetsRow, error) {
	rows, err := q.db.Query(ctx, listScheduleTargets, arg.OrgID, arg.ScheduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScheduleTargetsRow{}
	for rows.Next() {
		var i ListScheduleTargetsRow
		if err := rows.Scan(
			&i.OrgID,
			&i.ScheduleID,
			&i.ResourceID,
			&i.ConnectionID,
			&i.ConnectionRevision,
			&i.ModuleRevision,
			&i.Name,
			&i.NativeID,
			&i.Provider,
			&i.Region,
			&i.Status,
			&i.Kind,
			&i.ObservedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedules = `-- name: ListSchedules :many
SELECT id, org_id, name, editor_id, editor_email, identity_id, identity_enabled, enabled, revision, spec, policy_version, approved_revision, approver_id, approved_at, next_due, next_action, next_local, next_skip, last_outcome, last_detail, created_at, updated_at, deleted_at, maintenance_revision, clock_version, editor_oidc_id, approver_oidc_id, write_revision FROM schedules WHERE org_id=$1 AND deleted_at IS NULL ORDER BY name,id LIMIT 1001
`

func (q *Queries) ListSchedules(ctx context.Context, orgID string) ([]Schedule, error) {
	rows, err := q.db.Query(ctx, listSchedules, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Schedule{}
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.EditorID,
			&i.EditorEmail,
			&i.IdentityID,
			&i.IdentityEnabled,
			&i.Enabled,
			&i.Revision,
			&i.Spec,
			&i.PolicyVersion,
			&i.ApprovedRevision,
			&i.ApproverID,
			&i.ApprovedAt,
			&i.NextDue,
			&i.NextAction,
			&i.NextLocal,
			&i.NextSkip,
			&i.LastOutcome,
			&i.LastDetail,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.MaintenanceRevision,
			&i.ClockVersion,
			&i.EditorOidcID,
			&i.ApproverOidcID,
			&i.WriteRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSchedule = `-- name: LockSchedule :one
SELECT id, org_id, name, editor_id, editor_email, identity_id, identity_enabled, enabled, revision, spec, policy_version, approved_revision, approver_id, approved_at, next_due, next_action, next_local, next_skip, last_outcome, last_detail, created_at, updated_at, deleted_at, maintenance_revision, clock_version, editor_oidc_id, approver_oidc_id, write_revision FROM schedules WHERE org_id=$1 AND id=$2 AND deleted_at IS NULL FOR UPDATE
`

type LockScheduleParams struct {
	OrgID string
	ID    string
}

func (q *Queries) LockSchedule(ctx context.Context, arg LockScheduleParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, lockSchedule, arg.OrgID, arg.ID)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.EditorID,
		&i.EditorEmail,
		&i.IdentityID,
		&i.IdentityEnabled,
		&i.Enabled,
		&i.Revision,
		&i.Spec,
		&i.PolicyVersion,
		&i.ApprovedRevision,
		&i.ApproverID,
		&i.ApprovedAt,
		&i.NextDue,
		&i.NextAction,
		&i.NextLocal,
		&i.NextSkip,
		&i.LastOutcome,
		&i.LastDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.MaintenanceRevision,
		&i.ClockVersion,
		&i.EditorOidcID,
		&i.ApproverOidcID,
		&i.WriteRevision,
	)
	return i, err
}

const refreshScheduleClock = `-- name: RefreshScheduleClock :exec
UPDATE schedules SET clock_version=2,next_due=$3,next_action=$4,next_local=$5,next_skip=$6,updated_at=now() WHERE org_id=$1 AND id=$2
`

type RefreshScheduleClockParams struct {
	OrgID      string
	ID         string
	NextDue    pgtype.Timestamptz
	NextAction string
	NextLocal  string
	NextSkip   string
}

func (q *Queries) RefreshScheduleClock(ctx context.Context, arg RefreshScheduleClockParams) error {
	_, err := q.db.Exec(ctx, refreshScheduleClock,
		arg.OrgID,
		arg.ID,
		arg.NextDue,
		arg.NextAction,
		arg.NextLocal,
		arg.NextSkip,
	)
	return err
}

const resourceOperationBusy = `-- name: ResourceOperationBusy :one
SELECT EXISTS(SELECT 1 FROM operations WHERE org_id=$1 AND resource_id=$2 AND status IN ('awaiting_approval','queued','dispatching','observing','uncertain'))
`

type ResourceOperationBusyParams struct {
	OrgID      string
	ResourceID pgtype.Text
}

func (q *Queries) ResourceOperationBusy(ctx context.Context, arg ResourceOperationBusyParams) (bool, error) {
	row := q.db.QueryRow(ctx, resourceOperationBusy, arg.OrgID, arg.ResourceID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const scheduleAuthorizesOperation = `-- name: ScheduleAuthorizesOperation :one
SELECT EXISTS(SELECT 1 FROM schedules s JOIN schedule_targets t ON t.org_id=s.org_id AND t.schedule_id=s.id WHERE s.org_id=$1 AND s.id=$2 AND s.revision=$3 AND s.identity_id=$4 AND t.resource_id=$5 AND t.connection_revision=$6 AND s.deleted_at IS NULL AND s.enabled AND s.identity_enabled AND s.approved_revision=s.revision AND s.maintenance_revision=(SELECT maintenance_revision FROM organizations WHERE id=s.org_id) AND identity_allows(s.org_id,s.editor_id,s.editor_oidc_id) AND identity_allows(s.org_id,s.approver_id,s.approver_oidc_id) AND s.policy_version='power-v1' AND (s.spec->>'action'=$7::text OR (s.spec->>'action'='window' AND $7::text IN ('start','shutdown'))))
`

type ScheduleAuthorizesOperationParams struct {
	OrgID              string
	ID                 string
	Revision           int64
	IdentityID         string
	ResourceID         string
	ConnectionRevision int64
	Action             string
}

func (q *Queries) ScheduleAuthorizesOperation(ctx context.Context, arg ScheduleAuthorizesOperationParams) (bool, error) {
	row := q.db.QueryRow(ctx, scheduleAuthorizesOperation,
		arg.OrgID,
		arg.ID,
		arg.Revision,
		arg.IdentityID,
		arg.ResourceID,
		arg.ConnectionRevision,
		arg.Action,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setScheduleEnabled = `-- name: SetScheduleEnabled :exec
UPDATE schedules SET write_revision=write_revision+1,enabled=$3,identity_enabled=$4,updated_at=now() WHERE org_id=$1 AND id=$2
`

type SetScheduleEnabledParams struct {
	OrgID           string
	ID              string
	Enabled         bool
	IdentityEnabled bool
}

func (q *Queries) SetScheduleEnabled(ctx context.Context, arg SetScheduleEnabledParams) error {
	_, err := q.db.Exec(ctx, setScheduleEnabled,
		arg.OrgID,
		arg.ID,
		arg.Enabled,
		arg.IdentityEnabled,
	)
	return err
}

const updateSchedule = `-- name: UpdateSchedule :exec
UPDATE schedules SET write_revision=write_revision+1,clock_version=2,name=$3,editor_id=$4,editor_email=$5,spec=$6,revision=revision+1,approved_revision=NULL,approver_id=NULL,approved_at=NULL,next_due=$7,next_action=$8,next_local=$9,next_skip=$10,updated_at=now() WHERE org_id=$1 AND id=$2
`

type UpdateScheduleParams struct {
	OrgID       string
	ID          string
	Name        string
	EditorID    string
	EditorEmail string
	Spec        []byte
	NextDue     pgtype.Timestamptz
	NextAction  string
	NextLocal   string
	NextSkip    string
}

func (q *Queries) UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) error {
	_, err := q.db.Exec(ctx, updateSchedule,
		arg.OrgID,
		arg.ID,
		arg.Name,
		arg.EditorID,
		arg.EditorEmail,
		arg.Spec,
		arg.NextDue,
		arg.NextAction,
		arg.NextLocal,
		arg.NextSkip,
	)
	return err
}
