// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sources.sql

package database

import (
	"context"
)

const getAutomationSourceMetadata = `-- name: GetAutomationSourceMetadata :one
SELECT id,name,runtime,entrypoint,sha256,files,archive_bytes,expanded_bytes,input_schema FROM automation_sources WHERE org_id=$1 AND id=$2
`

type GetAutomationSourceMetadataParams struct {
	OrgID string
	ID    string
}

type GetAutomationSourceMetadataRow struct {
	ID            string
	Name          string
	Runtime       string
	Entrypoint    string
	Sha256        string
	Files         []string
	ArchiveBytes  int32
	ExpandedBytes int64
	InputSchema   []byte
}

func (q *Queries) GetAutomationSourceMetadata(ctx context.Context, arg GetAutomationSourceMetadataParams) (GetAutomationSourceMetadataRow, error) {
	row := q.db.QueryRow(ctx, getAutomationSourceMetadata, arg.OrgID, arg.ID)
	var i GetAutomationSourceMetadataRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Runtime,
		&i.Entrypoint,
		&i.Sha256,
		&i.Files,
		&i.ArchiveBytes,
		&i.ExpandedBytes,
		&i.InputSchema,
	)
	return i, err
}

const importAutomationSource = `-- name: ImportAutomationSource :one
INSERT INTO automation_sources(id,org_id,name,runtime,entrypoint,sha256,files,archive_bytes,expanded_bytes,ciphertext,input_schema,storage)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
ON CONFLICT(org_id,runtime,entrypoint,sha256) DO UPDATE SET sha256=automation_sources.sha256
RETURNING id
`

type ImportAutomationSourceParams struct {
	ID            string
	OrgID         string
	Name          string
	Runtime       string
	Entrypoint    string
	Sha256        string
	Files         []string
	ArchiveBytes  int32
	ExpandedBytes int64
	Ciphertext    []byte
	InputSchema   []byte
	Storage       string
}

func (q *Queries) ImportAutomationSource(ctx context.Context, arg ImportAutomationSourceParams) (string, error) {
	row := q.db.QueryRow(ctx, importAutomationSource,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Runtime,
		arg.Entrypoint,
		arg.Sha256,
		arg.Files,
		arg.ArchiveBytes,
		arg.ExpandedBytes,
		arg.Ciphertext,
		arg.InputSchema,
		arg.Storage,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const listAutomationSources = `-- name: ListAutomationSources :many
SELECT id,name,runtime,entrypoint,sha256,files,archive_bytes,expanded_bytes,input_schema FROM automation_sources WHERE org_id=$1 ORDER BY created_at DESC,id LIMIT 51
`

type ListAutomationSourcesRow struct {
	ID            string
	Name          string
	Runtime       string
	Entrypoint    string
	Sha256        string
	Files         []string
	ArchiveBytes  int32
	ExpandedBytes int64
	InputSchema   []byte
}

func (q *Queries) ListAutomationSources(ctx context.Context, orgID string) ([]ListAutomationSourcesRow, error) {
	rows, err := q.db.Query(ctx, listAutomationSources, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAutomationSourcesRow{}
	for rows.Next() {
		var i ListAutomationSourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Runtime,
			&i.Entrypoint,
			&i.Sha256,
			&i.Files,
			&i.ArchiveBytes,
			&i.ExpandedBytes,
			&i.InputSchema,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rebindSourceArtifact = `-- name: RebindSourceArtifact :exec
UPDATE automation_sources SET ciphertext=$2 WHERE id=$1 AND storage='s3'
`

type RebindSourceArtifactParams struct {
	ID         string
	Ciphertext []byte
}

func (q *Queries) RebindSourceArtifact(ctx context.Context, arg RebindSourceArtifactParams) error {
	_, err := q.db.Exec(ctx, rebindSourceArtifact, arg.ID, arg.Ciphertext)
	return err
}

const rebindStateArtifact = `-- name: RebindStateArtifact :exec
UPDATE automation_states SET ciphertext=$2 WHERE id=$1 AND storage='s3'
`

type RebindStateArtifactParams struct {
	ID         string
	Ciphertext []byte
}

func (q *Queries) RebindStateArtifact(ctx context.Context, arg RebindStateArtifactParams) error {
	_, err := q.db.Exec(ctx, rebindStateArtifact, arg.ID, arg.Ciphertext)
	return err
}

const recoveryArtifact = `-- name: RecoveryArtifact :one
SELECT kind,id,org_id,object_key::text,ciphertext FROM (
 SELECT 'sources'::text AS kind,id,org_id,'sources/'||org_id||'/'||id AS object_key,ciphertext FROM automation_sources WHERE storage='s3'
 UNION ALL
 SELECT 'states'::text AS kind,id,org_id,'states/'||org_id||'/'||project_id||'/'||id AS object_key,ciphertext FROM automation_states WHERE storage='s3'
) objects WHERE (kind,id)>($1::text,$2::text) ORDER BY kind,id LIMIT 1
`

type RecoveryArtifactParams struct {
	AfterKind string
	AfterID   string
}

type RecoveryArtifactRow struct {
	Kind       string
	ID         string
	OrgID      string
	ObjectKey  string
	Ciphertext []byte
}

func (q *Queries) RecoveryArtifact(ctx context.Context, arg RecoveryArtifactParams) (RecoveryArtifactRow, error) {
	row := q.db.QueryRow(ctx, recoveryArtifact, arg.AfterKind, arg.AfterID)
	var i RecoveryArtifactRow
	err := row.Scan(
		&i.Kind,
		&i.ID,
		&i.OrgID,
		&i.ObjectKey,
		&i.Ciphertext,
	)
	return i, err
}

const verifyAutomationSource = `-- name: VerifyAutomationSource :one
SELECT id, org_id, name, runtime, entrypoint, sha256, files, archive_bytes, expanded_bytes, ciphertext, created_at, input_schema, storage FROM automation_sources WHERE id>$1 ORDER BY id LIMIT 1
`

func (q *Queries) VerifyAutomationSource(ctx context.Context, id string) (AutomationSource, error) {
	row := q.db.QueryRow(ctx, verifyAutomationSource, id)
	var i AutomationSource
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Runtime,
		&i.Entrypoint,
		&i.Sha256,
		&i.Files,
		&i.ArchiveBytes,
		&i.ExpandedBytes,
		&i.Ciphertext,
		&i.CreatedAt,
		&i.InputSchema,
		&i.Storage,
	)
	return i, err
}
