// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teams.sql

package database

import (
	"context"
)

const addTeamMember = `-- name: AddTeamMember :execrows
INSERT INTO team_members(org_id,team_id,user_id) SELECT $1,$2,m.user_id FROM memberships m WHERE m.org_id=$1 AND m.user_id=$3
`

type AddTeamMemberParams struct {
	OrgID  string
	TeamID string
	UserID string
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, addTeamMember, arg.OrgID, arg.TeamID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createTeam = `-- name: CreateTeam :exec
INSERT INTO teams(org_id,id,name,role_id,active) VALUES($1,$2,$3,$4,$5)
`

type CreateTeamParams struct {
	OrgID  string
	ID     string
	Name   string
	RoleID string
	Active bool
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) error {
	_, err := q.db.Exec(ctx, createTeam,
		arg.OrgID,
		arg.ID,
		arg.Name,
		arg.RoleID,
		arg.Active,
	)
	return err
}

const deleteTeam = `-- name: DeleteTeam :execrows
DELETE FROM teams WHERE org_id=$1 AND id=$2 AND revision=$3
`

type DeleteTeamParams struct {
	OrgID    string
	ID       string
	Revision int64
}

func (q *Queries) DeleteTeam(ctx context.Context, arg DeleteTeamParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTeam, arg.OrgID, arg.ID, arg.Revision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTeam = `-- name: GetTeam :one
SELECT org_id, id, name, role_id, active, revision FROM teams WHERE org_id=$1 AND id=$2
`

type GetTeamParams struct {
	OrgID string
	ID    string
}

func (q *Queries) GetTeam(ctx context.Context, arg GetTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, getTeam, arg.OrgID, arg.ID)
	var i Team
	err := row.Scan(
		&i.OrgID,
		&i.ID,
		&i.Name,
		&i.RoleID,
		&i.Active,
		&i.Revision,
	)
	return i, err
}

const listTeams = `-- name: ListTeams :many
SELECT t.org_id, t.id, t.name, t.role_id, t.active, t.revision,ARRAY(SELECT tm.user_id FROM team_members tm WHERE tm.org_id=t.org_id AND tm.team_id=t.id ORDER BY tm.user_id)::text[] AS user_ids FROM teams t WHERE t.org_id=$1 ORDER BY t.name,t.id LIMIT 101
`

type ListTeamsRow struct {
	OrgID    string
	ID       string
	Name     string
	RoleID   string
	Active   bool
	Revision int64
	UserIds  []string
}

func (q *Queries) ListTeams(ctx context.Context, orgID string) ([]ListTeamsRow, error) {
	rows, err := q.db.Query(ctx, listTeams, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamsRow{}
	for rows.Next() {
		var i ListTeamsRow
		if err := rows.Scan(
			&i.OrgID,
			&i.ID,
			&i.Name,
			&i.RoleID,
			&i.Active,
			&i.Revision,
			&i.UserIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceTeamMembers = `-- name: ReplaceTeamMembers :exec
DELETE FROM team_members WHERE org_id=$1 AND team_id=$2
`

type ReplaceTeamMembersParams struct {
	OrgID  string
	TeamID string
}

func (q *Queries) ReplaceTeamMembers(ctx context.Context, arg ReplaceTeamMembersParams) error {
	_, err := q.db.Exec(ctx, replaceTeamMembers, arg.OrgID, arg.TeamID)
	return err
}

const updateTeam = `-- name: UpdateTeam :execrows
UPDATE teams SET name=$3,role_id=$4,active=$5,revision=revision+1 WHERE org_id=$1 AND id=$2 AND revision=$6
`

type UpdateTeamParams struct {
	OrgID    string
	ID       string
	Name     string
	RoleID   string
	Active   bool
	Revision int64
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTeam,
		arg.OrgID,
		arg.ID,
		arg.Name,
		arg.RoleID,
		arg.Active,
		arg.Revision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
