// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: templates.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bindOperationTemplate = `-- name: BindOperationTemplate :exec
UPDATE operations SET template_id=$3 WHERE org_id=$1 AND id=$2
`

type BindOperationTemplateParams struct {
	OrgID      string
	ID         string
	TemplateID pgtype.Text
}

func (q *Queries) BindOperationTemplate(ctx context.Context, arg BindOperationTemplateParams) error {
	_, err := q.db.Exec(ctx, bindOperationTemplate, arg.OrgID, arg.ID, arg.TemplateID)
	return err
}

const getServerTemplate = `-- name: GetServerTemplate :one
SELECT id, org_id, connection_id, name, version, region, creation, status, created_at FROM server_templates WHERE org_id=$1 AND id=$2 FOR SHARE
`

type GetServerTemplateParams struct {
	OrgID string
	ID    string
}

func (q *Queries) GetServerTemplate(ctx context.Context, arg GetServerTemplateParams) (ServerTemplate, error) {
	row := q.db.QueryRow(ctx, getServerTemplate, arg.OrgID, arg.ID)
	var i ServerTemplate
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ConnectionID,
		&i.Name,
		&i.Version,
		&i.Region,
		&i.Creation,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listServerTemplates = `-- name: ListServerTemplates :many
SELECT id, org_id, connection_id, name, version, region, creation, status, created_at FROM server_templates WHERE org_id=$1 ORDER BY name,version DESC LIMIT 201
`

func (q *Queries) ListServerTemplates(ctx context.Context, orgID string) ([]ServerTemplate, error) {
	rows, err := q.db.Query(ctx, listServerTemplates, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServerTemplate{}
	for rows.Next() {
		var i ServerTemplate
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ConnectionID,
			&i.Name,
			&i.Version,
			&i.Region,
			&i.Creation,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishServerTemplate = `-- name: PublishServerTemplate :one
INSERT INTO server_templates(id,org_id,connection_id,name,version,region,creation)
SELECT $1,$2,$3,$4,coalesce(max(version),0)+1,$5,$6
FROM server_templates WHERE org_id=$2 AND name=$4
RETURNING id, org_id, connection_id, name, version, region, creation, status, created_at
`

type PublishServerTemplateParams struct {
	ID           string
	OrgID        string
	ConnectionID string
	Name         string
	Region       string
	Creation     []byte
}

func (q *Queries) PublishServerTemplate(ctx context.Context, arg PublishServerTemplateParams) (ServerTemplate, error) {
	row := q.db.QueryRow(ctx, publishServerTemplate,
		arg.ID,
		arg.OrgID,
		arg.ConnectionID,
		arg.Name,
		arg.Region,
		arg.Creation,
	)
	var i ServerTemplate
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ConnectionID,
		&i.Name,
		&i.Version,
		&i.Region,
		&i.Creation,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const setServerTemplateStatus = `-- name: SetServerTemplateStatus :one
UPDATE server_templates SET status=$3 WHERE org_id=$1 AND id=$2 AND (status='published' OR (status='retired' AND $3='revoked')) RETURNING id, org_id, connection_id, name, version, region, creation, status, created_at
`

type SetServerTemplateStatusParams struct {
	OrgID  string
	ID     string
	Status string
}

func (q *Queries) SetServerTemplateStatus(ctx context.Context, arg SetServerTemplateStatusParams) (ServerTemplate, error) {
	row := q.db.QueryRow(ctx, setServerTemplateStatus, arg.OrgID, arg.ID, arg.Status)
	var i ServerTemplate
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ConnectionID,
		&i.Name,
		&i.Version,
		&i.Region,
		&i.Creation,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
