FROM gcr.io/distroless/static-debian12:nonroot@sha256:afa5c872c891853ca7fcf1f12c3edb23f7eeef36189728842dd51042ff57f7ab AS runtime
ARG EDITION=community
ARG SOURCE=https://github.com/alphabravo-oss/providah-community
ARG REVISION=development
ARG VERSION=development
LABEL org.opencontainers.image.source=$SOURCE org.opencontainers.image.revision=$REVISION org.opencontainers.image.version=$VERSION io.providah.edition=$EDITION
FROM runtime AS egress
COPY egress-proxy /egress-proxy
COPY --chown=65532:65532 egress/ /run/egress/
USER 65532:65532
HEALTHCHECK --interval=1s --timeout=1s --retries=3 CMD ["/egress-proxy", "health"]
ENTRYPOINT ["/egress-proxy"]
FROM runtime AS provider
COPY provider /provider
ENTRYPOINT ["/provider"]
FROM docker:cli@sha256:eccaacfeed644c7de222ff047483568cb988dde95476fbaaf10ea2d04921bb66 AS launcher
ARG EDITION=community
ARG SOURCE=https://github.com/alphabravo-oss/providah-community
ARG REVISION=development
ARG VERSION=development
LABEL org.opencontainers.image.source=$SOURCE org.opencontainers.image.revision=$REVISION org.opencontainers.image.version=$VERSION io.providah.edition=$EDITION
COPY launcher /launcher
HEALTHCHECK --interval=2s --timeout=3s --start-period=360s --retries=5 CMD ["/launcher", "health"]
ENTRYPOINT ["/launcher"]
FROM runtime AS app
COPY providah /providah
COPY web /web
EXPOSE 8080
ENTRYPOINT ["/providah"]
