-- +goose Up
ALTER TABLE operations DROP CONSTRAINT operations_resource_kind_check;
ALTER TABLE operations ADD CONSTRAINT operations_resource_kind_check CHECK(resource_kind IN ('compute.placement_group','organization.project','compute.image','compute.server','storage.snapshot','storage.volume','database.instance','database.cluster','network.network','network.firewall','access.ssh_key','database.snapshot','database.cluster_snapshot','network.load_balancer'));
ALTER TABLE operations DROP CONSTRAINT operation_kind_action;
ALTER TABLE operations ADD CONSTRAINT operation_kind_action CHECK((resource_kind='compute.placement_group' AND provider IN ('aws','hetzner') AND action='delete') OR (resource_kind='organization.project' AND provider='digitalocean' AND action='delete') OR (resource_kind='compute.image' AND provider='aws' AND action='delete') OR resource_kind='compute.server' OR (resource_kind IN ('storage.snapshot','storage.volume','access.ssh_key') AND action='delete') OR (resource_kind IN ('network.network','network.firewall') AND action='delete' AND provider IN ('digitalocean','hetzner')) OR (resource_kind IN ('database.instance','database.cluster') AND provider='aws' AND action IN ('start','shutdown') AND provider_identity<>'') OR (resource_kind='network.firewall' AND provider='aws' AND action='delete') OR (resource_kind IN ('database.snapshot','database.cluster_snapshot') AND provider='aws' AND action='delete') OR (resource_kind='network.load_balancer' AND provider IN ('aws','digitalocean','hetzner') AND action='delete'));
CREATE UNIQUE INDEX operation_placement_group_busy ON operations(org_id,connection_id,native_id,(CASE WHEN provider='aws' THEN region ELSE '' END)) WHERE resource_kind='compute.placement_group' AND status IN ('awaiting_approval','queued','dispatching','observing','uncertain');
-- +goose Down
ALTER TABLE operations DROP CONSTRAINT operations_resource_kind_check;
ALTER TABLE operations ADD CONSTRAINT operations_resource_kind_check CHECK(resource_kind IN ('organization.project','compute.image','compute.server','storage.snapshot','storage.volume','database.instance','database.cluster','network.network','network.firewall','access.ssh_key','database.snapshot','database.cluster_snapshot','network.load_balancer'));
ALTER TABLE operations DROP CONSTRAINT operation_kind_action;
ALTER TABLE operations ADD CONSTRAINT operation_kind_action CHECK((resource_kind='organization.project' AND provider='digitalocean' AND action='delete') OR (resource_kind='compute.image' AND provider='aws' AND action='delete') OR resource_kind='compute.server' OR (resource_kind IN ('storage.snapshot','storage.volume','access.ssh_key') AND action='delete') OR (resource_kind IN ('network.network','network.firewall') AND action='delete' AND provider IN ('digitalocean','hetzner')) OR (resource_kind IN ('database.instance','database.cluster') AND provider='aws' AND action IN ('start','shutdown') AND provider_identity<>'') OR (resource_kind='network.firewall' AND provider='aws' AND action='delete') OR (resource_kind IN ('database.snapshot','database.cluster_snapshot') AND provider='aws' AND action='delete') OR (resource_kind='network.load_balancer' AND provider IN ('aws','digitalocean','hetzner') AND action='delete'));
DROP INDEX operation_placement_group_busy;
